#!/usr/bin/env python3
"""Export the browser's B mark to every product icon slot.

The B is drawn from UnifrakturCook Bold, the blackletter face JD
approved on 2026-09-19 (artifacts/brand-review/unifrakturcook-b.png).
The font and its licence are archived under branding/source/. It is
under the SIL Open Font License 1.1, which allows redistribution, so
these outputs are cleared for distribution. The shape is approved as it
stands: do not change the glyph, the geometry or the colours without
another review.

One master drives everything:

  branding/master/b-tile.svg   plate + B, 64 box (app icon)
  branding/master/b-glyph.svg  B only, currentColor (pages)

The B is positioned exactly as design/v2/brand-preview.svg lays out its
text: 49px, text-anchor middle at x=30, baseline
y=48, on a 60x60 rx17 #176b5b plate at (2,2). The outline is written
into the SVG as a path, so nothing depends on the font at run time.

From that master this tool rasterises (pure Python: flattened quadratic
curves, nonzero fill, exact horizontal / supersampled vertical coverage)
the ICO and PNG files Chromium compiles into chrome.exe, chrome.dll and
the resource paks, and writes them under boring-core/chromium_src/ so
tools/apply.py overlays them onto the build tree (with pristine backups).
It also writes components/boring/branding/brand_mark.h for the pages.

Output is deterministic: the same inputs give byte-identical files.

Usage:
  python tools/export_brand.py                 regenerate + manifest
  python tools/export_brand.py --check         regenerate into a temp dir
                                               and verify every hash
  python tools/export_brand.py --preview DIR   also write enlarged previews
                                               on light and dark backgrounds
"""

import argparse
import hashlib
import json
import math
import os
import shutil
import struct
import sys
import tempfile
import zlib

CORE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_SOURCE = "branding/source/UnifrakturCook-Bold.ttf"
FONT_LICENCE = "branding/source/UnifrakturCook-OFL.txt"
DEFAULT_FONT = os.path.join(CORE, FONT_SOURCE.replace("/", os.sep))
MANIFEST = "branding/manifest.json"

TILE_SVG = "branding/master/b-tile.svg"
GLYPH_SVG = "branding/master/b-glyph.svg"
HEADER = "components/boring/branding/brand_mark.h"
DOC_SOURCE = "branding/source/chromium_doc.ico"
PDF_SOURCE = "branding/source/chromium_pdf.ico"

# The demo mark, design/v2/brand-preview.svg.
PLATE_COLOR = (0x17, 0x6B, 0x5B)
GLYPH_COLOR = (0xFA, 0xF9, 0xF6)
PLATE = (2.0, 2.0, 60.0, 60.0, 17.0)  # x, y, w, h, rx in the 64 box
FONT_SIZE = 49.0
ANCHOR_X = 30.0
BASELINE_Y = 48.0
CHAR = "B"

# Small sizes: same master outline, a plate that fills the canvas, a
# larger B (scaled about the centre of its own bounds, so it stays where
# the master puts it) and a coverage boost (coverage ** glyph_gamma) so
# the thin serif strokes do not wash out at 16-24 px. Everything 32 px
# and up uses the master exactly.
SIZE_TWEAKS = {
    16: {"plate": [0.0, 0.0, 64.0, 64.0, 13.0], "glyph_scale": 1.25, "glyph_gamma": 0.7},
    20: {"plate": [0.0, 0.0, 64.0, 64.0, 14.0], "glyph_scale": 1.2, "glyph_gamma": 0.75},
    24: {"plate": [0.0, 0.0, 64.0, 64.0, 15.0], "glyph_scale": 1.14, "glyph_gamma": 0.8},
}

ICO_SIZES = [16, 20, 24, 32, 40, 48, 64, 96, 128, 256]

MARK_LABEL = "the boring browser's logo"
PROVENANCE = (
    "The boring browser's B. Outline from UnifrakturCook Bold, copyright "
    "2010 j. 'mach' wust and 2009 Peter Wiegel, SIL Open Font License 1.1; "
    "the font and its licence are archived under "
    "boring-core/branding/source/. Approved 2026-09-19. Generated by "
    "boring-core/tools/export_brand.py."
)


# ---------------------------------------------------------------------------
# TrueType reading (cmap format 4, head, hhea/hmtx, loca, glyf).


class Font:
    def __init__(self, data):
        self.data = data
        count = struct.unpack(">H", data[4:6])[0]
        self.tables = {}
        for i in range(count):
            tag, _sum, off, length = struct.unpack(
                ">4sIII", data[12 + 16 * i : 28 + 16 * i]
            )
            self.tables[tag.decode("latin-1")] = (off, length)
        head = self.tables["head"][0]
        self.units_per_em = struct.unpack(">H", data[head + 18 : head + 20])[0]
        self.loca_format = struct.unpack(">h", data[head + 50 : head + 52])[0]
        maxp = self.tables["maxp"][0]
        self.num_glyphs = struct.unpack(">H", data[maxp + 4 : maxp + 6])[0]
        hhea = self.tables["hhea"][0]
        self.num_hmetrics = struct.unpack(">H", data[hhea + 34 : hhea + 36])[0]

    def glyph_index(self, ch):
        data = self.data
        cmap = self.tables["cmap"][0]
        count = struct.unpack(">H", data[cmap + 2 : cmap + 4])[0]
        sub = None
        for i in range(count):
            pid, eid, off = struct.unpack(
                ">HHI", data[cmap + 4 + 8 * i : cmap + 12 + 8 * i]
            )
            fmt = struct.unpack(">H", data[cmap + off : cmap + off + 2])[0]
            if fmt == 4 and (pid, eid) in ((3, 1), (0, 3), (0, 4), (3, 0)):
                sub = cmap + off
                if (pid, eid) == (3, 1):
                    break
        if sub is None:
            raise SystemExit("font has no cmap format 4 subtable")
        code = ord(ch)
        seg2 = struct.unpack(">H", data[sub + 6 : sub + 8])[0]
        ends = sub + 14
        starts = ends + seg2 + 2
        deltas = starts + seg2
        ranges = deltas + seg2
        for i in range(seg2 // 2):
            end = struct.unpack(">H", data[ends + 2 * i : ends + 2 * i + 2])[0]
            if code > end:
                continue
            start = struct.unpack(">H", data[starts + 2 * i : starts + 2 * i + 2])[0]
            if code < start:
                return 0
            delta = struct.unpack(">h", data[deltas + 2 * i : deltas + 2 * i + 2])[0]
            roff_at = ranges + 2 * i
            roff = struct.unpack(">H", data[roff_at : roff_at + 2])[0]
            if roff == 0:
                return (code + delta) & 0xFFFF
            at = roff_at + roff + 2 * (code - start)
            gid = struct.unpack(">H", data[at : at + 2])[0]
            return (gid + delta) & 0xFFFF if gid else 0
        return 0

    def advance(self, gid):
        hmtx = self.tables["hmtx"][0]
        i = min(gid, self.num_hmetrics - 1)
        return struct.unpack(">H", self.data[hmtx + 4 * i : hmtx + 4 * i + 2])[0]

    def _glyph_range(self, gid):
        loca = self.tables["loca"][0]
        if self.loca_format == 0:
            a, b = struct.unpack(">HH", self.data[loca + 2 * gid : loca + 2 * gid + 4])
            return a * 2, b * 2
        return struct.unpack(">II", self.data[loca + 4 * gid : loca + 4 * gid + 8])

    def contours(self, gid, depth=0):
        """Contours as lists of (x, y, on_curve) in font units."""
        if depth > 8:
            raise SystemExit("composite glyph nesting too deep")
        start, end = self._glyph_range(gid)
        if start == end:
            return []
        data = self.data
        g = self.tables["glyf"][0] + start
        ncont = struct.unpack(">h", data[g : g + 2])[0]
        if ncont >= 0:
            return self._simple(g, ncont)
        return self._composite(g, depth)

    def _simple(self, g, ncont):
        data = self.data
        p = g + 10
        end_pts = list(struct.unpack(">%dH" % ncont, data[p : p + 2 * ncont]))
        p += 2 * ncont
        npts = end_pts[-1] + 1 if end_pts else 0
        ilen = struct.unpack(">H", data[p : p + 2])[0]
        p += 2 + ilen
        flags = []
        while len(flags) < npts:
            f = data[p]
            p += 1
            flags.append(f)
            if f & 8:
                rep = data[p]
                p += 1
                flags.extend([f] * rep)
        xs = []
        v = 0
        for f in flags:
            if f & 2:
                d = data[p]
                p += 1
                v += d if f & 16 else -d
            elif not f & 16:
                v += struct.unpack(">h", data[p : p + 2])[0]
                p += 2
            xs.append(v)
        ys = []
        v = 0
        for f in flags:
            if f & 4:
                d = data[p]
                p += 1
                v += d if f & 32 else -d
            elif not f & 32:
                v += struct.unpack(">h", data[p : p + 2])[0]
                p += 2
            ys.append(v)
        out = []
        first = 0
        for last in end_pts:
            out.append(
                [(xs[i], ys[i], bool(flags[i] & 1)) for i in range(first, last + 1)]
            )
            first = last + 1
        return out

    def _composite(self, g, depth):
        data = self.data
        p = g + 10
        out = []
        while True:
            flags, gid = struct.unpack(">HH", data[p : p + 4])
            p += 4
            if flags & 1:
                a1, a2 = struct.unpack(">hh", data[p : p + 4])
                p += 4
            else:
                a1, a2 = struct.unpack(">bb", data[p : p + 2])
                p += 2
            m = [1.0, 0.0, 0.0, 1.0]
            if flags & 8:
                s = struct.unpack(">h", data[p : p + 2])[0] / 16384.0
                p += 2
                m = [s, 0.0, 0.0, s]
            elif flags & 0x40:
                sx, sy = struct.unpack(">hh", data[p : p + 4])
                p += 4
                m = [sx / 16384.0, 0.0, 0.0, sy / 16384.0]
            elif flags & 0x80:
                vals = struct.unpack(">hhhh", data[p : p + 8])
                p += 8
                m = [v / 16384.0 for v in vals]
            if not flags & 2:
                raise SystemExit("point-matched composite glyphs not supported")
            for c in self.contours(gid, depth + 1):
                out.append(
                    [
                        (
                            m[0] * x + m[2] * y + a1,
                            m[1] * x + m[3] * y + a2,
                            on,
                        )
                        for x, y, on in c
                    ]
                )
            if not flags & 0x20:
                break
        return out


def fmt(v):
    s = "%.3f" % v
    s = s.rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def glyph_outline(font):
    """The B as closed contours of ('L', p) / ('Q', c, p) in the 64 box.

    Coordinates are rounded to 3 decimals once, here, so the SVG path and
    the rasteriser use exactly the same numbers.
    """
    gid = font.glyph_index(CHAR)
    if not gid:
        raise SystemExit("font has no glyph for %r" % CHAR)
    adv = font.advance(gid)
    scale = FONT_SIZE / font.units_per_em
    x0 = ANCHOR_X - adv * scale / 2.0  # text-anchor: middle

    def xf(x, y):
        return (
            float(fmt(x0 + x * scale)),
            float(fmt(BASELINE_Y - y * scale)),
        )

    contours = []
    for raw in font.contours(gid):
        pts = [(x, y, on) for x, y, on in raw]
        if not any(on for _x, _y, on in pts):
            mx = (pts[-1][0] + pts[0][0]) / 2.0
            my = (pts[-1][1] + pts[0][1]) / 2.0
            pts = [(mx, my, True)] + pts
        else:
            k = next(i for i, p in enumerate(pts) if p[2])
            pts = pts[k:] + pts[:k]
        start = pts[0]
        segs = []
        ctrl = None
        for x, y, on in pts[1:] + [start]:
            if on:
                if ctrl is None:
                    segs.append(("L", xf(x, y)))
                else:
                    segs.append(("Q", xf(*ctrl), xf(x, y)))
                    ctrl = None
            else:
                if ctrl is not None:
                    mid = ((ctrl[0] + x) / 2.0, (ctrl[1] + y) / 2.0)
                    segs.append(("Q", xf(*ctrl), xf(*mid)))
                ctrl = (x, y)
        s = xf(start[0], start[1])
        if segs and segs[-1][0] == "L" and segs[-1][1] == s:
            segs.pop()
        contours.append((s, segs))
    info = {
        "glyph_id": gid,
        "advance_units": adv,
        "units_per_em": font.units_per_em,
        "text_start_x": round(x0, 6),
    }
    return contours, info


def outline_path(contours):
    parts = []
    for start, segs in contours:
        cmd = ["M%s %s" % (fmt(start[0]), fmt(start[1]))]
        for seg in segs:
            if seg[0] == "L":
                cmd.append("L%s %s" % (fmt(seg[1][0]), fmt(seg[1][1])))
            else:
                cmd.append(
                    "Q%s %s %s %s"
                    % (fmt(seg[1][0]), fmt(seg[1][1]), fmt(seg[2][0]), fmt(seg[2][1]))
                )
        cmd.append("Z")
        parts.append("".join(cmd))
    return "".join(parts)


def outline_bounds(contours):
    xs = []
    ys = []
    for start, segs in contours:
        xs.append(start[0])
        ys.append(start[1])
        for seg in segs:
            for p in seg[1:]:
                xs.append(p[0])
                ys.append(p[1])
    return min(xs), min(ys), max(xs), max(ys)


def hexcolor(c):
    return "#%02x%02x%02x" % c


def tile_svg(path_d):
    x, y, w, h, rx = PLATE
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" '
        'viewBox="0 0 64 64" role="img" aria-label="B mark, %s">\n'
        "<title>B mark, %s</title>\n"
        "<!-- %s -->\n"
        '<rect x="%s" y="%s" width="%s" height="%s" rx="%s" fill="%s"/>\n'
        '<path fill="%s" d="%s"/>\n'
        "</svg>\n"
        % (
            MARK_LABEL,
            MARK_LABEL,
            PROVENANCE,
            fmt(x),
            fmt(y),
            fmt(w),
            fmt(h),
            fmt(rx),
            hexcolor(PLATE_COLOR),
            hexcolor(GLYPH_COLOR),
            path_d,
        )
    )


def glyph_svg(path_d):
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" '
        'viewBox="0 0 64 64" role="img" aria-label="B mark, %s">\n'
        "<title>B mark, %s</title>\n"
        "<!-- %s -->\n"
        '<path fill="currentColor" d="%s"/>\n'
        "</svg>\n" % (MARK_LABEL, MARK_LABEL, PROVENANCE, path_d)
    )


def header_text(tile, glyph):
    for svg in (tile, glyph):
        if ')SVG"' in svg:
            raise SystemExit("svg would end the raw string early")
    return (
        "// Copyright 2026 boring. BSD style license.\n"
        "//\n"
        "// GENERATED by boring-core/tools/export_brand.py. Do not edit by hand;\n"
        "// change the master and run the tool again.\n"
        "//\n"
        "// The outline comes from UnifrakturCook Bold (SIL Open Font License\n"
        "// 1.1), archived with its licence under boring-core/branding/source/.\n"
        "//\n"
        "// Both strings are byte-identical to branding/master/*.svg.\n"
        "\n"
        "#ifndef COMPONENTS_BORING_BRANDING_BRAND_MARK_H_\n"
        "#define COMPONENTS_BORING_BRANDING_BRAND_MARK_H_\n"
        "\n"
        "namespace boring::branding {\n"
        "\n"
        "// Plate + B, 64 viewBox. For favicons and app-style marks.\n"
        'inline constexpr char kBrandTileSvg[] = R"SVG(' + tile + ')SVG";\n'
        "\n"
        "// B only, fill=\"currentColor\", same 64 viewBox and placement.\n"
        'inline constexpr char kBrandGlyphSvg[] = R"SVG(' + glyph + ')SVG";\n'
        "\n"
        "}  // namespace boring::branding\n"
        "\n"
        "#endif  // COMPONENTS_BORING_BRANDING_BRAND_MARK_H_\n"
    )


# ---------------------------------------------------------------------------
# Rasterising.


class Xform:
    """Maps the 64 box to pixels: p * scale + offset."""

    def __init__(self, scale, ox, oy):
        self.scale = scale
        self.ox = ox
        self.oy = oy

    def __call__(self, p):
        return (p[0] * self.scale + self.ox, p[1] * self.scale + self.oy)


def flatten_outline(contours, xf, glyph_scale=1.0, tol=0.05):
    b = outline_bounds(contours)
    cx = (b[0] + b[2]) / 2.0
    cy = (b[1] + b[3]) / 2.0

    def g(p):
        if glyph_scale == 1.0:
            return xf(p)
        return xf((cx + (p[0] - cx) * glyph_scale, cy + (p[1] - cy) * glyph_scale))

    polys = []
    for start, segs in contours:
        cur = g(start)
        poly = [cur]
        for seg in segs:
            if seg[0] == "L":
                cur = g(seg[1])
                poly.append(cur)
            else:
                c = g(seg[1])
                e = g(seg[2])
                dx = cur[0] - 2 * c[0] + e[0]
                dy = cur[1] - 2 * c[1] + e[1]
                dev = math.hypot(dx, dy) / 4.0
                n = max(1, int(math.ceil(math.sqrt(dev / tol))))
                for i in range(1, n + 1):
                    t = i / n
                    u = 1 - t
                    poly.append(
                        (
                            u * u * cur[0] + 2 * u * t * c[0] + t * t * e[0],
                            u * u * cur[1] + 2 * u * t * c[1] + t * t * e[1],
                        )
                    )
                cur = e
        polys.append(poly)
    return polys


def rounded_rect(x, y, w, h, r, xf, tol=0.05):
    r = min(r, w / 2.0, h / 2.0)
    rp = r * xf.scale
    if rp <= 0:
        pts = [(x, y), (x + w, y), (x + w, y + h), (x, y + h)]
        return [[xf(p) for p in pts]]
    # Segments per quarter so the chord error stays under tol pixels.
    n = max(2, int(math.ceil((math.pi / 2) / (2 * math.acos(max(-1.0, 1 - tol / rp))))))
    corners = [
        (x + w - r, y + r, -math.pi / 2),
        (x + w - r, y + h - r, 0.0),
        (x + r, y + h - r, math.pi / 2),
        (x + r, y + r, math.pi),
    ]
    pts = []
    for cx, cy, a0 in corners:
        for i in range(n + 1):
            a = a0 + (math.pi / 2) * i / n
            pts.append(xf((cx + r * math.cos(a), cy + r * math.sin(a))))
    return [pts]


def coverage(polys, width, height, ss):
    """Nonzero coverage in [0, 1]: ss sub-rows per pixel, exact spans in x."""
    edges = []
    for poly in polys:
        n = len(poly)
        for i in range(n):
            x0, y0 = poly[i]
            x1, y1 = poly[(i + 1) % n]
            if y0 == y1:
                continue
            d = 1
            if y0 > y1:
                x0, y0, x1, y1 = x1, y1, x0, y0
                d = -1
            edges.append((y0, y1, x0, (x1 - x0) / (y1 - y0), d))
    edges.sort()
    cov = [0.0] * (width * height)
    active = []
    ei = 0
    w = 1.0 / ss
    for j in range(height * ss):
        y = (j + 0.5) / ss
        while ei < len(edges) and edges[ei][0] <= y:
            active.append(edges[ei])
            ei += 1
        active = [e for e in active if e[1] > y]
        if not active:
            continue
        xs = sorted((e[2] + (y - e[0]) * e[3], e[4]) for e in active)
        row = (j // ss) * width
        wind = 0
        for k in range(len(xs) - 1):
            wind += xs[k][1]
            if wind == 0:
                continue
            a = max(0.0, xs[k][0])
            b = min(float(width), xs[k + 1][0])
            if b <= a:
                continue
            ia = int(a)
            ib = int(b)
            if ia == ib:
                cov[row + ia] += (b - a) * w
                continue
            cov[row + ia] += (ia + 1 - a) * w
            for i in range(ia + 1, ib):
                cov[row + i] += w
            if ib < width:
                cov[row + ib] += (b - ib) * w
    return [c if c < 1.0 else 1.0 for c in cov]


def supersample_for(size):
    return 16 if size > 128 else 32


class Canvas:
    """Premultiplied float RGBA."""

    def __init__(self, width, height):
        self.width = width
        self.height = height
        self.px = [(0.0, 0.0, 0.0, 0.0)] * (width * height)

    @classmethod
    def from_rgba(cls, width, height, rgba):
        c = cls(width, height)
        px = []
        for r, g, b, a in rgba:
            af = a / 255.0
            px.append((r / 255.0 * af, g / 255.0 * af, b / 255.0 * af, af))
        c.px = px
        return c

    def fill(self, cov, color):
        cr, cg, cb = (v / 255.0 for v in color)
        px = self.px
        for i, c in enumerate(cov):
            if c <= 0.0:
                continue
            r, g, b, a = px[i]
            k = 1.0 - c
            px[i] = (cr * c + r * k, cg * c + g * k, cb * c + b * k, c + a * k)

    def rgba(self):
        out = bytearray()
        for r, g, b, a in self.px:
            ai = int(round(a * 255))
            if ai <= 0:
                out += b"\0\0\0\0"
                continue
            out += bytes(
                (
                    min(255, int(round(r / a * 255))),
                    min(255, int(round(g / a * 255))),
                    min(255, int(round(b / a * 255))),
                    min(255, ai),
                )
            )
        return bytes(out)


def draw_tile(canvas, outline, scale, ox, oy, size_hint):
    """Paint plate + B with the 64 box mapped by scale/offset."""
    tweak = SIZE_TWEAKS.get(size_hint)
    if tweak:
        px_, py_, pw, ph, prx = tweak["plate"]
        gs = tweak["glyph_scale"]
        gamma = tweak["glyph_gamma"]
    else:
        px_, py_, pw, ph, prx = PLATE
        gs = 1.0
        gamma = 1.0
    xf = Xform(scale, ox, oy)
    ss = supersample_for(max(canvas.width, canvas.height))
    plate = coverage(rounded_rect(px_, py_, pw, ph, prx, xf), canvas.width, canvas.height, ss)
    canvas.fill(plate, PLATE_COLOR)
    glyph = coverage(flatten_outline(outline, xf, gs), canvas.width, canvas.height, ss)
    if gamma != 1.0:
        glyph = [c ** gamma if c > 0.0 else 0.0 for c in glyph]
    # The B only shows where the plate is (it always sits inside it).
    canvas.fill([min(a, b) for a, b in zip(glyph, plate)], GLYPH_COLOR)


def tile_image(outline, size):
    c = Canvas(size, size)
    draw_tile(c, outline, size / 64.0, 0.0, 0.0, size)
    return c


def tile_in_square(outline, width, height, left, top, side, size_hint=None):
    """B tile whose plate fills the square (left, top, side) in pixels."""
    c = Canvas(width, height)
    tweak = SIZE_TWEAKS.get(size_hint)
    px_, py_, pw, _ph, _rx = tweak["plate"] if tweak else PLATE
    scale = side / pw
    ox = left - px_ * scale
    oy = top - py_ * scale
    draw_tile(c, outline, scale, ox, oy, size_hint)
    return c


# ---------------------------------------------------------------------------
# PNG and ICO.


def png_bytes(width, height, rgba):
    stride = width * 4
    raw = bytearray()
    prev = bytes(stride)
    for y in range(height):
        line = rgba[y * stride : (y + 1) * stride]
        sub = bytes((line[i] - (line[i - 4] if i >= 4 else 0)) & 255 for i in range(stride))
        up = bytes((line[i] - prev[i]) & 255 for i in range(stride))
        best = min(
            ((0, line), (1, sub), (2, up)),
            key=lambda fl: sum(v if v < 128 else 256 - v for v in fl[1]),
        )
        raw.append(best[0])
        raw += best[1]
        prev = line

    def chunk(tag, body):
        return (
            struct.pack(">I", len(body))
            + tag
            + body
            + struct.pack(">I", zlib.crc32(tag + body) & 0xFFFFFFFF)
        )

    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(bytes(raw), 9))
        + chunk(b"IEND", b"")
    )


def png_decode(data):
    p = 8
    idat = b""
    pal = trns = None
    while p < len(data):
        length = struct.unpack(">I", data[p : p + 4])[0]
        tag = data[p + 4 : p + 8]
        body = data[p + 8 : p + 8 + length]
        p += 12 + length
        if tag == b"IHDR":
            w, h, depth, ct, _c, _f, interlace = struct.unpack(">IIBBBBB", body)
        elif tag == b"IDAT":
            idat += body
        elif tag == b"PLTE":
            pal = body
        elif tag == b"tRNS":
            trns = body
    if depth != 8 or interlace:
        raise SystemExit("only 8-bit non-interlaced PNG sources are supported")
    bpp = {6: 4, 2: 3, 3: 1, 0: 1, 4: 2}[ct]
    raw = zlib.decompress(idat)
    stride = w * bpp
    prev = bytearray(stride)
    out = []
    i = 0
    for _y in range(h):
        ft = raw[i]
        line = bytearray(raw[i + 1 : i + 1 + stride])
        i += 1 + stride
        for x in range(stride):
            a = line[x - bpp] if x >= bpp else 0
            b = prev[x]
            c = prev[x - bpp] if x >= bpp else 0
            if ft == 1:
                line[x] = (line[x] + a) & 255
            elif ft == 2:
                line[x] = (line[x] + b) & 255
            elif ft == 3:
                line[x] = (line[x] + (a + b) // 2) & 255
            elif ft == 4:
                pp = a + b - c
                pa, pb, pc = abs(pp - a), abs(pp - b), abs(pp - c)
                pr = a if pa <= pb and pa <= pc else (b if pb <= pc else c)
                line[x] = (line[x] + pr) & 255
        for x in range(w):
            if ct == 6:
                out.append(tuple(line[4 * x : 4 * x + 4]))
            elif ct == 2:
                out.append(tuple(line[3 * x : 3 * x + 3]) + (255,))
            elif ct == 3:
                k = line[x]
                alpha = trns[k] if trns and k < len(trns) else 255
                out.append(tuple(pal[3 * k : 3 * k + 3]) + (alpha,))
            elif ct == 0:
                out.append((line[x], line[x], line[x], 255))
            else:
                out.append((line[2 * x], line[2 * x], line[2 * x], line[2 * x + 1]))
        prev = line
    return w, h, out


def bmp32_frame(width, height, rgba):
    """BITMAPINFOHEADER + bottom-up BGRA + AND mask, as Windows icons store it."""
    mask_stride = ((width + 31) // 32) * 4
    xor = bytearray()
    mask = bytearray()
    for y in range(height - 1, -1, -1):
        row = rgba[y * width * 4 : (y + 1) * width * 4]
        bits = bytearray(mask_stride)
        for x in range(width):
            r, g, b, a = row[4 * x : 4 * x + 4]
            xor += bytes((b, g, r, a))
            if a == 0:
                bits[x // 8] |= 0x80 >> (x % 8)
        mask += bits
    header = struct.pack(
        "<IiiHHIIiiII", 40, width, height * 2, 1, 32, 0, len(xor) + len(mask), 0, 0, 0, 0
    )
    return header + bytes(xor) + bytes(mask)


def ico_bytes(frames):
    """frames: list of (size, rgba). 256 is stored as PNG, the rest BMP32."""
    frames = sorted(frames, key=lambda f: f[0])
    blobs = []
    for size, rgba in frames:
        if size >= 256:
            blobs.append((size, png_bytes(size, size, rgba)))
        else:
            blobs.append((size, bmp32_frame(size, size, rgba)))
    out = bytearray(struct.pack("<HHH", 0, 1, len(blobs)))
    offset = 6 + 16 * len(blobs)
    for size, blob in blobs:
        dim = 0 if size >= 256 else size
        out += struct.pack("<BBBBHHII", dim, dim, 0, 0, 1, 32, len(blob), offset)
        offset += len(blob)
    for _size, blob in blobs:
        out += blob
    return bytes(out)


def ico_decode(data):
    """32-bit frames of an ICO as {size: rgba tuples}. Palette frames are skipped."""
    count = struct.unpack("<H", data[4:6])[0]
    frames = {}
    for i in range(count):
        w, h, _c, _r, _p, _b, size, off = struct.unpack(
            "<BBBBHHII", data[6 + 16 * i : 22 + 16 * i]
        )
        w = w or 256
        h = h or 256
        blob = data[off : off + size]
        if blob[:4] == b"\x89PNG":
            pw, ph, px = png_decode(blob)
            frames[pw] = px
            continue
        bw, bh2, _planes, bpp = struct.unpack("<IiHH", blob[4:16])
        if bpp != 32:
            continue
        hdr = struct.unpack("<I", blob[:4])[0]
        pix = blob[hdr : hdr + bw * bw * 4]
        rows = []
        for y in range(bw):
            r = pix[y * bw * 4 : (y + 1) * bw * 4]
            rows.append([(r[4 * x + 2], r[4 * x + 1], r[4 * x], r[4 * x + 3]) for x in range(bw)])
        rows.reverse()
        frames[bw] = [p for row in rows for p in row]
    return frames


# ---------------------------------------------------------------------------
# Document / PDF association icons: keep Chromium's page, swap the emblem.


def is_emblem(p):
    r, g, b, a = p
    return a > 60 and b > r + 30 and b > g + 10


def is_label(p):
    r, g, b, a = p
    return a > 200 and max(r, g, b) < 110 and abs(r - g) < 24 and abs(g - b) < 24


def page_color(px, size, y, x_from, step):
    x = x_from
    while 0 <= x < size:
        r, g, b, a = px[y * size + x]
        if a == 255 and min(r, g, b) > 180 and not is_emblem(px[y * size + x]):
            return (r, g, b, a)
        x += step
    return None


def swap_emblem(outline, size, px, keep_label):
    xs = []
    ys = []
    for i, p in enumerate(px):
        if is_emblem(p):
            xs.append(i % size)
            ys.append(i // size)
    if not xs:
        raise SystemExit("no Chromium emblem found in %d px document frame" % size)
    top, bottom, left = min(ys), max(ys) + 1, min(xs)
    radius = (bottom - top) / 2.0
    cy = top + radius
    cx = left + radius

    # Chromium only draws the "PDF" label on its large frames; the small
    # PDF frames are identical to the document ones.
    label = None
    if keep_label and size >= 64:
        lx = [i % size for i, p in enumerate(px) if is_label(p)]
        ly = [i // size for i, p in enumerate(px) if is_label(p)]
        if lx:
            box = (min(lx), min(ly), max(lx) + 1, max(ly) + 1)
            if box[2] - box[0] >= size // 3 and box[3] - box[1] >= size // 8:
                label = box

    # Paint the page back over the emblem, row by row, from the nearest
    # clean page pixels on either side.
    out = list(px)
    reach = radius + 1.0
    for y in range(max(0, int(cy - reach)), min(size, int(math.ceil(cy + reach)))):
        yc = y + 0.5
        dy = yc - cy
        if abs(dy) > reach:
            continue
        half = math.sqrt(max(0.0, reach * reach - dy * dy))
        xa = max(0, int(math.floor(cx - half)))
        xb = min(size - 1, int(math.ceil(cx + half)))
        lc = page_color(px, size, y, xa - 1, -1)
        rc = page_color(px, size, y, xb + 1, 1)
        if lc is None and rc is None:
            continue
        lc = lc or rc
        rc = rc or lc
        for x in range(xa, xb + 1):
            dx = x + 0.5 - cx
            if dx * dx + dy * dy > reach * reach:
                continue
            t = (x - xa + 0.5) / (xb - xa + 1)
            out[y * size + x] = tuple(
                int(round(lc[k] * (1 - t) + rc[k] * t)) for k in range(4)
            )

    canvas = Canvas.from_rgba(size, size, out)
    if size >= 64:
        # A rounded square reads larger than a circle of the same width.
        side = 2 * radius * 0.9
        left = cx - side / 2
        top = cy - side / 2
    else:
        # Small frames: fill the emblem's footprint on whole pixels so the
        # plate edges stay crisp.
        side = float(round(2 * radius))
        left = float(round(cx - side / 2))
        top = float(round(cy - side / 2))
    hint = 16 if side < 28 else None
    tile = tile_in_square(outline, size, size, left, top, side, hint)
    # Composite the tile over the page (source-over, premultiplied).
    merged = []
    for (r, g, b, a), (tr, tg, tb, ta) in zip(canvas.px, tile.px):
        k = 1.0 - ta
        merged.append((tr + r * k, tg + g * k, tb + b * k, ta + a * k))
    canvas.px = merged
    result = bytearray(canvas.rgba())
    if label:
        x0, y0, x1, y1 = label
        for y in range(y0, y1):
            for x in range(x0, x1):
                r, g, b, a = px[y * size + x]
                # Label body and its white text are neutral; anything
                # tinted blue is the old emblem showing at the edge.
                if a < 200 or abs(r - g) >= 24 or abs(g - b) >= 24:
                    continue
                i = (y * size + x) * 4
                result[i : i + 4] = bytes((r, g, b, a))
    return bytes(result)


def doc_ico(outline, source_bytes, keep_label):
    frames = ico_decode(source_bytes)
    out = []
    for size in sorted(frames):
        out.append((size, swap_emblem(outline, size, frames[size], keep_label)))
    return ico_bytes(out), sorted(frames)


# ---------------------------------------------------------------------------
# The output list.


def outputs(outline):
    """Yield (repo path, chromium dest or None, description, bytes)."""
    icon_frames = [(s, tile_image(outline, s).rgba()) for s in ICO_SIZES]
    yield (
        "chromium_src/chrome/app/theme/chromium/win/chromium.ico",
        "chrome/app/theme/chromium/win/chromium.ico",
        "IDR_MAINFRAME in chrome_exe.rc and chrome_dll.rc: exe, window, taskbar, "
        "Alt-Tab, shortcuts; frames " + ",".join(str(s) for s in ICO_SIZES),
        ico_bytes(icon_frames),
    )
    by_size = dict(icon_frames)

    for name, source, label in (
        ("chromium_doc.ico", DOC_SOURCE, False),
        ("chromium_pdf.ico", PDF_SOURCE, True),
    ):
        with open(os.path.join(CORE, source), "rb") as f:
            data, sizes = doc_ico(outline, f.read(), label)
        yield (
            "chromium_src/chrome/app/theme/chromium/win/" + name,
            "chrome/app/theme/chromium/win/" + name,
            "document association icon, Chromium page kept, emblem swapped for "
            "the B tile; frames " + ",".join(str(s) for s in sizes),
            data,
        )

    def png_of(canvas):
        return png_bytes(canvas.width, canvas.height, canvas.rgba())

    def tile_png(size):
        return png_bytes(size, size, by_size[size]) if size in by_size else png_of(
            tile_image(outline, size)
        )

    # Start menu tiles (VisualElements), same plate footprint as Chromium's
    # emblem in its 600 and 176 px tiles.
    yield (
        "chromium_src/chrome/app/theme/chromium/win/tiles/Logo.png",
        "chrome/app/theme/chromium/win/tiles/Logo.png",
        "VisualElements Square150x150Logo, 600x600, plate at 190..410",
        png_of(tile_in_square(outline, 600, 600, 190, 190, 220)),
    )
    yield (
        "chromium_src/chrome/app/theme/chromium/win/tiles/SmallLogo.png",
        "chrome/app/theme/chromium/win/tiles/SmallLogo.png",
        "VisualElements Square70x70/44x44Logo, 176x176, plate at 29..147",
        png_of(tile_in_square(outline, 176, 176, 29, 29, 118)),
    )

    # Unscaled product logos (chrome_unscaled_resources.grd) and the
    # scaled ones (theme_resources.grd, 100 and 200 percent).
    for s in (16, 24, 48, 64, 128, 256):
        yield (
            "chromium_src/chrome/app/theme/chromium/product_logo_%d.png" % s,
            "chrome/app/theme/chromium/product_logo_%d.png" % s,
            "IDR_PRODUCT_LOGO_%d / _SHORTCUTS (unscaled), %dx%d" % (s, s, s),
            tile_png(s),
        )
    for pct, mult in (("100", 1), ("200", 2)):
        for logical in (16, 32):
            s = logical * mult
            yield (
                "chromium_src/chrome/app/theme/default_%s_percent/chromium/product_logo_%d.png"
                % (pct, logical),
                "chrome/app/theme/default_%s_percent/chromium/product_logo_%d.png"
                % (pct, logical),
                "IDR_PRODUCT_LOGO_%d at %s%%, %dx%d" % (logical, pct, s, s),
                tile_png(s),
            )
        # Logo + wordmark: no approved wordmark, so the B tile sits where
        # Chromium's emblem was and the rest of the canvas is clear.
        h = 22 * mult
        w = 97 * mult
        img = png_of(tile_in_square(outline, w, h, 0, 0, h, h if h in SIZE_TWEAKS else None))
        for suffix in ("", "_white"):
            yield (
                "chromium_src/chrome/app/theme/default_%s_percent/chromium/product_logo_name_22%s.png"
                % (pct, suffix),
                "chrome/app/theme/default_%s_percent/chromium/product_logo_name_22%s.png"
                % (pct, suffix),
                "IDR_PRODUCT_LOGO_NAME_22%s at %s%%, %dx%d, B tile only (no wordmark)"
                % (suffix.upper(), pct, w, h),
                img,
            )
        # chrome://version product logo (logo + wordmark), same treatment.
        h = 32 * mult
        w = 171 * mult
        img = png_of(tile_in_square(outline, w, h, 0, 0, h))
        for suffix in ("", "_white"):
            yield (
                "chromium_src/components/resources/default_%s_percent/chromium/product_logo%s.png"
                % (pct, suffix),
                "components/resources/default_%s_percent/chromium/product_logo%s.png"
                % (pct, suffix),
                "IDR_PRODUCT_LOGO%s (chrome://version) at %s%%, %dx%d, B tile only"
                % (suffix.upper(), pct, w, h),
                img,
            )
        s = 16 * mult
        yield (
            "chromium_src/components/resources/default_%s_percent/chromium/favicon_product.png" % pct,
            "components/resources/default_%s_percent/chromium/favicon_product.png" % pct,
            "IDR_PRODUCT_FAVICON at %s%% (chrome://version and, via "
            "branding-resources.patch, the boring pages), %dx%d" % (pct, s, s),
            tile_png(s),
        )
        yield (
            "chromium_src/chrome/app/theme/default_%s_percent/common/favicon_settings.png" % pct,
            "chrome/app/theme/default_%s_percent/common/favicon_settings.png" % pct,
            "IDR_SETTINGS_FAVICON at %s%% (chrome://settings incl. About tab "
            "favicon; its only consumer is settings_utils.cc), %dx%d" % (pct, s, s),
            tile_png(s),
        )

# Chromium's product vector icons (omnibox chip for chrome:// pages, app
# menu, infobars, omnibox actions). Each keeps its original canvas sizes
# so default-size consumers do not change; every representation is the
# B tile in fixed brand colours (PATH_COLOR_ARGB), so tinting callers get
# the same mark as the favicon. Representations under 24 units use the
# 16 px small-size geometry (fuller plate, larger B); gamma cannot be
# expressed in a vector icon, so it is left out.
VECTOR_ICONS = [
    ("components/omnibox/browser/vector_icons/product_chrome_refresh_old.icon",
     [15], "omnibox::kProductChromeRefreshOldIcon: location chip for chrome:// "
     "pages (rounded icons off, our default), app menu Set as default, "
     "infobars, omnibox actions/pedals, chrome:// suggestions"),
    ("components/omnibox/browser/vector_icons/chrome_product.icon",
     [24, 16], "omnibox::kChromeProductIcon: the same slots when rounded icons are on"),
    ("components/omnibox/browser/vector_icons/product_old.icon",
     [32, 16], "omnibox::kProductOldIcon: autofill popup product row"),
    ("components/vector_icons/chromium/product.icon",
     [24, 16], "vector_icons::kProductIcon (branding_path_component=chromium): "
     "autofill AI first-run and plus-address dialogs"),
    ("components/vector_icons/chromium/product_refresh.icon",
     [24, 16], "vector_icons::kProductRefreshIcon: infobars when rounded icons are on"),
]


def vector_icon_text(outline, canvases):
    lines = [
        "// Copyright 2026 boring. BSD style license.",
        "//",
        "// GENERATED by boring-core/tools/export_brand.py from the B master.",
        "// Outline from UnifrakturCook Bold (SIL Open Font License 1.1); see",
        "// boring-core/branding/source/ for the font and its licence.",
        "",
    ]
    for canvas in canvases:
        tweak = SIZE_TWEAKS[16] if canvas < 24 else None
        if tweak:
            px_, py_, pw, ph, prx = tweak["plate"]
            gs = tweak["glyph_scale"]
        else:
            px_, py_, pw, ph, prx = PLATE
            gs = 1.0
        k = canvas / 64.0
        b = outline_bounds(outline)
        cx = (b[0] + b[2]) / 2.0
        cy = (b[1] + b[3]) / 2.0

        def pt(p):
            x = (cx + (p[0] - cx) * gs) * k
            y = (cy + (p[1] - cy) * gs) * k
            return "%s, %s" % (fmt(x), fmt(y))

        lines.append("CANVAS_DIMENSIONS, %d," % canvas)
        lines.append("PATH_COLOR_ARGB, 0xFF, 0x%02X, 0x%02X, 0x%02X," % PLATE_COLOR)
        lines.append("ROUND_RECT, %s, %s, %s, %s, %s," % tuple(
            fmt(v * k) for v in (px_, py_, pw, ph, prx)))
        lines.append("NEW_PATH,")
        lines.append("PATH_COLOR_ARGB, 0xFF, 0x%02X, 0x%02X, 0x%02X," % GLYPH_COLOR)
        lines.append("FILL_RULE_NONZERO,")
        for start, segs in outline:
            lines.append("MOVE_TO, %s," % pt(start))
            for seg in segs:
                if seg[0] == "L":
                    lines.append("LINE_TO, %s," % pt(seg[1]))
                else:
                    lines.append("QUADRATIC_TO, %s, %s," % (pt(seg[1]), pt(seg[2])))
            lines.append("CLOSE,")
        lines.append("")
    return "\n".join(lines)


def text_outputs(tile, glyph, outline):
    """Text files: SVG masters, the page header and Chromium's SVG logos."""
    yield (TILE_SVG, None, "master: plate + B, 64 box", tile)
    yield (GLYPH_SVG, None, "master: B only, currentColor", glyph)
    yield (
        HEADER,
        "components/boring/branding/brand_mark.h (synced by apply.py)",
        "kBrandTileSvg / kBrandGlyphSvg, byte-identical to the masters",
        header_text(tile, glyph),
    )
    yield (
        "chromium_src/chrome/app/theme/chromium/product_logo.svg",
        "chrome/app/theme/chromium/product_logo.svg",
        "IDR_PRODUCT_LOGO_SVG (intro, profile picker, default-browser and "
        "search-engine-choice pages), copy of the tile master",
        tile,
    )
    yield (
        "chromium_src/chrome/app/theme/chromium/product_logo_animation.svg",
        "chrome/app/theme/chromium/product_logo_animation.svg",
        "IDR_PRODUCT_LOGO_ANIMATION_SVG (chrome://intro), static copy of the tile master",
        tile,
    )
    for dest, canvases, use in VECTOR_ICONS:
        yield ("chromium_src/" + dest, dest, use, vector_icon_text(outline, canvases))


# ---------------------------------------------------------------------------


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def normalized(path, data):
    """Text files are hashed with LF endings (git autocrlf may add CR)."""
    if path.endswith((".svg", ".h", ".json", ".icon")):
        return data.replace(b"\r\n", b"\n")
    return data


def png_size(data):
    w, h = struct.unpack(">II", data[16:24])
    return "%dx%d" % (w, h)


def generate(root, font_path):
    with open(font_path, "rb") as f:
        font_data = f.read()
    font = Font(font_data)
    outline, info = glyph_outline(font)
    bounds = outline_bounds(outline)
    for size, tw in SIZE_TWEAKS.items():
        x, y, w, h, _r = tw["plate"]
        gs = tw["glyph_scale"]
        mid = ((bounds[0] + bounds[2]) / 2.0, (bounds[1] + bounds[3]) / 2.0)
        gb = [mid[i % 2] + (v - mid[i % 2]) * gs for i, v in enumerate(bounds)]
        if gb[0] < x or gb[1] < y or gb[2] > x + w or gb[3] > y + h:
            raise SystemExit("glyph leaves the plate at %d px" % size)
    path_d = outline_path(outline)
    tile = tile_svg(path_d)
    glyph = glyph_svg(path_d)

    records = []

    def write(rel, data):
        dest = os.path.join(root, rel.replace("/", os.sep))
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        with open(dest, "wb") as f:
            f.write(data)

    for rel, chromium, desc, text in text_outputs(tile, glyph, outline):
        data = text.encode("utf-8")
        write(rel, data)
        records.append(
            {
                "path": rel,
                "chromium_dest": chromium,
                "use": desc,
                "size": "64x64 viewBox" if rel.endswith(".svg") else None,
                "bytes": len(data),
                "sha256": sha256(data),
            }
        )
    for rel, chromium, desc, data in outputs(outline):
        write(rel, data)
        records.append(
            {
                "path": rel,
                "chromium_dest": chromium,
                "use": desc,
                "size": png_size(data) if rel.endswith(".png") else "multi-frame ICO",
                "bytes": len(data),
                "sha256": sha256(data),
            }
        )

    font_rel = os.path.relpath(font_path, CORE).replace("\\", "/")
    inputs = [
        {
            "path": font_rel if not font_rel.startswith("..") else font_path.replace("\\", "/"),
            "role": "glyph outline source: UnifrakturCook Bold, copyright 2010 "
            "j. 'mach' wust and 2009 Peter Wiegel, SIL Open Font License 1.1. "
            "Approved by JD on 2026-09-19. Redistributable, and the licence "
            "ships beside it.",
            "sha256": sha256(font_data),
        }
    ]
    for rel, role in (
        (FONT_LICENCE, "SIL Open Font License 1.1 for UnifrakturCook Bold, "
                       "kept with the font as the licence requires"),
        (DOC_SOURCE, "Chromium's chromium_doc.ico (BSD), page silhouette kept"),
        (PDF_SOURCE, "Chromium's chromium_pdf.ico (BSD), page and PDF label kept"),
    ):
        with open(os.path.join(CORE, rel), "rb") as f:
            inputs.append({"path": rel, "role": role, "sha256": sha256(f.read())})

    manifest = {
        "generator": "boring-core/tools/export_brand.py",
        "status": "approved",
        "final_asset_available": True,
        "final_asset_note": "JD approved this B on 2026-09-19, from the review "
        "render in artifacts/brand-review/unifrakturcook-b.png. The glyph is "
        "UnifrakturCook Bold under the SIL Open Font License 1.1, archived with "
        "its licence under branding/source/, so these outputs are cleared for "
        "distribution. Do not change the approved shape without another review.",
        "inputs": inputs,
        "masters": {
            "tile": {"path": TILE_SVG, "sha256": sha256(tile.encode("utf-8"))},
            "glyph": {"path": GLYPH_SVG, "sha256": sha256(glyph.encode("utf-8"))},
        },
        "geometry": {
            "source": "design/v2/brand-preview.svg",
            "box": 64,
            "plate": {"x": PLATE[0], "y": PLATE[1], "w": PLATE[2], "h": PLATE[3],
                      "rx": PLATE[4], "fill": hexcolor(PLATE_COLOR)},
            "glyph": {"char": CHAR, "font_size": FONT_SIZE, "anchor": "middle",
                      "anchor_x": ANCHOR_X, "baseline_y": BASELINE_Y,
                      "fill": hexcolor(GLYPH_COLOR),
                      "bounds": [round(v, 3) for v in bounds], **info},
        },
        "size_tweaks": {
            str(k): dict(v, note="derived from the same master outline; plate "
                         "fills the canvas, glyph scaled about the centre of "
                         "its bounds, glyph coverage raised to glyph_gamma")
            for k, v in sorted(SIZE_TWEAKS.items())
        },
        "raster": {
            "fill_rule": "nonzero",
            "coverage": "exact horizontal spans, 32 sub-rows per pixel (16 above 128 px)",
            "blend": "premultiplied source-over in sRGB",
            "ico": "BMP32 + AND mask below 256 px, PNG at 256 (as Chromium's own icons)",
            "zlib_runtime": zlib.ZLIB_RUNTIME_VERSION,
        },
        "outputs": records,
    }
    text = json.dumps(manifest, indent=2, sort_keys=False) + "\n"
    write(MANIFEST, text.encode("utf-8"))
    return manifest


def check(font_path):
    tmp = tempfile.mkdtemp(prefix="boring-brand-")
    ok = True
    try:
        # Sources are read from CORE; outputs go to the temp root.
        fresh = generate(tmp, font_path)
        with open(os.path.join(CORE, MANIFEST), "rb") as f:
            recorded = json.loads(f.read().decode("utf-8"))
        want = {r["path"]: r["sha256"] for r in recorded["outputs"]}
        got = {r["path"]: r["sha256"] for r in fresh["outputs"]}
        for inp_new, inp_old in zip(fresh["inputs"], recorded["inputs"]):
            if inp_new["sha256"] != inp_old["sha256"]:
                print("INPUT CHANGED", inp_old["path"])
                ok = False
        for path in sorted(set(want) | set(got)):
            if want.get(path) != got.get(path):
                print("REGENERATED DIFFERS", path)
                ok = False
                continue
            try:
                with open(os.path.join(CORE, path.replace("/", os.sep)), "rb") as f:
                    have = sha256(normalized(path, f.read()))
            except OSError:
                print("MISSING", path)
                ok = False
                continue
            if have != got[path]:
                print("CHECKED-IN FILE DIFFERS", path)
                ok = False
        with open(os.path.join(tmp, MANIFEST), "rb") as f:
            new_manifest = f.read()
        with open(os.path.join(CORE, MANIFEST), "rb") as f:
            if normalized(".json", f.read()) != new_manifest:
                print("MANIFEST DIFFERS")
                ok = False
        # The header must carry the masters byte for byte.
        with open(os.path.join(tmp, HEADER), "rb") as f:
            header = f.read().decode("utf-8")
        for rel in (TILE_SVG, GLYPH_SVG):
            with open(os.path.join(tmp, rel), "rb") as f:
                if 'R"SVG(' + f.read().decode("utf-8") + ')SVG"' not in header:
                    print("HEADER DOES NOT EMBED", rel)
                    ok = False
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    print("check: %s (%d outputs)" % ("OK" if ok else "FAILED", len(got)))
    return ok


def preview(dest):
    """Enlarged previews of every PNG/ICO frame on light and dark grounds."""
    manifest_path = os.path.join(CORE, MANIFEST)
    with open(manifest_path, encoding="utf-8") as f:
        manifest = json.load(f)
    os.makedirs(dest, exist_ok=True)
    for rec in manifest["outputs"]:
        path = os.path.join(CORE, rec["path"].replace("/", os.sep))
        with open(path, "rb") as f:
            data = f.read()
        if path.endswith(".png"):
            w, h, px = png_decode(data)
            images = [("", w, h, px)]
        elif path.endswith(".ico"):
            images = [("_%d" % s, s, s, px) for s, px in sorted(ico_decode(data).items())]
        else:
            continue
        base = rec["path"].replace("chromium_src/", "").replace("/", "_").replace(".", "_")
        for suffix, w, h, px in images:
            zoom = max(1, min(8, 256 // max(w, h)))
            for ground_name, ground in (("light", (255, 255, 255)), ("dark", (32, 33, 36))):
                out = bytearray()
                for y in range(h * zoom):
                    for x in range(w * zoom):
                        r, g, b, a = px[(y // zoom) * w + x // zoom]
                        k = a / 255.0
                        out += bytes(
                            int(round(c * k + gc * (1 - k))) for c, gc in zip((r, g, b), ground)
                        ) + b"\xff"
                name = "%s%s_%s.png" % (base, suffix, ground_name)
                with open(os.path.join(dest, name), "wb") as f:
                    f.write(png_bytes(w * zoom, h * zoom, bytes(out)))
    print("previews in", dest)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--font", default=DEFAULT_FONT)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--preview", metavar="DIR")
    args = ap.parse_args()
    if args.check:
        sys.exit(0 if check(args.font) else 1)
    manifest = generate(CORE, args.font)
    print("wrote %d outputs (approved B, UnifrakturCook Bold, OFL 1.1)"
          % len(manifest["outputs"]))
    if args.preview:
        preview(args.preview)


if __name__ == "__main__":
    main()
