#!/usr/bin/env python3
"""Build the scam and phishing blocklist. No source is cleared for v1.

PERMITTED_SOURCES is empty, so this tool writes nothing and exits
non-zero. That is the whole point of it right now.

Two feeds were used while this was being built, URLhaus and OpenPhish.
Neither grants permission to redistribute its data inside an installer
and a public update feed: their terms cover getting at the data, not
handing it on. See docs/release/URLHAUS_PERMISSION_REVIEW.md. Fetching a
list we may not pass on, and shipping it anyway, is not a thing to do
quietly, so v1 ships no scam list at all and says so in the browser.
components/boring/core/boring_capabilities.h is the switch that keeps
the browser's claims matching this file.

Everything else here is kept on purpose: the parsers, the floors and the
truncation checks are all tested, and the day a feed we may redistribute
is in place, adding it back to PERMITTED_SOURCES is the whole change.

A fixed test entry is always written into a list when one is built. It
lives below a marker line and is never counted as coverage: a list
holding nothing but test data protects nobody, and the only way to be
sure nobody mistakes one for the other is to keep them apart in the file
rather than subtract one from the other afterwards.

Usage: python get_scamlist.py [--out DIR]
"""

import argparse
import os
import re
import sys
from urllib.parse import urlparse

from get_filterlists import (
    BuildResult,
    FeedError,
    SourceStatus,
    decode_payload,
    fetch_url,
)

DEFAULT_OUT = r"E:\ung\build\src\out\Default"

# Always present, used by the smoke tests. Never counted as coverage.
TEST_HOSTS = ("boring-scam-test.invalid",)

HEADER = "# boring scam blocklist, generated by get_scamlist.py"

# Everything below this line is test data. count_real_hosts() stops
# here, so a test entry can never be read as protection by anything,
# including a future reader that forgets the rule exists.
TEST_MARKER = "# --- test entries below this line, not protection ---"

# Kept so the parsers stay testable against what these feeds really
# send. Neither is fetched: see PERMITTED_SOURCES below.
URLHAUS_URL = "https://urlhaus.abuse.ch/downloads/hostfile/"
OPENPHISH_URL = "https://openphish.com/feed.txt"

# The addresses a hostfile points blocked names at.
HOSTFILE_SINKS = ("127.0.0.1", "0.0.0.0")

# URLhaus ends its hostfile with a count of what it just wrote. When it
# is there we can prove the middle of the download did not go missing.
URLHAUS_TRAILER_RE = re.compile(r"^#\s*Number of entries:\s*(\d+)\s*$")

# A name we are willing to block. Deliberately narrow: whatever ends up
# here is matched against every host the browser visits.
HOSTNAME_RE = re.compile(r"^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9-]+)+\.?$")

# Measured 2026-09-19: every one of URLhaus's 390 non-comment lines and
# every one of OpenPhish's 300 lines parsed. A real feed sits at 100
# per cent, so 90 leaves room for the odd malformed record while still
# refusing a payload that is mostly something else.
MIN_PARSE_RATIO = 0.90

# Measured 2026-09-19: URLhaus held 390 unique hosts and OpenPhish 234.
# 25 is a tenth of the smaller one. This only asks whether a source
# delivered a feed at all; how much coverage is enough is decided in
# publish_lists.py against the previous bundle.
MIN_SOURCE_HOSTS = 25


def parse_hostfile(text: str) -> set[str]:
    """The hosts a hostfile blocks. FeedError if it is not a hostfile."""
    lines = text.splitlines()
    hosts: set[str] = set()
    records = 0
    accepted = 0
    claimed: int | None = None

    for line in lines:
        line = line.strip()
        if not line:
            continue
        if line.startswith("#"):
            match = URLHAUS_TRAILER_RE.match(line)
            if match:
                claimed = int(match.group(1))
            continue
        records += 1
        parts = line.split()
        if len(parts) != 2 or parts[0] not in HOSTFILE_SINKS:
            continue
        host = parts[1].lower().rstrip(".")
        if not HOSTNAME_RE.match(host):
            continue
        accepted += 1
        hosts.add(host)

    if records == 0:
        raise FeedError("no host lines at all")
    ratio = accepted / records
    if ratio < MIN_PARSE_RATIO:
        raise FeedError(f"only {ratio:.0%} of lines are host records")

    # Not a trailing-newline check: URLhaus sends its last line without
    # one, measured 2026-09-19. What a cut mid-download breaks is the
    # last record, so that is what is checked.
    last = next((ln.strip() for ln in reversed(lines) if ln.strip()), "")
    if not last.startswith("#") and (
        len(last.split()) != 2 or last.split()[0] not in HOSTFILE_SINKS
    ):
        raise FeedError("last line is not a whole record, looks truncated")

    # The trailer counts what the feed meant to send. Fewer records than
    # that means part of the body never arrived, which no other check
    # here would notice because what did arrive parses perfectly.
    if claimed is not None and accepted < claimed:
        raise FeedError(f"{accepted} host lines but the feed claims {claimed}")
    return hosts


def parse_url_feed(text: str) -> set[str]:
    """The hosts a list of phishing URLs names. FeedError if it is not one."""
    lines = text.splitlines()
    hosts: set[str] = set()
    records = 0
    accepted = 0

    for line in lines:
        line = line.strip()
        if not line:
            continue
        records += 1
        parsed = urlparse(line)
        if parsed.scheme not in ("http", "https"):
            continue
        host = (parsed.hostname or "").lower().rstrip(".")
        if not HOSTNAME_RE.match(host):
            continue
        accepted += 1
        hosts.add(host)

    if records == 0:
        raise FeedError("no URLs at all")
    ratio = accepted / records
    if ratio < MIN_PARSE_RATIO:
        raise FeedError(f"only {ratio:.0%} of lines are URLs")

    # Every record is one line and the real feed terminates all of
    # them, measured 2026-09-19. A download cut short arrives without
    # the final newline, and half a URL still parses as a URL, so this
    # is the only thing that catches it.
    if not text.endswith("\n"):
        raise FeedError("does not end with a newline, looks truncated")
    return hosts


def _collect(name: str, url: str, parse, fetch_fn) -> tuple[SourceStatus, set[str]]:
    """Fetches and parses one source, and says how it went either way."""
    status = SourceStatus(name=name, url=url)
    try:
        fetched = fetch_fn(url)
        status.http_status = fetched.http_status
        status.bytes = len(fetched.data)
        hosts = parse(decode_payload(fetched))
    except FeedError as e:
        status.reason = str(e)
        return status, set()

    # A feed that happens to name our test host does not get to count
    # it. Stripped here, before anything is counted, so a source's own
    # figure is real coverage too.
    hosts -= set(TEST_HOSTS)

    if len(hosts) < MIN_SOURCE_HOSTS:
        status.entries = len(hosts)
        status.reason = f"only {len(hosts)} hosts"
        return status, set()

    status.entries = len(hosts)
    status.ok = True
    return status, hosts


# The feeds this tool is allowed to fetch and pass on. Empty: no
# provider has given that permission, so nothing is fetched. Adding an
# entry here is a distribution decision, not a coding one, and the
# permission has to be written down before the entry goes in.
PERMITTED_SOURCES: tuple[tuple[str, str, object], ...] = ()


def build_scam_list(fetch=fetch_url) -> BuildResult:
    """Downloads every permitted feed and says how it went.

    With no permitted feeds this returns an empty result and no text
    worth writing, which is what the caller checks. The fetch is a
    parameter so tests can hand in their own without reaching the
    network. Real hosts and test hosts are kept in separate collections
    all the way through, so the count returned is only ever real
    coverage.
    """
    real: set[str] = set()
    sources: list[SourceStatus] = []

    for name, url, parse in PERMITTED_SOURCES:
        status, hosts = _collect(name, url, parse, fetch)
        sources.append(status)
        real |= hosts

    lines = [HEADER, *sorted(real), TEST_MARKER, *sorted(TEST_HOSTS)]
    return BuildResult(text="\n".join(lines) + "\n", entries=len(real), sources=sources)


def count_real_hosts(text: str) -> int:
    """How many real hosts a blocklist's text holds.

    Stops at the test marker, so the entries the smoke tests rely on
    are never counted as protection. A file with no marker is read
    whole, which is what an old bundle written before the marker
    existed looks like.
    """
    total = 0
    for line in text.splitlines():
        line = line.strip()
        if line == TEST_MARKER:
            break
        if line and not line.startswith("#"):
            total += 1
    return total


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=DEFAULT_OUT)
    args = ap.parse_args(argv)

    if not PERMITTED_SOURCES:
        print(
            "no scam feed is cleared for redistribution, so no list is built.\n"
            "This version of the browser ships without scam blocking and says\n"
            "so on its Protection page. See the module docstring and\n"
            "docs/release/URLHAUS_PERMISSION_REVIEW.md."
        )
        return 2

    built = build_scam_list()
    for source in built.sources:
        state = f"{source.entries} hosts" if source.ok else f"FAILED, {source.reason}"
        print(f"  {source.name}: {state}")

    if built.entries == 0:
        print("no scam source came back usable, not writing a list")
        return 1

    dest_dir = os.path.join(args.out, "boring")
    os.makedirs(dest_dir, exist_ok=True)
    out_path = os.path.join(dest_dir, "scamlist.txt")
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(built.text)
    print("wrote", out_path, "with", built.entries, "real hosts")
    if built.degraded:
        print("WARNING: written from some sources only,", built.describe_failures())
    return 0


if __name__ == "__main__":
    sys.exit(main())
