#!/usr/bin/env python3
"""Download open scam and phishing feeds into one blocklist file.

Sources:
  - URLhaus (abuse.ch): hosts serving malware
  - OpenPhish: live phishing pages

Writes boring/scamlist.txt next to chrome.exe, one host per line. The
browser loads it at startup. Run again any time to refresh. A fixed
test entry is always added so the automated tests can rely on it.
"""

import argparse
import os
import urllib.request
from urllib.parse import urlparse

DEFAULT_OUT = r"E:\ung\build\src\out\Default"

# Always present, used by the smoke tests.
TEST_HOSTS = ["boring-scam-test.invalid"]


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    return urllib.request.urlopen(req, timeout=60).read().decode("utf-8", "replace")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=DEFAULT_OUT)
    args = ap.parse_args()

    hosts = set(TEST_HOSTS)

    print("downloading URLhaus hostfile ...")
    try:
        for line in fetch("https://urlhaus.abuse.ch/downloads/hostfile/").splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) == 2:
                hosts.add(parts[1].lower())
    except Exception as e:
        print("  skipped:", e)

    print("downloading OpenPhish feed ...")
    try:
        for line in fetch("https://openphish.com/feed.txt").splitlines():
            line = line.strip()
            if not line:
                continue
            host = urlparse(line).hostname
            if host and "." in host:
                hosts.add(host.lower())
    except Exception as e:
        print("  skipped:", e)

    dest_dir = os.path.join(args.out, "boring")
    os.makedirs(dest_dir, exist_ok=True)
    out_path = os.path.join(dest_dir, "scamlist.txt")
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("# boring scam blocklist, generated by get_scamlist.py\n")
        for host in sorted(hosts):
            f.write(host + "\n")
    print("wrote", out_path, "with", len(hosts), "hosts")


if __name__ == "__main__":
    main()
