#!/usr/bin/env python3
# Copyright 2026 boring. BSD style license.
"""Embed the page assistance scripts in a C++ header at build time.

Usage: embed_scripts.py <output.h> kName=<file.js> [kName=<file.js> ...]

Writes one `inline constexpr char kName[]` per pair, in the order given, in
namespace boring. Each holds the file's exact contents as a raw string
(R"BORINGJS(...)BORINGJS"). The scripts are page_context.js, protocol.js and
gemini_adapter.js: AssistanceSession installs them in the source page and in
the Gemini frame. Keeping the scripts as plain .js files lets node and
WebDriver test them as they ship.
"""

import re
import sys

DELIMITER = "BORINGJS"
NAME_PATTERN = re.compile(r"k[A-Z][A-Za-z0-9]*")

HEADER = """\
// Generated by components/boring/assistance/embed_scripts.py.
// Do not edit.

#ifndef COMPONENTS_BORING_ASSISTANCE_ASSISTANCE_SCRIPTS_H_
#define COMPONENTS_BORING_ASSISTANCE_ASSISTANCE_SCRIPTS_H_

namespace boring {{

{constants}

}}  // namespace boring

#endif  // COMPONENTS_BORING_ASSISTANCE_ASSISTANCE_SCRIPTS_H_
"""

CONSTANT = 'inline constexpr char {name}[] = R"{delimiter}({script}){delimiter}";'


def parse_pair(arg: str) -> tuple[str, str]:
    name, sep, path = arg.partition("=")
    if not sep:
        sys.exit(f"expected kName=<file.js>, got: {arg}")
    if not NAME_PATTERN.fullmatch(name):
        sys.exit(f"bad name {name!r}: must match ^k[A-Z][A-Za-z0-9]*$")
    return name, path


def read(path: str) -> str:
    try:
        with open(path, encoding="utf-8") as f:
            return f.read()
    except OSError as err:
        sys.exit(f"cannot read {path}: {err.strerror}")


def render(pairs: list[tuple[str, str]]) -> str:
    constants = "\n\n".join(
        CONSTANT.format(name=name, delimiter=DELIMITER, script=script)
        for name, script in pairs
    )
    return HEADER.format(constants=constants)


def main() -> None:
    args = sys.argv[1:]
    if len(args) < 2:
        sys.exit(__doc__)
    output, *specs = args
    pairs = []
    for spec in specs:
        name, path = parse_pair(spec)
        script = read(path)
        if ")" + DELIMITER in script:
            sys.exit(f"{path} contains the raw string delimiter {DELIMITER}")
        pairs.append((name, script))
    with open(output, "w", encoding="utf-8", newline="\n") as f:
        f.write(render(pairs))


if __name__ == "__main__":
    main()
