// Copyright 2012 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// Sync protocol datatype extension for apps.

// If you change or add any fields in this file, update proto_visitors.h and
// potentially proto_enum_conversions.{h, cc}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/app_specifics.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The possible launch types for an app.
// This enum should be kept in sync with extensions::LaunchType.
type AppSpecifics_LaunchType int32

const (
	AppSpecifics_PINNED     AppSpecifics_LaunchType = 0
	AppSpecifics_REGULAR    AppSpecifics_LaunchType = 1
	AppSpecifics_FULLSCREEN AppSpecifics_LaunchType = 2
	AppSpecifics_WINDOW     AppSpecifics_LaunchType = 3
)

// Enum value maps for AppSpecifics_LaunchType.
var (
	AppSpecifics_LaunchType_name = map[int32]string{
		0: "PINNED",
		1: "REGULAR",
		2: "FULLSCREEN",
		3: "WINDOW",
	}
	AppSpecifics_LaunchType_value = map[string]int32{
		"PINNED":     0,
		"REGULAR":    1,
		"FULLSCREEN": 2,
		"WINDOW":     3,
	}
)

func (x AppSpecifics_LaunchType) Enum() *AppSpecifics_LaunchType {
	p := new(AppSpecifics_LaunchType)
	*p = x
	return p
}

func (x AppSpecifics_LaunchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppSpecifics_LaunchType) Descriptor() protoreflect.EnumDescriptor {
	return file_components_sync_protocol_app_specifics_proto_enumTypes[0].Descriptor()
}

func (AppSpecifics_LaunchType) Type() protoreflect.EnumType {
	return &file_components_sync_protocol_app_specifics_proto_enumTypes[0]
}

func (x AppSpecifics_LaunchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AppSpecifics_LaunchType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AppSpecifics_LaunchType(num)
	return nil
}

// Deprecated: Use AppSpecifics_LaunchType.Descriptor instead.
func (AppSpecifics_LaunchType) EnumDescriptor() ([]byte, []int) {
	return file_components_sync_protocol_app_specifics_proto_rawDescGZIP(), []int{2, 0}
}

// Settings related to push notifications for apps.
type AppNotificationSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DEPRECATED: Use oauth_client_id below.
	// Whether or not the user has setup notifications at least once.
	// The value for this field will start out false and will be set
	// to true when the user accepts receiving notifications for the
	// first time and then it will always remain true.
	//
	// Deprecated: Marked as deprecated in components/sync/protocol/app_specifics.proto.
	InitialSetupDone *bool `protobuf:"varint,1,opt,name=initial_setup_done,json=initialSetupDone" json:"initial_setup_done,omitempty"`
	// Whether or not the user has disabled notifications.
	Disabled *bool `protobuf:"varint,2,opt,name=disabled" json:"disabled,omitempty"`
	// OAuth2 client id to which the user granted the notification permission.
	// This field will start out empty.
	// It will be set when the user accepts receiving notifications.
	// This field is used when the user revokes the notifications permission.
	// Note that it is never cleared after it was set once. Hence, the presence
	// of this field can be used to determine if the user has setup notifications
	// at least once for the given app.
	OauthClientId *string `protobuf:"bytes,3,opt,name=oauth_client_id,json=oauthClientId" json:"oauth_client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppNotificationSettings) Reset() {
	*x = AppNotificationSettings{}
	mi := &file_components_sync_protocol_app_specifics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppNotificationSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppNotificationSettings) ProtoMessage() {}

func (x *AppNotificationSettings) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_app_specifics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppNotificationSettings.ProtoReflect.Descriptor instead.
func (*AppNotificationSettings) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_app_specifics_proto_rawDescGZIP(), []int{0}
}

// Deprecated: Marked as deprecated in components/sync/protocol/app_specifics.proto.
func (x *AppNotificationSettings) GetInitialSetupDone() bool {
	if x != nil && x.InitialSetupDone != nil {
		return *x.InitialSetupDone
	}
	return false
}

func (x *AppNotificationSettings) GetDisabled() bool {
	if x != nil && x.Disabled != nil {
		return *x.Disabled
	}
	return false
}

func (x *AppNotificationSettings) GetOauthClientId() string {
	if x != nil && x.OauthClientId != nil {
		return *x.OauthClientId
	}
	return ""
}

// Information about a linked app icon.
type LinkedAppIconInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URL of the app icon.
	Url *string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	// The size of the app icon in DIPs.
	Size          *uint32 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkedAppIconInfo) Reset() {
	*x = LinkedAppIconInfo{}
	mi := &file_components_sync_protocol_app_specifics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkedAppIconInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedAppIconInfo) ProtoMessage() {}

func (x *LinkedAppIconInfo) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_app_specifics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedAppIconInfo.ProtoReflect.Descriptor instead.
func (*LinkedAppIconInfo) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_app_specifics_proto_rawDescGZIP(), []int{1}
}

func (x *LinkedAppIconInfo) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *LinkedAppIconInfo) GetSize() uint32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

// Properties of app sync objects.
//
// For now, an app is just an extension.  We keep the two data types
// separate for future-proofing purposes.
type AppSpecifics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Extension data.
	Extension *ExtensionSpecifics `protobuf:"bytes,1,opt,name=extension" json:"extension,omitempty"`
	// Notification settings.
	NotificationSettings *AppNotificationSettings `protobuf:"bytes,2,opt,name=notification_settings,json=notificationSettings" json:"notification_settings,omitempty"`
	// This controls where on a page this application icon will appear.
	AppLaunchOrdinal *string `protobuf:"bytes,3,opt,name=app_launch_ordinal,json=appLaunchOrdinal" json:"app_launch_ordinal,omitempty"`
	// This specifics which page the application icon will appear on in the NTP.
	// This values only provide the order within the application pages, not within
	// all of the panels in the NTP.
	PageOrdinal *string `protobuf:"bytes,4,opt,name=page_ordinal,json=pageOrdinal" json:"page_ordinal,omitempty"`
	// This describes how the extension should be launched.
	LaunchType *AppSpecifics_LaunchType `protobuf:"varint,5,opt,name=launch_type,json=launchType,enum=sync_pb.AppSpecifics_LaunchType" json:"launch_type,omitempty"`
	// DEPRECATED. See https://crbug.com/1233303.
	//
	// Deprecated: Marked as deprecated in components/sync/protocol/app_specifics.proto.
	BookmarkAppUrl *string `protobuf:"bytes,6,opt,name=bookmark_app_url,json=bookmarkAppUrl" json:"bookmark_app_url,omitempty"`
	// DEPRECATED. See https://crbug.com/1233303.
	//
	// Deprecated: Marked as deprecated in components/sync/protocol/app_specifics.proto.
	BookmarkAppDescription *string `protobuf:"bytes,7,opt,name=bookmark_app_description,json=bookmarkAppDescription" json:"bookmark_app_description,omitempty"`
	// DEPRECATED. See https://crbug.com/1233303.
	//
	// Deprecated: Marked as deprecated in components/sync/protocol/app_specifics.proto.
	BookmarkAppIconColor *string `protobuf:"bytes,8,opt,name=bookmark_app_icon_color,json=bookmarkAppIconColor" json:"bookmark_app_icon_color,omitempty"`
	// This is information about linked icons (that is, icons that are downloaded
	// from outside the app's bundle of files.
	LinkedAppIcons []*LinkedAppIconInfo `protobuf:"bytes,9,rep,name=linked_app_icons,json=linkedAppIcons" json:"linked_app_icons,omitempty"`
	// DEPRECATED. See https://crbug.com/1233303.
	//
	// Deprecated: Marked as deprecated in components/sync/protocol/app_specifics.proto.
	BookmarkAppScope *string `protobuf:"bytes,10,opt,name=bookmark_app_scope,json=bookmarkAppScope" json:"bookmark_app_scope,omitempty"`
	// DEPRECATED. See https://crbug.com/1233303.
	//
	// Deprecated: Marked as deprecated in components/sync/protocol/app_specifics.proto.
	BookmarkAppThemeColor *uint32 `protobuf:"varint,11,opt,name=bookmark_app_theme_color,json=bookmarkAppThemeColor" json:"bookmark_app_theme_color,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AppSpecifics) Reset() {
	*x = AppSpecifics{}
	mi := &file_components_sync_protocol_app_specifics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSpecifics) ProtoMessage() {}

func (x *AppSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_app_specifics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSpecifics.ProtoReflect.Descriptor instead.
func (*AppSpecifics) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_app_specifics_proto_rawDescGZIP(), []int{2}
}

func (x *AppSpecifics) GetExtension() *ExtensionSpecifics {
	if x != nil {
		return x.Extension
	}
	return nil
}

func (x *AppSpecifics) GetNotificationSettings() *AppNotificationSettings {
	if x != nil {
		return x.NotificationSettings
	}
	return nil
}

func (x *AppSpecifics) GetAppLaunchOrdinal() string {
	if x != nil && x.AppLaunchOrdinal != nil {
		return *x.AppLaunchOrdinal
	}
	return ""
}

func (x *AppSpecifics) GetPageOrdinal() string {
	if x != nil && x.PageOrdinal != nil {
		return *x.PageOrdinal
	}
	return ""
}

func (x *AppSpecifics) GetLaunchType() AppSpecifics_LaunchType {
	if x != nil && x.LaunchType != nil {
		return *x.LaunchType
	}
	return AppSpecifics_PINNED
}

// Deprecated: Marked as deprecated in components/sync/protocol/app_specifics.proto.
func (x *AppSpecifics) GetBookmarkAppUrl() string {
	if x != nil && x.BookmarkAppUrl != nil {
		return *x.BookmarkAppUrl
	}
	return ""
}

// Deprecated: Marked as deprecated in components/sync/protocol/app_specifics.proto.
func (x *AppSpecifics) GetBookmarkAppDescription() string {
	if x != nil && x.BookmarkAppDescription != nil {
		return *x.BookmarkAppDescription
	}
	return ""
}

// Deprecated: Marked as deprecated in components/sync/protocol/app_specifics.proto.
func (x *AppSpecifics) GetBookmarkAppIconColor() string {
	if x != nil && x.BookmarkAppIconColor != nil {
		return *x.BookmarkAppIconColor
	}
	return ""
}

func (x *AppSpecifics) GetLinkedAppIcons() []*LinkedAppIconInfo {
	if x != nil {
		return x.LinkedAppIcons
	}
	return nil
}

// Deprecated: Marked as deprecated in components/sync/protocol/app_specifics.proto.
func (x *AppSpecifics) GetBookmarkAppScope() string {
	if x != nil && x.BookmarkAppScope != nil {
		return *x.BookmarkAppScope
	}
	return ""
}

// Deprecated: Marked as deprecated in components/sync/protocol/app_specifics.proto.
func (x *AppSpecifics) GetBookmarkAppThemeColor() uint32 {
	if x != nil && x.BookmarkAppThemeColor != nil {
		return *x.BookmarkAppThemeColor
	}
	return 0
}

var File_components_sync_protocol_app_specifics_proto protoreflect.FileDescriptor

const file_components_sync_protocol_app_specifics_proto_rawDesc = "" +
	"\n" +
	",components/sync/protocol/app_specifics.proto\x12\async_pb\x1a2components/sync/protocol/extension_specifics.proto\"\x8f\x01\n" +
	"\x17AppNotificationSettings\x120\n" +
	"\x12initial_setup_done\x18\x01 \x01(\bB\x02\x18\x01R\x10initialSetupDone\x12\x1a\n" +
	"\bdisabled\x18\x02 \x01(\bR\bdisabled\x12&\n" +
	"\x0foauth_client_id\x18\x03 \x01(\tR\roauthClientId\"9\n" +
	"\x11LinkedAppIconInfo\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\"\xd3\x05\n" +
	"\fAppSpecifics\x129\n" +
	"\textension\x18\x01 \x01(\v2\x1b.sync_pb.ExtensionSpecificsR\textension\x12U\n" +
	"\x15notification_settings\x18\x02 \x01(\v2 .sync_pb.AppNotificationSettingsR\x14notificationSettings\x12,\n" +
	"\x12app_launch_ordinal\x18\x03 \x01(\tR\x10appLaunchOrdinal\x12!\n" +
	"\fpage_ordinal\x18\x04 \x01(\tR\vpageOrdinal\x12A\n" +
	"\vlaunch_type\x18\x05 \x01(\x0e2 .sync_pb.AppSpecifics.LaunchTypeR\n" +
	"launchType\x12,\n" +
	"\x10bookmark_app_url\x18\x06 \x01(\tB\x02\x18\x01R\x0ebookmarkAppUrl\x12<\n" +
	"\x18bookmark_app_description\x18\a \x01(\tB\x02\x18\x01R\x16bookmarkAppDescription\x129\n" +
	"\x17bookmark_app_icon_color\x18\b \x01(\tB\x02\x18\x01R\x14bookmarkAppIconColor\x12D\n" +
	"\x10linked_app_icons\x18\t \x03(\v2\x1a.sync_pb.LinkedAppIconInfoR\x0elinkedAppIcons\x120\n" +
	"\x12bookmark_app_scope\x18\n" +
	" \x01(\tB\x02\x18\x01R\x10bookmarkAppScope\x12;\n" +
	"\x18bookmark_app_theme_color\x18\v \x01(\rB\x02\x18\x01R\x15bookmarkAppThemeColor\"A\n" +
	"\n" +
	"LaunchType\x12\n" +
	"\n" +
	"\x06PINNED\x10\x00\x12\v\n" +
	"\aREGULAR\x10\x01\x12\x0e\n" +
	"\n" +
	"FULLSCREEN\x10\x02\x12\n" +
	"\n" +
	"\x06WINDOW\x10\x03B+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_app_specifics_proto_rawDescOnce sync.Once
	file_components_sync_protocol_app_specifics_proto_rawDescData []byte
)

func file_components_sync_protocol_app_specifics_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_app_specifics_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_app_specifics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_app_specifics_proto_rawDesc), len(file_components_sync_protocol_app_specifics_proto_rawDesc)))
	})
	return file_components_sync_protocol_app_specifics_proto_rawDescData
}

var file_components_sync_protocol_app_specifics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_components_sync_protocol_app_specifics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_components_sync_protocol_app_specifics_proto_goTypes = []any{
	(AppSpecifics_LaunchType)(0),    // 0: sync_pb.AppSpecifics.LaunchType
	(*AppNotificationSettings)(nil), // 1: sync_pb.AppNotificationSettings
	(*LinkedAppIconInfo)(nil),       // 2: sync_pb.LinkedAppIconInfo
	(*AppSpecifics)(nil),            // 3: sync_pb.AppSpecifics
	(*ExtensionSpecifics)(nil),      // 4: sync_pb.ExtensionSpecifics
}
var file_components_sync_protocol_app_specifics_proto_depIdxs = []int32{
	4, // 0: sync_pb.AppSpecifics.extension:type_name -> sync_pb.ExtensionSpecifics
	1, // 1: sync_pb.AppSpecifics.notification_settings:type_name -> sync_pb.AppNotificationSettings
	0, // 2: sync_pb.AppSpecifics.launch_type:type_name -> sync_pb.AppSpecifics.LaunchType
	2, // 3: sync_pb.AppSpecifics.linked_app_icons:type_name -> sync_pb.LinkedAppIconInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_app_specifics_proto_init() }
func file_components_sync_protocol_app_specifics_proto_init() {
	if File_components_sync_protocol_app_specifics_proto != nil {
		return
	}
	file_components_sync_protocol_extension_specifics_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_app_specifics_proto_rawDesc), len(file_components_sync_protocol_app_specifics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_app_specifics_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_app_specifics_proto_depIdxs,
		EnumInfos:         file_components_sync_protocol_app_specifics_proto_enumTypes,
		MessageInfos:      file_components_sync_protocol_app_specifics_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_app_specifics_proto = out.File
	file_components_sync_protocol_app_specifics_proto_goTypes = nil
	file_components_sync_protocol_app_specifics_proto_depIdxs = nil
}
