// Copyright 2013 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// Sync protocol datatype extension for the app list (aka app launcher).

// If you change or add any fields in this file, update proto_visitors.h and
// potentially proto_enum_conversions.{h, cc}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/app_list_specifics.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// What type of item this is.
type AppListSpecifics_AppListItemType int32

const (
	// An app, whether a web app, Android app, etc.
	//
	// For bookmark apps (URL shortcuts), additional information such as their
	// URLs are kept in the AppSpecifics.bookmark_app_foobar fields.
	AppListSpecifics_TYPE_APP AppListSpecifics_AppListItemType = 1
	// A request to remove any matching default installed apps.
	AppListSpecifics_TYPE_REMOVE_DEFAULT_APP AppListSpecifics_AppListItemType = 2
	// A folder containing entries whose `parent_id` matches `item_id`.
	AppListSpecifics_TYPE_FOLDER AppListSpecifics_AppListItemType = 3
	// Obsolete type, intended for URL shortcuts, that was never implemented.
	AppListSpecifics_TYPE_OBSOLETE_URL AppListSpecifics_AppListItemType = 4
	// A "page break" item (Indicate creation of a new page in app list).
	AppListSpecifics_TYPE_PAGE_BREAK AppListSpecifics_AppListItemType = 5
)

// Enum value maps for AppListSpecifics_AppListItemType.
var (
	AppListSpecifics_AppListItemType_name = map[int32]string{
		1: "TYPE_APP",
		2: "TYPE_REMOVE_DEFAULT_APP",
		3: "TYPE_FOLDER",
		4: "TYPE_OBSOLETE_URL",
		5: "TYPE_PAGE_BREAK",
	}
	AppListSpecifics_AppListItemType_value = map[string]int32{
		"TYPE_APP":                1,
		"TYPE_REMOVE_DEFAULT_APP": 2,
		"TYPE_FOLDER":             3,
		"TYPE_OBSOLETE_URL":       4,
		"TYPE_PAGE_BREAK":         5,
	}
)

func (x AppListSpecifics_AppListItemType) Enum() *AppListSpecifics_AppListItemType {
	p := new(AppListSpecifics_AppListItemType)
	*p = x
	return p
}

func (x AppListSpecifics_AppListItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppListSpecifics_AppListItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_components_sync_protocol_app_list_specifics_proto_enumTypes[0].Descriptor()
}

func (AppListSpecifics_AppListItemType) Type() protoreflect.EnumType {
	return &file_components_sync_protocol_app_list_specifics_proto_enumTypes[0]
}

func (x AppListSpecifics_AppListItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AppListSpecifics_AppListItemType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AppListSpecifics_AppListItemType(num)
	return nil
}

// Deprecated: Use AppListSpecifics_AppListItemType.Descriptor instead.
func (AppListSpecifics_AppListItemType) EnumDescriptor() ([]byte, []int) {
	return file_components_sync_protocol_app_list_specifics_proto_rawDescGZIP(), []int{0, 0}
}

// The color groups used for grouping together icons by colors.
type AppListSpecifics_ColorGroup int32

const (
	AppListSpecifics_COLOR_EMPTY   AppListSpecifics_ColorGroup = 0
	AppListSpecifics_COLOR_WHITE   AppListSpecifics_ColorGroup = 1
	AppListSpecifics_COLOR_RED     AppListSpecifics_ColorGroup = 2
	AppListSpecifics_COLOR_ORANGE  AppListSpecifics_ColorGroup = 3
	AppListSpecifics_COLOR_YELLOW  AppListSpecifics_ColorGroup = 4
	AppListSpecifics_COLOR_GREEN   AppListSpecifics_ColorGroup = 5
	AppListSpecifics_COLOR_BLUE    AppListSpecifics_ColorGroup = 6
	AppListSpecifics_COLOR_MAGENTA AppListSpecifics_ColorGroup = 7
	AppListSpecifics_COLOR_BLACK   AppListSpecifics_ColorGroup = 8
)

// Enum value maps for AppListSpecifics_ColorGroup.
var (
	AppListSpecifics_ColorGroup_name = map[int32]string{
		0: "COLOR_EMPTY",
		1: "COLOR_WHITE",
		2: "COLOR_RED",
		3: "COLOR_ORANGE",
		4: "COLOR_YELLOW",
		5: "COLOR_GREEN",
		6: "COLOR_BLUE",
		7: "COLOR_MAGENTA",
		8: "COLOR_BLACK",
	}
	AppListSpecifics_ColorGroup_value = map[string]int32{
		"COLOR_EMPTY":   0,
		"COLOR_WHITE":   1,
		"COLOR_RED":     2,
		"COLOR_ORANGE":  3,
		"COLOR_YELLOW":  4,
		"COLOR_GREEN":   5,
		"COLOR_BLUE":    6,
		"COLOR_MAGENTA": 7,
		"COLOR_BLACK":   8,
	}
)

func (x AppListSpecifics_ColorGroup) Enum() *AppListSpecifics_ColorGroup {
	p := new(AppListSpecifics_ColorGroup)
	*p = x
	return p
}

func (x AppListSpecifics_ColorGroup) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppListSpecifics_ColorGroup) Descriptor() protoreflect.EnumDescriptor {
	return file_components_sync_protocol_app_list_specifics_proto_enumTypes[1].Descriptor()
}

func (AppListSpecifics_ColorGroup) Type() protoreflect.EnumType {
	return &file_components_sync_protocol_app_list_specifics_proto_enumTypes[1]
}

func (x AppListSpecifics_ColorGroup) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AppListSpecifics_ColorGroup) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AppListSpecifics_ColorGroup(num)
	return nil
}

// Deprecated: Use AppListSpecifics_ColorGroup.Descriptor instead.
func (AppListSpecifics_ColorGroup) EnumDescriptor() ([]byte, []int) {
	return file_components_sync_protocol_app_list_specifics_proto_rawDescGZIP(), []int{0, 1}
}

// Properties of app list objects.
type AppListSpecifics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the item:
	// * TYPE_FOLDER: Folder id (generated)
	// * TYPE_APP: App Id
	ItemId   *string                           `protobuf:"bytes,1,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	ItemType *AppListSpecifics_AppListItemType `protobuf:"varint,2,opt,name=item_type,json=itemType,enum=sync_pb.AppListSpecifics_AppListItemType" json:"item_type,omitempty"`
	// Item name (FOLDER).
	ItemName *string `protobuf:"bytes,3,opt,name=item_name,json=itemName" json:"item_name,omitempty"`
	// Id of the parent (folder) item.
	ParentId *string `protobuf:"bytes,4,opt,name=parent_id,json=parentId" json:"parent_id,omitempty"`
	// Marked OBSOLETE because this is unused for the app list.
	// Which page this item will appear on in the app list.
	//
	// Deprecated: Marked as deprecated in components/sync/protocol/app_list_specifics.proto.
	OBSOLETEPageOrdinal *string `protobuf:"bytes,5,opt,name=OBSOLETE_page_ordinal,json=OBSOLETEPageOrdinal" json:"OBSOLETE_page_ordinal,omitempty"`
	// Where on a page this item will appear.
	ItemOrdinal *string `protobuf:"bytes,6,opt,name=item_ordinal,json=itemOrdinal" json:"item_ordinal,omitempty"`
	// Where on a shelf this item will appear.
	ItemPinOrdinal *string                     `protobuf:"bytes,7,opt,name=item_pin_ordinal,json=itemPinOrdinal" json:"item_pin_ordinal,omitempty"`
	ItemColor      *AppListSpecifics_IconColor `protobuf:"bytes,8,opt,name=item_color,json=itemColor" json:"item_color,omitempty"`
	// Identifier for the app package of the item. Package Ids are stable and
	// globally unique across app platforms, whereas App Id stored in item_id is
	// not.
	PromisePackageId *string `protobuf:"bytes,10,opt,name=promise_package_id,json=promisePackageId" json:"promise_package_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AppListSpecifics) Reset() {
	*x = AppListSpecifics{}
	mi := &file_components_sync_protocol_app_list_specifics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppListSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppListSpecifics) ProtoMessage() {}

func (x *AppListSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_app_list_specifics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppListSpecifics.ProtoReflect.Descriptor instead.
func (*AppListSpecifics) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_app_list_specifics_proto_rawDescGZIP(), []int{0}
}

func (x *AppListSpecifics) GetItemId() string {
	if x != nil && x.ItemId != nil {
		return *x.ItemId
	}
	return ""
}

func (x *AppListSpecifics) GetItemType() AppListSpecifics_AppListItemType {
	if x != nil && x.ItemType != nil {
		return *x.ItemType
	}
	return AppListSpecifics_TYPE_APP
}

func (x *AppListSpecifics) GetItemName() string {
	if x != nil && x.ItemName != nil {
		return *x.ItemName
	}
	return ""
}

func (x *AppListSpecifics) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

// Deprecated: Marked as deprecated in components/sync/protocol/app_list_specifics.proto.
func (x *AppListSpecifics) GetOBSOLETEPageOrdinal() string {
	if x != nil && x.OBSOLETEPageOrdinal != nil {
		return *x.OBSOLETEPageOrdinal
	}
	return ""
}

func (x *AppListSpecifics) GetItemOrdinal() string {
	if x != nil && x.ItemOrdinal != nil {
		return *x.ItemOrdinal
	}
	return ""
}

func (x *AppListSpecifics) GetItemPinOrdinal() string {
	if x != nil && x.ItemPinOrdinal != nil {
		return *x.ItemPinOrdinal
	}
	return ""
}

func (x *AppListSpecifics) GetItemColor() *AppListSpecifics_IconColor {
	if x != nil {
		return x.ItemColor
	}
	return nil
}

func (x *AppListSpecifics) GetPromisePackageId() string {
	if x != nil && x.PromisePackageId != nil {
		return *x.PromisePackageId
	}
	return ""
}

type AppListSpecifics_IconColor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The item icon's background color.
	BackgroundColor *AppListSpecifics_ColorGroup `protobuf:"varint,1,opt,name=background_color,json=backgroundColor,enum=sync_pb.AppListSpecifics_ColorGroup" json:"background_color,omitempty"`
	// The item icon's hue.
	Hue           *int32 `protobuf:"varint,2,opt,name=hue" json:"hue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppListSpecifics_IconColor) Reset() {
	*x = AppListSpecifics_IconColor{}
	mi := &file_components_sync_protocol_app_list_specifics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppListSpecifics_IconColor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppListSpecifics_IconColor) ProtoMessage() {}

func (x *AppListSpecifics_IconColor) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_app_list_specifics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppListSpecifics_IconColor.ProtoReflect.Descriptor instead.
func (*AppListSpecifics_IconColor) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_app_list_specifics_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AppListSpecifics_IconColor) GetBackgroundColor() AppListSpecifics_ColorGroup {
	if x != nil && x.BackgroundColor != nil {
		return *x.BackgroundColor
	}
	return AppListSpecifics_COLOR_EMPTY
}

func (x *AppListSpecifics_IconColor) GetHue() int32 {
	if x != nil && x.Hue != nil {
		return *x.Hue
	}
	return 0
}

var File_components_sync_protocol_app_list_specifics_proto protoreflect.FileDescriptor

const file_components_sync_protocol_app_list_specifics_proto_rawDesc = "" +
	"\n" +
	"1components/sync/protocol/app_list_specifics.proto\x12\async_pb\"\xbe\x06\n" +
	"\x10AppListSpecifics\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12F\n" +
	"\titem_type\x18\x02 \x01(\x0e2).sync_pb.AppListSpecifics.AppListItemTypeR\bitemType\x12\x1b\n" +
	"\titem_name\x18\x03 \x01(\tR\bitemName\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x126\n" +
	"\x15OBSOLETE_page_ordinal\x18\x05 \x01(\tB\x02\x18\x01R\x13OBSOLETEPageOrdinal\x12!\n" +
	"\fitem_ordinal\x18\x06 \x01(\tR\vitemOrdinal\x12(\n" +
	"\x10item_pin_ordinal\x18\a \x01(\tR\x0eitemPinOrdinal\x12B\n" +
	"\n" +
	"item_color\x18\b \x01(\v2#.sync_pb.AppListSpecifics.IconColorR\titemColor\x12,\n" +
	"\x12promise_package_id\x18\n" +
	" \x01(\tR\x10promisePackageId\x1an\n" +
	"\tIconColor\x12O\n" +
	"\x10background_color\x18\x01 \x01(\x0e2$.sync_pb.AppListSpecifics.ColorGroupR\x0fbackgroundColor\x12\x10\n" +
	"\x03hue\x18\x02 \x01(\x05R\x03hue\"y\n" +
	"\x0fAppListItemType\x12\f\n" +
	"\bTYPE_APP\x10\x01\x12\x1b\n" +
	"\x17TYPE_REMOVE_DEFAULT_APP\x10\x02\x12\x0f\n" +
	"\vTYPE_FOLDER\x10\x03\x12\x15\n" +
	"\x11TYPE_OBSOLETE_URL\x10\x04\x12\x13\n" +
	"\x0fTYPE_PAGE_BREAK\x10\x05\"\xa6\x01\n" +
	"\n" +
	"ColorGroup\x12\x0f\n" +
	"\vCOLOR_EMPTY\x10\x00\x12\x0f\n" +
	"\vCOLOR_WHITE\x10\x01\x12\r\n" +
	"\tCOLOR_RED\x10\x02\x12\x10\n" +
	"\fCOLOR_ORANGE\x10\x03\x12\x10\n" +
	"\fCOLOR_YELLOW\x10\x04\x12\x0f\n" +
	"\vCOLOR_GREEN\x10\x05\x12\x0e\n" +
	"\n" +
	"COLOR_BLUE\x10\x06\x12\x11\n" +
	"\rCOLOR_MAGENTA\x10\a\x12\x0f\n" +
	"\vCOLOR_BLACK\x10\bJ\x04\b\t\x10\n" +
	"B+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_app_list_specifics_proto_rawDescOnce sync.Once
	file_components_sync_protocol_app_list_specifics_proto_rawDescData []byte
)

func file_components_sync_protocol_app_list_specifics_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_app_list_specifics_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_app_list_specifics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_app_list_specifics_proto_rawDesc), len(file_components_sync_protocol_app_list_specifics_proto_rawDesc)))
	})
	return file_components_sync_protocol_app_list_specifics_proto_rawDescData
}

var file_components_sync_protocol_app_list_specifics_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_components_sync_protocol_app_list_specifics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_components_sync_protocol_app_list_specifics_proto_goTypes = []any{
	(AppListSpecifics_AppListItemType)(0), // 0: sync_pb.AppListSpecifics.AppListItemType
	(AppListSpecifics_ColorGroup)(0),      // 1: sync_pb.AppListSpecifics.ColorGroup
	(*AppListSpecifics)(nil),              // 2: sync_pb.AppListSpecifics
	(*AppListSpecifics_IconColor)(nil),    // 3: sync_pb.AppListSpecifics.IconColor
}
var file_components_sync_protocol_app_list_specifics_proto_depIdxs = []int32{
	0, // 0: sync_pb.AppListSpecifics.item_type:type_name -> sync_pb.AppListSpecifics.AppListItemType
	3, // 1: sync_pb.AppListSpecifics.item_color:type_name -> sync_pb.AppListSpecifics.IconColor
	1, // 2: sync_pb.AppListSpecifics.IconColor.background_color:type_name -> sync_pb.AppListSpecifics.ColorGroup
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_app_list_specifics_proto_init() }
func file_components_sync_protocol_app_list_specifics_proto_init() {
	if File_components_sync_protocol_app_list_specifics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_app_list_specifics_proto_rawDesc), len(file_components_sync_protocol_app_list_specifics_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_app_list_specifics_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_app_list_specifics_proto_depIdxs,
		EnumInfos:         file_components_sync_protocol_app_list_specifics_proto_enumTypes,
		MessageInfos:      file_components_sync_protocol_app_list_specifics_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_app_list_specifics_proto = out.File
	file_components_sync_protocol_app_list_specifics_proto_goTypes = nil
	file_components_sync_protocol_app_list_specifics_proto_depIdxs = nil
}
