// Copyright 2018 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/bookmark_model_metadata.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Corresponds to a single bookmark id/metadata pair.
type BookmarkMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bookmark local id.
	Id *int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Bookmarks sync metadata.
	Metadata      *EntityMetadata `protobuf:"bytes,2,opt,name=metadata" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookmarkMetadata) Reset() {
	*x = BookmarkMetadata{}
	mi := &file_components_sync_protocol_bookmark_model_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookmarkMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookmarkMetadata) ProtoMessage() {}

func (x *BookmarkMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_bookmark_model_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookmarkMetadata.ProtoReflect.Descriptor instead.
func (*BookmarkMetadata) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_bookmark_model_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *BookmarkMetadata) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *BookmarkMetadata) GetMetadata() *EntityMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Sync proto to carry the sync metadata for the bookmarks model. It is used for
// persisting and loading sync metadata from disk.
type BookmarkModelMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bookmark global metadata.
	DataTypeState *DataTypeState `protobuf:"bytes,1,opt,name=data_type_state,json=dataTypeState" json:"data_type_state,omitempty"`
	// A set of all bookmarks metadata.
	BookmarksMetadata []*BookmarkMetadata `protobuf:"bytes,2,rep,name=bookmarks_metadata,json=bookmarksMetadata" json:"bookmarks_metadata,omitempty"`
	// Indicates whether the reupload of bookmarks has been triggered such that
	// they include fields like `type`, `unique_position` and `parent_guid`, which
	// means that their sequence number has been increased (independently of
	// whether the commit has succeeded or even started).
	// TODO(crbug.com/40780588): remove this code when most of bookmarks are
	// reuploaded.
	BookmarksHierarchyFieldsReuploaded *bool `protobuf:"varint,6,opt,name=bookmarks_hierarchy_fields_reuploaded,json=bookmarksHierarchyFieldsReuploaded" json:"bookmarks_hierarchy_fields_reuploaded,omitempty"`
	// Number of remote updates that were ignored because the parent folder could
	// not be determined since sync (bookmark sync) started (since initial sync,
	// including initial sync itself). Note that this excludes updates
	// representing changes (moves) to existing/tracked bookmarks (i.e. the parent
	// folder used to be known, but the new one specified in the update isn't).
	//
	// Only a minority of users should have a non-zero value, due to a) corrupt
	// data, reasons unknown; or b) permanent folders that were unsupported at the
	// time the update was received (either for the permanent folder itself or for
	// descendants). The absence of this field should be interpreted as 'unknown',
	// which roughly means the counter wasn't supported by the browser -M77 or
	// below- at the time sync was enabled (it also means, it will remain
	// 'unknown' until initial sync is exercised, e.g. sync disabled and
	// reenabled).
	NumIgnoredUpdatesDueToMissingParent *int64 `protobuf:"varint,7,opt,name=num_ignored_updates_due_to_missing_parent,json=numIgnoredUpdatesDueToMissingParent" json:"num_ignored_updates_due_to_missing_parent,omitempty"`
	// See field above. Among such ignored updates, this field tracks which was
	// the highest server version. This may be useful -in the future- to get a
	// sense of "time" (or, since versions are opaque to the client, at least a
	// notion of ordering with respect to other updates). The absence of this
	// field should be interpreted as 'unknown' and does not distinguish the
	// case between a) no updates ignored; and b) field wasn't supported at the
	// time the last update was ignored. To distinguish between these two, the
	// field above can be used.
	MaxVersionAmongIgnoredUpdatesDueToMissingParent *int64 `protobuf:"varint,8,opt,name=max_version_among_ignored_updates_due_to_missing_parent,json=maxVersionAmongIgnoredUpdatesDueToMissingParent" json:"max_version_among_ignored_updates_due_to_missing_parent,omitempty"`
	// Indicates whether the count of remote updates during the latest initial
	// merge exceeded the bookmark limit. This field is mutually exclusive to all
	// the other fields and is managed completely by the processor.
	// TODO(454302754): Remove this field once
	// `last_initial_merge_remote_updates_exceeded_limit_timestamp_windows_epoch_micros`
	// is stable.
	LastInitialMergeRemoteUpdatesExceededLimit *bool `protobuf:"varint,9,opt,name=last_initial_merge_remote_updates_exceeded_limit,json=lastInitialMergeRemoteUpdatesExceededLimit" json:"last_initial_merge_remote_updates_exceeded_limit,omitempty"`
	// The timestamp (in microseconds) when the above limit was exceeded.
	InitialMergeRemoteUpdatesExceededLimitTimestampWindowsEpochMicros *int64 `protobuf:"varint,10,opt,name=initial_merge_remote_updates_exceeded_limit_timestamp_windows_epoch_micros,json=initialMergeRemoteUpdatesExceededLimitTimestampWindowsEpochMicros" json:"initial_merge_remote_updates_exceeded_limit_timestamp_windows_epoch_micros,omitempty"`
	unknownFields                                                     protoimpl.UnknownFields
	sizeCache                                                         protoimpl.SizeCache
}

func (x *BookmarkModelMetadata) Reset() {
	*x = BookmarkModelMetadata{}
	mi := &file_components_sync_protocol_bookmark_model_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookmarkModelMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookmarkModelMetadata) ProtoMessage() {}

func (x *BookmarkModelMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_bookmark_model_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookmarkModelMetadata.ProtoReflect.Descriptor instead.
func (*BookmarkModelMetadata) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_bookmark_model_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *BookmarkModelMetadata) GetDataTypeState() *DataTypeState {
	if x != nil {
		return x.DataTypeState
	}
	return nil
}

func (x *BookmarkModelMetadata) GetBookmarksMetadata() []*BookmarkMetadata {
	if x != nil {
		return x.BookmarksMetadata
	}
	return nil
}

func (x *BookmarkModelMetadata) GetBookmarksHierarchyFieldsReuploaded() bool {
	if x != nil && x.BookmarksHierarchyFieldsReuploaded != nil {
		return *x.BookmarksHierarchyFieldsReuploaded
	}
	return false
}

func (x *BookmarkModelMetadata) GetNumIgnoredUpdatesDueToMissingParent() int64 {
	if x != nil && x.NumIgnoredUpdatesDueToMissingParent != nil {
		return *x.NumIgnoredUpdatesDueToMissingParent
	}
	return 0
}

func (x *BookmarkModelMetadata) GetMaxVersionAmongIgnoredUpdatesDueToMissingParent() int64 {
	if x != nil && x.MaxVersionAmongIgnoredUpdatesDueToMissingParent != nil {
		return *x.MaxVersionAmongIgnoredUpdatesDueToMissingParent
	}
	return 0
}

func (x *BookmarkModelMetadata) GetLastInitialMergeRemoteUpdatesExceededLimit() bool {
	if x != nil && x.LastInitialMergeRemoteUpdatesExceededLimit != nil {
		return *x.LastInitialMergeRemoteUpdatesExceededLimit
	}
	return false
}

func (x *BookmarkModelMetadata) GetInitialMergeRemoteUpdatesExceededLimitTimestampWindowsEpochMicros() int64 {
	if x != nil && x.InitialMergeRemoteUpdatesExceededLimitTimestampWindowsEpochMicros != nil {
		return *x.InitialMergeRemoteUpdatesExceededLimitTimestampWindowsEpochMicros
	}
	return 0
}

var File_components_sync_protocol_bookmark_model_metadata_proto protoreflect.FileDescriptor

const file_components_sync_protocol_bookmark_model_metadata_proto_rawDesc = "" +
	"\n" +
	"6components/sync/protocol/bookmark_model_metadata.proto\x12\async_pb\x1a.components/sync/protocol/data_type_state.proto\x1a.components/sync/protocol/entity_metadata.proto\"W\n" +
	"\x10BookmarkMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.sync_pb.EntityMetadataR\bmetadata\"\xce\x05\n" +
	"\x15BookmarkModelMetadata\x12>\n" +
	"\x0fdata_type_state\x18\x01 \x01(\v2\x16.sync_pb.DataTypeStateR\rdataTypeState\x12H\n" +
	"\x12bookmarks_metadata\x18\x02 \x03(\v2\x19.sync_pb.BookmarkMetadataR\x11bookmarksMetadata\x12Q\n" +
	"%bookmarks_hierarchy_fields_reuploaded\x18\x06 \x01(\bR\"bookmarksHierarchyFieldsReuploaded\x12V\n" +
	")num_ignored_updates_due_to_missing_parent\x18\a \x01(\x03R#numIgnoredUpdatesDueToMissingParent\x12p\n" +
	"7max_version_among_ignored_updates_due_to_missing_parent\x18\b \x01(\x03R/maxVersionAmongIgnoredUpdatesDueToMissingParent\x12d\n" +
	"0last_initial_merge_remote_updates_exceeded_limit\x18\t \x01(\bR*lastInitialMergeRemoteUpdatesExceededLimit\x12\x95\x01\n" +
	"Jinitial_merge_remote_updates_exceeded_limit_timestamp_windows_epoch_micros\x18\n" +
	" \x01(\x03RAinitialMergeRemoteUpdatesExceededLimitTimestampWindowsEpochMicrosJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06B+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_bookmark_model_metadata_proto_rawDescOnce sync.Once
	file_components_sync_protocol_bookmark_model_metadata_proto_rawDescData []byte
)

func file_components_sync_protocol_bookmark_model_metadata_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_bookmark_model_metadata_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_bookmark_model_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_bookmark_model_metadata_proto_rawDesc), len(file_components_sync_protocol_bookmark_model_metadata_proto_rawDesc)))
	})
	return file_components_sync_protocol_bookmark_model_metadata_proto_rawDescData
}

var file_components_sync_protocol_bookmark_model_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_components_sync_protocol_bookmark_model_metadata_proto_goTypes = []any{
	(*BookmarkMetadata)(nil),      // 0: sync_pb.BookmarkMetadata
	(*BookmarkModelMetadata)(nil), // 1: sync_pb.BookmarkModelMetadata
	(*EntityMetadata)(nil),        // 2: sync_pb.EntityMetadata
	(*DataTypeState)(nil),         // 3: sync_pb.DataTypeState
}
var file_components_sync_protocol_bookmark_model_metadata_proto_depIdxs = []int32{
	2, // 0: sync_pb.BookmarkMetadata.metadata:type_name -> sync_pb.EntityMetadata
	3, // 1: sync_pb.BookmarkModelMetadata.data_type_state:type_name -> sync_pb.DataTypeState
	0, // 2: sync_pb.BookmarkModelMetadata.bookmarks_metadata:type_name -> sync_pb.BookmarkMetadata
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_bookmark_model_metadata_proto_init() }
func file_components_sync_protocol_bookmark_model_metadata_proto_init() {
	if File_components_sync_protocol_bookmark_model_metadata_proto != nil {
		return
	}
	file_components_sync_protocol_data_type_state_proto_init()
	file_components_sync_protocol_entity_metadata_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_bookmark_model_metadata_proto_rawDesc), len(file_components_sync_protocol_bookmark_model_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_bookmark_model_metadata_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_bookmark_model_metadata_proto_depIdxs,
		MessageInfos:      file_components_sync_protocol_bookmark_model_metadata_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_bookmark_model_metadata_proto = out.File
	file_components_sync_protocol_bookmark_model_metadata_proto_goTypes = nil
	file_components_sync_protocol_bookmark_model_metadata_proto_depIdxs = nil
}
