// Copyright 2012 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// Sync protocol for communication between sync client and server.

// If you change or add any fields in this file, update proto_visitors.h and
// potentially proto_enum_conversions.{h, cc}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/client_commands.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomNudgeDelay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatatypeId    *int32                 `protobuf:"varint,1,opt,name=datatype_id,json=datatypeId" json:"datatype_id,omitempty"` // Datatype id.
	DelayMs       *int32                 `protobuf:"varint,2,opt,name=delay_ms,json=delayMs" json:"delay_ms,omitempty"`          // Delay in milliseconds.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomNudgeDelay) Reset() {
	*x = CustomNudgeDelay{}
	mi := &file_components_sync_protocol_client_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomNudgeDelay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomNudgeDelay) ProtoMessage() {}

func (x *CustomNudgeDelay) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_client_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomNudgeDelay.ProtoReflect.Descriptor instead.
func (*CustomNudgeDelay) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_client_commands_proto_rawDescGZIP(), []int{0}
}

func (x *CustomNudgeDelay) GetDatatypeId() int32 {
	if x != nil && x.DatatypeId != nil {
		return *x.DatatypeId
	}
	return 0
}

func (x *CustomNudgeDelay) GetDelayMs() int32 {
	if x != nil && x.DelayMs != nil {
		return *x.DelayMs
	}
	return 0
}

type ClientCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time to wait before sending any requests to the server.
	SetSyncPollInterval *int32 `protobuf:"varint,1,opt,name=set_sync_poll_interval,json=setSyncPollInterval" json:"set_sync_poll_interval,omitempty"` // in seconds
	// This has been deprecated since M75.
	//
	// Deprecated: Marked as deprecated in components/sync/protocol/client_commands.proto.
	SetSyncLongPollInterval *int32 `protobuf:"varint,2,opt,name=set_sync_long_poll_interval,json=setSyncLongPollInterval" json:"set_sync_long_poll_interval,omitempty"`
	MaxCommitBatchSize      *int32 `protobuf:"varint,3,opt,name=max_commit_batch_size,json=maxCommitBatchSize" json:"max_commit_batch_size,omitempty"`
	// Number of seconds to delay before the throttled client should retry.
	ThrottleDelaySeconds *int32 `protobuf:"varint,5,opt,name=throttle_delay_seconds,json=throttleDelaySeconds" json:"throttle_delay_seconds,omitempty"`
	// This has been deprecated since M109.
	//
	// Deprecated: Marked as deprecated in components/sync/protocol/client_commands.proto.
	ClientInvalidationHintBufferSize *int32 `protobuf:"varint,6,opt,name=client_invalidation_hint_buffer_size,json=clientInvalidationHintBufferSize" json:"client_invalidation_hint_buffer_size,omitempty"`
	// A dictionary of custom nudge delays.
	CustomNudgeDelays []*CustomNudgeDelay `protobuf:"bytes,8,rep,name=custom_nudge_delays,json=customNudgeDelays" json:"custom_nudge_delays,omitempty"`
	// Configuration for commit quota of extension-related data types.
	// The maximum count of tokens (=initial at browser startup) and the
	// interval for refilling one more token if not at maximum.
	ExtensionTypesMaxTokens             *int32 `protobuf:"varint,9,opt,name=extension_types_max_tokens,json=extensionTypesMaxTokens" json:"extension_types_max_tokens,omitempty"`
	ExtensionTypesRefillIntervalSeconds *int32 `protobuf:"varint,10,opt,name=extension_types_refill_interval_seconds,json=extensionTypesRefillIntervalSeconds" json:"extension_types_refill_interval_seconds,omitempty"`
	// Extended nudge delay for data types with depleted quota.
	ExtensionTypesDepletedQuotaNudgeDelaySeconds *int32 `protobuf:"varint,11,opt,name=extension_types_depleted_quota_nudge_delay_seconds,json=extensionTypesDepletedQuotaNudgeDelaySeconds" json:"extension_types_depleted_quota_nudge_delay_seconds,omitempty"`
	unknownFields                                protoimpl.UnknownFields
	sizeCache                                    protoimpl.SizeCache
}

func (x *ClientCommand) Reset() {
	*x = ClientCommand{}
	mi := &file_components_sync_protocol_client_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCommand) ProtoMessage() {}

func (x *ClientCommand) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_client_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCommand.ProtoReflect.Descriptor instead.
func (*ClientCommand) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_client_commands_proto_rawDescGZIP(), []int{1}
}

func (x *ClientCommand) GetSetSyncPollInterval() int32 {
	if x != nil && x.SetSyncPollInterval != nil {
		return *x.SetSyncPollInterval
	}
	return 0
}

// Deprecated: Marked as deprecated in components/sync/protocol/client_commands.proto.
func (x *ClientCommand) GetSetSyncLongPollInterval() int32 {
	if x != nil && x.SetSyncLongPollInterval != nil {
		return *x.SetSyncLongPollInterval
	}
	return 0
}

func (x *ClientCommand) GetMaxCommitBatchSize() int32 {
	if x != nil && x.MaxCommitBatchSize != nil {
		return *x.MaxCommitBatchSize
	}
	return 0
}

func (x *ClientCommand) GetThrottleDelaySeconds() int32 {
	if x != nil && x.ThrottleDelaySeconds != nil {
		return *x.ThrottleDelaySeconds
	}
	return 0
}

// Deprecated: Marked as deprecated in components/sync/protocol/client_commands.proto.
func (x *ClientCommand) GetClientInvalidationHintBufferSize() int32 {
	if x != nil && x.ClientInvalidationHintBufferSize != nil {
		return *x.ClientInvalidationHintBufferSize
	}
	return 0
}

func (x *ClientCommand) GetCustomNudgeDelays() []*CustomNudgeDelay {
	if x != nil {
		return x.CustomNudgeDelays
	}
	return nil
}

func (x *ClientCommand) GetExtensionTypesMaxTokens() int32 {
	if x != nil && x.ExtensionTypesMaxTokens != nil {
		return *x.ExtensionTypesMaxTokens
	}
	return 0
}

func (x *ClientCommand) GetExtensionTypesRefillIntervalSeconds() int32 {
	if x != nil && x.ExtensionTypesRefillIntervalSeconds != nil {
		return *x.ExtensionTypesRefillIntervalSeconds
	}
	return 0
}

func (x *ClientCommand) GetExtensionTypesDepletedQuotaNudgeDelaySeconds() int32 {
	if x != nil && x.ExtensionTypesDepletedQuotaNudgeDelaySeconds != nil {
		return *x.ExtensionTypesDepletedQuotaNudgeDelaySeconds
	}
	return 0
}

var File_components_sync_protocol_client_commands_proto protoreflect.FileDescriptor

const file_components_sync_protocol_client_commands_proto_rawDesc = "" +
	"\n" +
	".components/sync/protocol/client_commands.proto\x12\async_pb\"N\n" +
	"\x10CustomNudgeDelay\x12\x1f\n" +
	"\vdatatype_id\x18\x01 \x01(\x05R\n" +
	"datatypeId\x12\x19\n" +
	"\bdelay_ms\x18\x02 \x01(\x05R\adelayMs\"\xce\x05\n" +
	"\rClientCommand\x123\n" +
	"\x16set_sync_poll_interval\x18\x01 \x01(\x05R\x13setSyncPollInterval\x12@\n" +
	"\x1bset_sync_long_poll_interval\x18\x02 \x01(\x05B\x02\x18\x01R\x17setSyncLongPollInterval\x121\n" +
	"\x15max_commit_batch_size\x18\x03 \x01(\x05R\x12maxCommitBatchSize\x124\n" +
	"\x16throttle_delay_seconds\x18\x05 \x01(\x05R\x14throttleDelaySeconds\x12R\n" +
	"$client_invalidation_hint_buffer_size\x18\x06 \x01(\x05B\x02\x18\x01R clientInvalidationHintBufferSize\x12I\n" +
	"\x13custom_nudge_delays\x18\b \x03(\v2\x19.sync_pb.CustomNudgeDelayR\x11customNudgeDelays\x12;\n" +
	"\x1aextension_types_max_tokens\x18\t \x01(\x05R\x17extensionTypesMaxTokens\x12T\n" +
	"'extension_types_refill_interval_seconds\x18\n" +
	" \x01(\x05R#extensionTypesRefillIntervalSeconds\x12h\n" +
	"2extension_types_depleted_quota_nudge_delay_seconds\x18\v \x01(\x05R,extensionTypesDepletedQuotaNudgeDelaySecondsJ\x04\b\x04\x10\x05J\x04\b\a\x10\bR\x1dsessions_commit_delay_secondsR\x16gu_retry_delay_secondsB+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_client_commands_proto_rawDescOnce sync.Once
	file_components_sync_protocol_client_commands_proto_rawDescData []byte
)

func file_components_sync_protocol_client_commands_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_client_commands_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_client_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_client_commands_proto_rawDesc), len(file_components_sync_protocol_client_commands_proto_rawDesc)))
	})
	return file_components_sync_protocol_client_commands_proto_rawDescData
}

var file_components_sync_protocol_client_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_components_sync_protocol_client_commands_proto_goTypes = []any{
	(*CustomNudgeDelay)(nil), // 0: sync_pb.CustomNudgeDelay
	(*ClientCommand)(nil),    // 1: sync_pb.ClientCommand
}
var file_components_sync_protocol_client_commands_proto_depIdxs = []int32{
	0, // 0: sync_pb.ClientCommand.custom_nudge_delays:type_name -> sync_pb.CustomNudgeDelay
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_client_commands_proto_init() }
func file_components_sync_protocol_client_commands_proto_init() {
	if File_components_sync_protocol_client_commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_client_commands_proto_rawDesc), len(file_components_sync_protocol_client_commands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_client_commands_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_client_commands_proto_depIdxs,
		MessageInfos:      file_components_sync_protocol_client_commands_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_client_commands_proto = out.File
	file_components_sync_protocol_client_commands_proto_goTypes = nil
	file_components_sync_protocol_client_commands_proto_depIdxs = nil
}
