// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/cookie_specifics.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The numbering is different compared to the `net::CookieSameSite` enum since
// the style guide asks to use UNSPECIFIED for the zero value enum
// (https://protobuf.dev/programming-guides/style/#enums).
type CookieSpecifics_CookieSameSite int32

const (
	CookieSpecifics_UNSPECIFIED    CookieSpecifics_CookieSameSite = 0
	CookieSpecifics_NO_RESTRICTION CookieSpecifics_CookieSameSite = 1
	CookieSpecifics_LAX_MODE       CookieSpecifics_CookieSameSite = 2
	CookieSpecifics_STRICT_MODE    CookieSpecifics_CookieSameSite = 3
)

// Enum value maps for CookieSpecifics_CookieSameSite.
var (
	CookieSpecifics_CookieSameSite_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "NO_RESTRICTION",
		2: "LAX_MODE",
		3: "STRICT_MODE",
	}
	CookieSpecifics_CookieSameSite_value = map[string]int32{
		"UNSPECIFIED":    0,
		"NO_RESTRICTION": 1,
		"LAX_MODE":       2,
		"STRICT_MODE":    3,
	}
)

func (x CookieSpecifics_CookieSameSite) Enum() *CookieSpecifics_CookieSameSite {
	p := new(CookieSpecifics_CookieSameSite)
	*p = x
	return p
}

func (x CookieSpecifics_CookieSameSite) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CookieSpecifics_CookieSameSite) Descriptor() protoreflect.EnumDescriptor {
	return file_components_sync_protocol_cookie_specifics_proto_enumTypes[0].Descriptor()
}

func (CookieSpecifics_CookieSameSite) Type() protoreflect.EnumType {
	return &file_components_sync_protocol_cookie_specifics_proto_enumTypes[0]
}

func (x CookieSpecifics_CookieSameSite) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CookieSpecifics_CookieSameSite) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CookieSpecifics_CookieSameSite(num)
	return nil
}

// Deprecated: Use CookieSpecifics_CookieSameSite.Descriptor instead.
func (CookieSpecifics_CookieSameSite) EnumDescriptor() ([]byte, []int) {
	return file_components_sync_protocol_cookie_specifics_proto_rawDescGZIP(), []int{0, 0}
}

// The numbering is different compared to the `net::CookiePriority` enum since
// the style guide asks to use UNSPECIFIED for the zero value enum
// (https://protobuf.dev/programming-guides/style/#enums).
type CookieSpecifics_CookiePriority int32

const (
	CookieSpecifics_UNSPECIFIED_PRIORITY CookieSpecifics_CookiePriority = 0
	CookieSpecifics_LOW                  CookieSpecifics_CookiePriority = 1
	CookieSpecifics_MEDIUM               CookieSpecifics_CookiePriority = 2
	CookieSpecifics_HIGH                 CookieSpecifics_CookiePriority = 3
)

// Enum value maps for CookieSpecifics_CookiePriority.
var (
	CookieSpecifics_CookiePriority_name = map[int32]string{
		0: "UNSPECIFIED_PRIORITY",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
	}
	CookieSpecifics_CookiePriority_value = map[string]int32{
		"UNSPECIFIED_PRIORITY": 0,
		"LOW":                  1,
		"MEDIUM":               2,
		"HIGH":                 3,
	}
)

func (x CookieSpecifics_CookiePriority) Enum() *CookieSpecifics_CookiePriority {
	p := new(CookieSpecifics_CookiePriority)
	*p = x
	return p
}

func (x CookieSpecifics_CookiePriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CookieSpecifics_CookiePriority) Descriptor() protoreflect.EnumDescriptor {
	return file_components_sync_protocol_cookie_specifics_proto_enumTypes[1].Descriptor()
}

func (CookieSpecifics_CookiePriority) Type() protoreflect.EnumType {
	return &file_components_sync_protocol_cookie_specifics_proto_enumTypes[1]
}

func (x CookieSpecifics_CookiePriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CookieSpecifics_CookiePriority) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CookieSpecifics_CookiePriority(num)
	return nil
}

// Deprecated: Use CookieSpecifics_CookiePriority.Descriptor instead.
func (CookieSpecifics_CookiePriority) EnumDescriptor() ([]byte, []int) {
	return file_components_sync_protocol_cookie_specifics_proto_rawDescGZIP(), []int{0, 1}
}

type CookieSpecifics_CookieSourceScheme int32

const (
	CookieSpecifics_UNSET      CookieSpecifics_CookieSourceScheme = 0
	CookieSpecifics_NON_SECURE CookieSpecifics_CookieSourceScheme = 1
	CookieSpecifics_SECURE     CookieSpecifics_CookieSourceScheme = 2
)

// Enum value maps for CookieSpecifics_CookieSourceScheme.
var (
	CookieSpecifics_CookieSourceScheme_name = map[int32]string{
		0: "UNSET",
		1: "NON_SECURE",
		2: "SECURE",
	}
	CookieSpecifics_CookieSourceScheme_value = map[string]int32{
		"UNSET":      0,
		"NON_SECURE": 1,
		"SECURE":     2,
	}
)

func (x CookieSpecifics_CookieSourceScheme) Enum() *CookieSpecifics_CookieSourceScheme {
	p := new(CookieSpecifics_CookieSourceScheme)
	*p = x
	return p
}

func (x CookieSpecifics_CookieSourceScheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CookieSpecifics_CookieSourceScheme) Descriptor() protoreflect.EnumDescriptor {
	return file_components_sync_protocol_cookie_specifics_proto_enumTypes[2].Descriptor()
}

func (CookieSpecifics_CookieSourceScheme) Type() protoreflect.EnumType {
	return &file_components_sync_protocol_cookie_specifics_proto_enumTypes[2]
}

func (x CookieSpecifics_CookieSourceScheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CookieSpecifics_CookieSourceScheme) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CookieSpecifics_CookieSourceScheme(num)
	return nil
}

// Deprecated: Use CookieSpecifics_CookieSourceScheme.Descriptor instead.
func (CookieSpecifics_CookieSourceScheme) EnumDescriptor() ([]byte, []int) {
	return file_components_sync_protocol_cookie_specifics_proto_rawDescGZIP(), []int{0, 2}
}

type CookieSpecifics_CookieSourceType int32

const (
	CookieSpecifics_UNKNOWN CookieSpecifics_CookieSourceType = 0
	CookieSpecifics_HTTP    CookieSpecifics_CookieSourceType = 1
	CookieSpecifics_SCRIPT  CookieSpecifics_CookieSourceType = 2
	CookieSpecifics_OTHER   CookieSpecifics_CookieSourceType = 3
)

// Enum value maps for CookieSpecifics_CookieSourceType.
var (
	CookieSpecifics_CookieSourceType_name = map[int32]string{
		0: "UNKNOWN",
		1: "HTTP",
		2: "SCRIPT",
		3: "OTHER",
	}
	CookieSpecifics_CookieSourceType_value = map[string]int32{
		"UNKNOWN": 0,
		"HTTP":    1,
		"SCRIPT":  2,
		"OTHER":   3,
	}
)

func (x CookieSpecifics_CookieSourceType) Enum() *CookieSpecifics_CookieSourceType {
	p := new(CookieSpecifics_CookieSourceType)
	*p = x
	return p
}

func (x CookieSpecifics_CookieSourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CookieSpecifics_CookieSourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_components_sync_protocol_cookie_specifics_proto_enumTypes[3].Descriptor()
}

func (CookieSpecifics_CookieSourceType) Type() protoreflect.EnumType {
	return &file_components_sync_protocol_cookie_specifics_proto_enumTypes[3]
}

func (x CookieSpecifics_CookieSourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CookieSpecifics_CookieSourceType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CookieSpecifics_CookieSourceType(num)
	return nil
}

// Deprecated: Use CookieSpecifics_CookieSourceType.Descriptor instead.
func (CookieSpecifics_CookieSourceType) EnumDescriptor() ([]byte, []int) {
	return file_components_sync_protocol_cookie_specifics_proto_rawDescGZIP(), []int{0, 3}
}

// This proto represents a single cookie. Except for `unique_key` all
// fields should be the same as in `net::CanonicalCookie`.
type CookieSpecifics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// To be used as a Sync client tag, corresponds to `StrictlyUniqueCookieKey`.
	// `StrictlyUniqueCookieKey` contains selected members of
	// `net::CanonicalCoookie` which we already save in specifics, but we save the
	// key separately to be resilient against future changes to
	// `StrictlyUniqueCookieKey`. By reading it from this field (instead of
	// computing it from other data in specifics) we make sure that the client tag
	// will be stable across different Chrome versions. It also leaves the option
	// to check if the key saved in a given entity is aligned with the current
	// definition of `StrictlyUniqueCookieKey`. If it is not, client can choose to
	// ignore that entity, or implement any other special handling. The string
	// saved here is expected to be computed by concatenating serialized values
	// from the `StrictlyUniqueCookieKey` for the corresponding cookie.
	UniqueKey                        *string                                       `protobuf:"bytes,1,opt,name=unique_key,json=uniqueKey" json:"unique_key,omitempty"`
	Name                             *string                                       `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Value                            *string                                       `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	Domain                           *string                                       `protobuf:"bytes,4,opt,name=domain" json:"domain,omitempty"`
	Path                             *string                                       `protobuf:"bytes,5,opt,name=path" json:"path,omitempty"`
	CreationTimeWindowsEpochMicros   *int64                                        `protobuf:"varint,6,opt,name=creation_time_windows_epoch_micros,json=creationTimeWindowsEpochMicros" json:"creation_time_windows_epoch_micros,omitempty"`
	ExpiryTimeWindowsEpochMicros     *int64                                        `protobuf:"varint,7,opt,name=expiry_time_windows_epoch_micros,json=expiryTimeWindowsEpochMicros" json:"expiry_time_windows_epoch_micros,omitempty"`
	LastAccessTimeWindowsEpochMicros *int64                                        `protobuf:"varint,8,opt,name=last_access_time_windows_epoch_micros,json=lastAccessTimeWindowsEpochMicros" json:"last_access_time_windows_epoch_micros,omitempty"`
	LastUpdateTimeWindowsEpochMicros *int64                                        `protobuf:"varint,9,opt,name=last_update_time_windows_epoch_micros,json=lastUpdateTimeWindowsEpochMicros" json:"last_update_time_windows_epoch_micros,omitempty"`
	Secure                           *bool                                         `protobuf:"varint,10,opt,name=secure" json:"secure,omitempty"`
	Httponly                         *bool                                         `protobuf:"varint,11,opt,name=httponly" json:"httponly,omitempty"`
	SiteRestrictions                 *CookieSpecifics_CookieSameSite               `protobuf:"varint,12,opt,name=site_restrictions,json=siteRestrictions,enum=sync_pb.CookieSpecifics_CookieSameSite" json:"site_restrictions,omitempty"`
	Priority                         *CookieSpecifics_CookiePriority               `protobuf:"varint,13,opt,name=priority,enum=sync_pb.CookieSpecifics_CookiePriority" json:"priority,omitempty"`
	SourceScheme                     *CookieSpecifics_CookieSourceScheme           `protobuf:"varint,14,opt,name=source_scheme,json=sourceScheme,enum=sync_pb.CookieSpecifics_CookieSourceScheme" json:"source_scheme,omitempty"`
	PartitionKey                     *CookieSpecifics_SerializedCookiePartitionKey `protobuf:"bytes,15,opt,name=partition_key,json=partitionKey" json:"partition_key,omitempty"`
	SourcePort                       *int32                                        `protobuf:"varint,16,opt,name=source_port,json=sourcePort" json:"source_port,omitempty"`
	SourceType                       *CookieSpecifics_CookieSourceType             `protobuf:"varint,17,opt,name=source_type,json=sourceType,enum=sync_pb.CookieSpecifics_CookieSourceType" json:"source_type,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *CookieSpecifics) Reset() {
	*x = CookieSpecifics{}
	mi := &file_components_sync_protocol_cookie_specifics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CookieSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CookieSpecifics) ProtoMessage() {}

func (x *CookieSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_cookie_specifics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CookieSpecifics.ProtoReflect.Descriptor instead.
func (*CookieSpecifics) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_cookie_specifics_proto_rawDescGZIP(), []int{0}
}

func (x *CookieSpecifics) GetUniqueKey() string {
	if x != nil && x.UniqueKey != nil {
		return *x.UniqueKey
	}
	return ""
}

func (x *CookieSpecifics) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CookieSpecifics) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *CookieSpecifics) GetDomain() string {
	if x != nil && x.Domain != nil {
		return *x.Domain
	}
	return ""
}

func (x *CookieSpecifics) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *CookieSpecifics) GetCreationTimeWindowsEpochMicros() int64 {
	if x != nil && x.CreationTimeWindowsEpochMicros != nil {
		return *x.CreationTimeWindowsEpochMicros
	}
	return 0
}

func (x *CookieSpecifics) GetExpiryTimeWindowsEpochMicros() int64 {
	if x != nil && x.ExpiryTimeWindowsEpochMicros != nil {
		return *x.ExpiryTimeWindowsEpochMicros
	}
	return 0
}

func (x *CookieSpecifics) GetLastAccessTimeWindowsEpochMicros() int64 {
	if x != nil && x.LastAccessTimeWindowsEpochMicros != nil {
		return *x.LastAccessTimeWindowsEpochMicros
	}
	return 0
}

func (x *CookieSpecifics) GetLastUpdateTimeWindowsEpochMicros() int64 {
	if x != nil && x.LastUpdateTimeWindowsEpochMicros != nil {
		return *x.LastUpdateTimeWindowsEpochMicros
	}
	return 0
}

func (x *CookieSpecifics) GetSecure() bool {
	if x != nil && x.Secure != nil {
		return *x.Secure
	}
	return false
}

func (x *CookieSpecifics) GetHttponly() bool {
	if x != nil && x.Httponly != nil {
		return *x.Httponly
	}
	return false
}

func (x *CookieSpecifics) GetSiteRestrictions() CookieSpecifics_CookieSameSite {
	if x != nil && x.SiteRestrictions != nil {
		return *x.SiteRestrictions
	}
	return CookieSpecifics_UNSPECIFIED
}

func (x *CookieSpecifics) GetPriority() CookieSpecifics_CookiePriority {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return CookieSpecifics_UNSPECIFIED_PRIORITY
}

func (x *CookieSpecifics) GetSourceScheme() CookieSpecifics_CookieSourceScheme {
	if x != nil && x.SourceScheme != nil {
		return *x.SourceScheme
	}
	return CookieSpecifics_UNSET
}

func (x *CookieSpecifics) GetPartitionKey() *CookieSpecifics_SerializedCookiePartitionKey {
	if x != nil {
		return x.PartitionKey
	}
	return nil
}

func (x *CookieSpecifics) GetSourcePort() int32 {
	if x != nil && x.SourcePort != nil {
		return *x.SourcePort
	}
	return 0
}

func (x *CookieSpecifics) GetSourceType() CookieSpecifics_CookieSourceType {
	if x != nil && x.SourceType != nil {
		return *x.SourceType
	}
	return CookieSpecifics_UNKNOWN
}

type CookieSpecifics_SerializedCookiePartitionKey struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TopLevelSite         *string                `protobuf:"bytes,1,opt,name=top_level_site,json=topLevelSite" json:"top_level_site,omitempty"`
	HasCrossSiteAncestor *bool                  `protobuf:"varint,2,opt,name=has_cross_site_ancestor,json=hasCrossSiteAncestor" json:"has_cross_site_ancestor,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CookieSpecifics_SerializedCookiePartitionKey) Reset() {
	*x = CookieSpecifics_SerializedCookiePartitionKey{}
	mi := &file_components_sync_protocol_cookie_specifics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CookieSpecifics_SerializedCookiePartitionKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CookieSpecifics_SerializedCookiePartitionKey) ProtoMessage() {}

func (x *CookieSpecifics_SerializedCookiePartitionKey) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_cookie_specifics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CookieSpecifics_SerializedCookiePartitionKey.ProtoReflect.Descriptor instead.
func (*CookieSpecifics_SerializedCookiePartitionKey) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_cookie_specifics_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CookieSpecifics_SerializedCookiePartitionKey) GetTopLevelSite() string {
	if x != nil && x.TopLevelSite != nil {
		return *x.TopLevelSite
	}
	return ""
}

func (x *CookieSpecifics_SerializedCookiePartitionKey) GetHasCrossSiteAncestor() bool {
	if x != nil && x.HasCrossSiteAncestor != nil {
		return *x.HasCrossSiteAncestor
	}
	return false
}

var File_components_sync_protocol_cookie_specifics_proto protoreflect.FileDescriptor

const file_components_sync_protocol_cookie_specifics_proto_rawDesc = "" +
	"\n" +
	"/components/sync/protocol/cookie_specifics.proto\x12\async_pb\"\xc3\n" +
	"\n" +
	"\x0fCookieSpecifics\x12\x1d\n" +
	"\n" +
	"unique_key\x18\x01 \x01(\tR\tuniqueKey\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12J\n" +
	"\"creation_time_windows_epoch_micros\x18\x06 \x01(\x03R\x1ecreationTimeWindowsEpochMicros\x12F\n" +
	" expiry_time_windows_epoch_micros\x18\a \x01(\x03R\x1cexpiryTimeWindowsEpochMicros\x12O\n" +
	"%last_access_time_windows_epoch_micros\x18\b \x01(\x03R lastAccessTimeWindowsEpochMicros\x12O\n" +
	"%last_update_time_windows_epoch_micros\x18\t \x01(\x03R lastUpdateTimeWindowsEpochMicros\x12\x16\n" +
	"\x06secure\x18\n" +
	" \x01(\bR\x06secure\x12\x1a\n" +
	"\bhttponly\x18\v \x01(\bR\bhttponly\x12T\n" +
	"\x11site_restrictions\x18\f \x01(\x0e2'.sync_pb.CookieSpecifics.CookieSameSiteR\x10siteRestrictions\x12C\n" +
	"\bpriority\x18\r \x01(\x0e2'.sync_pb.CookieSpecifics.CookiePriorityR\bpriority\x12P\n" +
	"\rsource_scheme\x18\x0e \x01(\x0e2+.sync_pb.CookieSpecifics.CookieSourceSchemeR\fsourceScheme\x12Z\n" +
	"\rpartition_key\x18\x0f \x01(\v25.sync_pb.CookieSpecifics.SerializedCookiePartitionKeyR\fpartitionKey\x12\x1f\n" +
	"\vsource_port\x18\x10 \x01(\x05R\n" +
	"sourcePort\x12J\n" +
	"\vsource_type\x18\x11 \x01(\x0e2).sync_pb.CookieSpecifics.CookieSourceTypeR\n" +
	"sourceType\x1a{\n" +
	"\x1cSerializedCookiePartitionKey\x12$\n" +
	"\x0etop_level_site\x18\x01 \x01(\tR\ftopLevelSite\x125\n" +
	"\x17has_cross_site_ancestor\x18\x02 \x01(\bR\x14hasCrossSiteAncestor\"T\n" +
	"\x0eCookieSameSite\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eNO_RESTRICTION\x10\x01\x12\f\n" +
	"\bLAX_MODE\x10\x02\x12\x0f\n" +
	"\vSTRICT_MODE\x10\x03\"I\n" +
	"\x0eCookiePriority\x12\x18\n" +
	"\x14UNSPECIFIED_PRIORITY\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\";\n" +
	"\x12CookieSourceScheme\x12\t\n" +
	"\x05UNSET\x10\x00\x12\x0e\n" +
	"\n" +
	"NON_SECURE\x10\x01\x12\n" +
	"\n" +
	"\x06SECURE\x10\x02\"@\n" +
	"\x10CookieSourceType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04HTTP\x10\x01\x12\n" +
	"\n" +
	"\x06SCRIPT\x10\x02\x12\t\n" +
	"\x05OTHER\x10\x03B+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_cookie_specifics_proto_rawDescOnce sync.Once
	file_components_sync_protocol_cookie_specifics_proto_rawDescData []byte
)

func file_components_sync_protocol_cookie_specifics_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_cookie_specifics_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_cookie_specifics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_cookie_specifics_proto_rawDesc), len(file_components_sync_protocol_cookie_specifics_proto_rawDesc)))
	})
	return file_components_sync_protocol_cookie_specifics_proto_rawDescData
}

var file_components_sync_protocol_cookie_specifics_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_components_sync_protocol_cookie_specifics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_components_sync_protocol_cookie_specifics_proto_goTypes = []any{
	(CookieSpecifics_CookieSameSite)(0),                  // 0: sync_pb.CookieSpecifics.CookieSameSite
	(CookieSpecifics_CookiePriority)(0),                  // 1: sync_pb.CookieSpecifics.CookiePriority
	(CookieSpecifics_CookieSourceScheme)(0),              // 2: sync_pb.CookieSpecifics.CookieSourceScheme
	(CookieSpecifics_CookieSourceType)(0),                // 3: sync_pb.CookieSpecifics.CookieSourceType
	(*CookieSpecifics)(nil),                              // 4: sync_pb.CookieSpecifics
	(*CookieSpecifics_SerializedCookiePartitionKey)(nil), // 5: sync_pb.CookieSpecifics.SerializedCookiePartitionKey
}
var file_components_sync_protocol_cookie_specifics_proto_depIdxs = []int32{
	0, // 0: sync_pb.CookieSpecifics.site_restrictions:type_name -> sync_pb.CookieSpecifics.CookieSameSite
	1, // 1: sync_pb.CookieSpecifics.priority:type_name -> sync_pb.CookieSpecifics.CookiePriority
	2, // 2: sync_pb.CookieSpecifics.source_scheme:type_name -> sync_pb.CookieSpecifics.CookieSourceScheme
	5, // 3: sync_pb.CookieSpecifics.partition_key:type_name -> sync_pb.CookieSpecifics.SerializedCookiePartitionKey
	3, // 4: sync_pb.CookieSpecifics.source_type:type_name -> sync_pb.CookieSpecifics.CookieSourceType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_cookie_specifics_proto_init() }
func file_components_sync_protocol_cookie_specifics_proto_init() {
	if File_components_sync_protocol_cookie_specifics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_cookie_specifics_proto_rawDesc), len(file_components_sync_protocol_cookie_specifics_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_cookie_specifics_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_cookie_specifics_proto_depIdxs,
		EnumInfos:         file_components_sync_protocol_cookie_specifics_proto_enumTypes,
		MessageInfos:      file_components_sync_protocol_cookie_specifics_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_cookie_specifics_proto = out.File
	file_components_sync_protocol_cookie_specifics_proto_goTypes = nil
	file_components_sync_protocol_cookie_specifics_proto_depIdxs = nil
}
