// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// Protobuf representation of the DeletionOrigin class.

// If you change or add any fields in this file, update proto_visitors.h and
// potentially proto_enum_conversions.{h, cc}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/deletion_origin.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a fingerprint-like token that identifies, or may help identity,
// which piece of functionality is responsible for issuing a deletion that
// propagates via Sync. It is sent to the Sync server as part of deletion
// requests, as a safeguard to investigate and mitigate user reports or even
// large-scale incidents.
type DeletionOrigin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Populated by chromium-based browsers with the version that originally
	// created the deletion. This will often be the same as the version that
	// uploaded (committed) the deletion, but in rare cases the latter could be
	// greater (i.e. the browser was updated in between).
	ChromiumVersion *string `protobuf:"bytes,1,opt,name=chromium_version,json=chromiumVersion" json:"chromium_version,omitempty"`
	// Populated by Android Google Play Services with the version of the APK
	// identifying the version that originally created the deletion. This should
	// not be populated for DeletionOrigin instances that go through Google Play
	// Services but were actually first triggered in chromium.
	GooglePlayServicesApkVersionName *string `protobuf:"bytes,2,opt,name=google_play_services_apk_version_name,json=googlePlayServicesApkVersionName" json:"google_play_services_apk_version_name,omitempty"`
	// Hash of the filename in the source code where the deletion originated. The
	// precise hashing function is unspecified and may change over time. It may
	// only be assumed that the hashing function is the same for a given version
	// of the client (see fields above). Hashing is used instead of including the
	// actual name to reduce the size of this message.
	FileNameHash *uint32 `protobuf:"fixed32,3,opt,name=file_name_hash,json=fileNameHash" json:"file_name_hash,omitempty"`
	// Line of code where the deletion originated.
	FileLineNumber *int32 `protobuf:"varint,4,opt,name=file_line_number,json=fileLineNumber" json:"file_line_number,omitempty"`
	// Human-readable and extra optional version of `file_name_hash`. Since the
	// file name can be long and includes the full path, this string is very
	// likely truncated (and hence not guaranteed to be unique). Truncation will
	// remove the beginning of the string rather than the end of it.
	FileNamePossiblyTruncated *string `protobuf:"bytes,5,opt,name=file_name_possibly_truncated,json=fileNamePossiblyTruncated" json:"file_name_possibly_truncated,omitempty"`
	// Arbitrary but unique tag defined in the source code, when other means
	// like the file name and line number aren't possible or desirable. This
	// string isn't meant to be too long (recommended limit of 30 characters) and
	// is subject to truncation any time. If truncation is used, it will remove
	// the beginning of the string rather than the end of it. This field must not
	// contain personally-identifiable information.
	UniqueSourceTagNoPiiPossiblyTruncated *string `protobuf:"bytes,6,opt,name=unique_source_tag_no_pii_possibly_truncated,json=uniqueSourceTagNoPiiPossiblyTruncated" json:"unique_source_tag_no_pii_possibly_truncated,omitempty"`
	// Google Play Services enum. Used only for deletions triggered internally.
	// This field is not populated or used in Chromium.
	GooglePlayServicesDeletionOriginType *int32 `protobuf:"varint,7,opt,name=google_play_services_deletion_origin_type,json=googlePlayServicesDeletionOriginType" json:"google_play_services_deletion_origin_type,omitempty"`
	// Android SDK version.
	// This field is not populated or used in Chromium.
	GooglePlayServicesSdkVersion *string `protobuf:"bytes,8,opt,name=google_play_services_sdk_version,json=googlePlayServicesSdkVersion" json:"google_play_services_sdk_version,omitempty"`
	// Form factor of the device.
	// This field is not populated or used in Chromium.
	GooglePlayServicesDeviceFormFactor *SyncEnums_DeviceFormFactor `protobuf:"varint,9,opt,name=google_play_services_device_form_factor,json=googlePlayServicesDeviceFormFactor,enum=sync_pb.SyncEnums_DeviceFormFactor" json:"google_play_services_device_form_factor,omitempty"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *DeletionOrigin) Reset() {
	*x = DeletionOrigin{}
	mi := &file_components_sync_protocol_deletion_origin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletionOrigin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletionOrigin) ProtoMessage() {}

func (x *DeletionOrigin) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_deletion_origin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletionOrigin.ProtoReflect.Descriptor instead.
func (*DeletionOrigin) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_deletion_origin_proto_rawDescGZIP(), []int{0}
}

func (x *DeletionOrigin) GetChromiumVersion() string {
	if x != nil && x.ChromiumVersion != nil {
		return *x.ChromiumVersion
	}
	return ""
}

func (x *DeletionOrigin) GetGooglePlayServicesApkVersionName() string {
	if x != nil && x.GooglePlayServicesApkVersionName != nil {
		return *x.GooglePlayServicesApkVersionName
	}
	return ""
}

func (x *DeletionOrigin) GetFileNameHash() uint32 {
	if x != nil && x.FileNameHash != nil {
		return *x.FileNameHash
	}
	return 0
}

func (x *DeletionOrigin) GetFileLineNumber() int32 {
	if x != nil && x.FileLineNumber != nil {
		return *x.FileLineNumber
	}
	return 0
}

func (x *DeletionOrigin) GetFileNamePossiblyTruncated() string {
	if x != nil && x.FileNamePossiblyTruncated != nil {
		return *x.FileNamePossiblyTruncated
	}
	return ""
}

func (x *DeletionOrigin) GetUniqueSourceTagNoPiiPossiblyTruncated() string {
	if x != nil && x.UniqueSourceTagNoPiiPossiblyTruncated != nil {
		return *x.UniqueSourceTagNoPiiPossiblyTruncated
	}
	return ""
}

func (x *DeletionOrigin) GetGooglePlayServicesDeletionOriginType() int32 {
	if x != nil && x.GooglePlayServicesDeletionOriginType != nil {
		return *x.GooglePlayServicesDeletionOriginType
	}
	return 0
}

func (x *DeletionOrigin) GetGooglePlayServicesSdkVersion() string {
	if x != nil && x.GooglePlayServicesSdkVersion != nil {
		return *x.GooglePlayServicesSdkVersion
	}
	return ""
}

func (x *DeletionOrigin) GetGooglePlayServicesDeviceFormFactor() SyncEnums_DeviceFormFactor {
	if x != nil && x.GooglePlayServicesDeviceFormFactor != nil {
		return *x.GooglePlayServicesDeviceFormFactor
	}
	return SyncEnums_DEVICE_FORM_FACTOR_UNSPECIFIED
}

var File_components_sync_protocol_deletion_origin_proto protoreflect.FileDescriptor

const file_components_sync_protocol_deletion_origin_proto_rawDesc = "" +
	"\n" +
	".components/sync/protocol/deletion_origin.proto\x12\async_pb\x1a)components/sync/protocol/sync_enums.proto\"\x94\x05\n" +
	"\x0eDeletionOrigin\x12)\n" +
	"\x10chromium_version\x18\x01 \x01(\tR\x0fchromiumVersion\x12O\n" +
	"%google_play_services_apk_version_name\x18\x02 \x01(\tR googlePlayServicesApkVersionName\x12$\n" +
	"\x0efile_name_hash\x18\x03 \x01(\aR\ffileNameHash\x12(\n" +
	"\x10file_line_number\x18\x04 \x01(\x05R\x0efileLineNumber\x12?\n" +
	"\x1cfile_name_possibly_truncated\x18\x05 \x01(\tR\x19fileNamePossiblyTruncated\x12Z\n" +
	"+unique_source_tag_no_pii_possibly_truncated\x18\x06 \x01(\tR%uniqueSourceTagNoPiiPossiblyTruncated\x12W\n" +
	")google_play_services_deletion_origin_type\x18\a \x01(\x05R$googlePlayServicesDeletionOriginType\x12F\n" +
	" google_play_services_sdk_version\x18\b \x01(\tR\x1cgooglePlayServicesSdkVersion\x12x\n" +
	"'google_play_services_device_form_factor\x18\t \x01(\x0e2#.sync_pb.SyncEnums.DeviceFormFactorR\"googlePlayServicesDeviceFormFactorB+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_deletion_origin_proto_rawDescOnce sync.Once
	file_components_sync_protocol_deletion_origin_proto_rawDescData []byte
)

func file_components_sync_protocol_deletion_origin_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_deletion_origin_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_deletion_origin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_deletion_origin_proto_rawDesc), len(file_components_sync_protocol_deletion_origin_proto_rawDesc)))
	})
	return file_components_sync_protocol_deletion_origin_proto_rawDescData
}

var file_components_sync_protocol_deletion_origin_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_components_sync_protocol_deletion_origin_proto_goTypes = []any{
	(*DeletionOrigin)(nil),          // 0: sync_pb.DeletionOrigin
	(SyncEnums_DeviceFormFactor)(0), // 1: sync_pb.SyncEnums.DeviceFormFactor
}
var file_components_sync_protocol_deletion_origin_proto_depIdxs = []int32{
	1, // 0: sync_pb.DeletionOrigin.google_play_services_device_form_factor:type_name -> sync_pb.SyncEnums.DeviceFormFactor
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_deletion_origin_proto_init() }
func file_components_sync_protocol_deletion_origin_proto_init() {
	if File_components_sync_protocol_deletion_origin_proto != nil {
		return
	}
	file_components_sync_protocol_sync_enums_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_deletion_origin_proto_rawDesc), len(file_components_sync_protocol_deletion_origin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_deletion_origin_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_deletion_origin_proto_depIdxs,
		MessageInfos:      file_components_sync_protocol_deletion_origin_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_deletion_origin_proto = out.File
	file_components_sync_protocol_deletion_origin_proto_goTypes = nil
	file_components_sync_protocol_deletion_origin_proto_depIdxs = nil
}
