// Copyright 2012 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// If you change or add any fields in this file, update proto_visitors.h and
// potentially proto_enum_conversions.{h, cc}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/get_updates_caller_info.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUpdatesCallerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if notifications were enabled for this GetUpdateMessage.
	// Note: Ideally this would be moved out of GetUpdatesCallerInfo, so that
	// GetUpdatesCallerInfo itself can be removed.
	NotificationsEnabled *bool `protobuf:"varint,2,opt,name=notifications_enabled,json=notificationsEnabled" json:"notifications_enabled,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetUpdatesCallerInfo) Reset() {
	*x = GetUpdatesCallerInfo{}
	mi := &file_components_sync_protocol_get_updates_caller_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdatesCallerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdatesCallerInfo) ProtoMessage() {}

func (x *GetUpdatesCallerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_get_updates_caller_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdatesCallerInfo.ProtoReflect.Descriptor instead.
func (*GetUpdatesCallerInfo) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_get_updates_caller_info_proto_rawDescGZIP(), []int{0}
}

func (x *GetUpdatesCallerInfo) GetNotificationsEnabled() bool {
	if x != nil && x.NotificationsEnabled != nil {
		return *x.NotificationsEnabled
	}
	return false
}

var File_components_sync_protocol_get_updates_caller_info_proto protoreflect.FileDescriptor

const file_components_sync_protocol_get_updates_caller_info_proto_rawDesc = "" +
	"\n" +
	"6components/sync/protocol/get_updates_caller_info.proto\x12\async_pb\"Y\n" +
	"\x14GetUpdatesCallerInfo\x123\n" +
	"\x15notifications_enabled\x18\x02 \x01(\bR\x14notificationsEnabledJ\x04\b\x01\x10\x02R\x06sourceB+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_get_updates_caller_info_proto_rawDescOnce sync.Once
	file_components_sync_protocol_get_updates_caller_info_proto_rawDescData []byte
)

func file_components_sync_protocol_get_updates_caller_info_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_get_updates_caller_info_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_get_updates_caller_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_get_updates_caller_info_proto_rawDesc), len(file_components_sync_protocol_get_updates_caller_info_proto_rawDesc)))
	})
	return file_components_sync_protocol_get_updates_caller_info_proto_rawDescData
}

var file_components_sync_protocol_get_updates_caller_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_components_sync_protocol_get_updates_caller_info_proto_goTypes = []any{
	(*GetUpdatesCallerInfo)(nil), // 0: sync_pb.GetUpdatesCallerInfo
}
var file_components_sync_protocol_get_updates_caller_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_get_updates_caller_info_proto_init() }
func file_components_sync_protocol_get_updates_caller_info_proto_init() {
	if File_components_sync_protocol_get_updates_caller_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_get_updates_caller_info_proto_rawDesc), len(file_components_sync_protocol_get_updates_caller_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_get_updates_caller_info_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_get_updates_caller_info_proto_depIdxs,
		MessageInfos:      file_components_sync_protocol_get_updates_caller_info_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_get_updates_caller_info_proto = out.File
	file_components_sync_protocol_get_updates_caller_info_proto_goTypes = nil
	file_components_sync_protocol_get_updates_caller_info_proto_depIdxs = nil
}
