// Copyright 2022 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/note_entity.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoteEntity_TargetType int32

const (
	NoteEntity_TARGET_TYPE_UNSPECIFIED NoteEntity_TargetType = 0
	// Page target type makes the note global to the page. It does not associate
	// with any user selection.
	NoteEntity_TARGET_TYPE_PAGE NoteEntity_TargetType = 1
)

// Enum value maps for NoteEntity_TargetType.
var (
	NoteEntity_TargetType_name = map[int32]string{
		0: "TARGET_TYPE_UNSPECIFIED",
		1: "TARGET_TYPE_PAGE",
	}
	NoteEntity_TargetType_value = map[string]int32{
		"TARGET_TYPE_UNSPECIFIED": 0,
		"TARGET_TYPE_PAGE":        1,
	}
)

func (x NoteEntity_TargetType) Enum() *NoteEntity_TargetType {
	p := new(NoteEntity_TargetType)
	*p = x
	return p
}

func (x NoteEntity_TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NoteEntity_TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_components_sync_protocol_note_entity_proto_enumTypes[0].Descriptor()
}

func (NoteEntity_TargetType) Type() protoreflect.EnumType {
	return &file_components_sync_protocol_note_entity_proto_enumTypes[0]
}

func (x NoteEntity_TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *NoteEntity_TargetType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = NoteEntity_TargetType(num)
	return nil
}

// Deprecated: Use NoteEntity_TargetType.Descriptor instead.
func (NoteEntity_TargetType) EnumDescriptor() ([]byte, []int) {
	return file_components_sync_protocol_note_entity_proto_rawDescGZIP(), []int{0, 0}
}

type NoteEntity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plain text of the note.
	PlainText *string `protobuf:"bytes,1,opt,name=plain_text,json=plainText" json:"plain_text,omitempty"`
	// Rich text of the note. It will be used when plain_text is empty and the UI
	// supports rich text.
	RichText *string `protobuf:"bytes,2,opt,name=rich_text,json=richText" json:"rich_text,omitempty"`
	// required
	TargetType *NoteEntity_TargetType `protobuf:"varint,3,opt,name=target_type,json=targetType,enum=sync_pb.NoteEntity_TargetType" json:"target_type,omitempty"`
	// required
	CurrentNoteVersion *int32 `protobuf:"varint,4,opt,name=current_note_version,json=currentNoteVersion" json:"current_note_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NoteEntity) Reset() {
	*x = NoteEntity{}
	mi := &file_components_sync_protocol_note_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteEntity) ProtoMessage() {}

func (x *NoteEntity) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_note_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteEntity.ProtoReflect.Descriptor instead.
func (*NoteEntity) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_note_entity_proto_rawDescGZIP(), []int{0}
}

func (x *NoteEntity) GetPlainText() string {
	if x != nil && x.PlainText != nil {
		return *x.PlainText
	}
	return ""
}

func (x *NoteEntity) GetRichText() string {
	if x != nil && x.RichText != nil {
		return *x.RichText
	}
	return ""
}

func (x *NoteEntity) GetTargetType() NoteEntity_TargetType {
	if x != nil && x.TargetType != nil {
		return *x.TargetType
	}
	return NoteEntity_TARGET_TYPE_UNSPECIFIED
}

func (x *NoteEntity) GetCurrentNoteVersion() int32 {
	if x != nil && x.CurrentNoteVersion != nil {
		return *x.CurrentNoteVersion
	}
	return 0
}

var File_components_sync_protocol_note_entity_proto protoreflect.FileDescriptor

const file_components_sync_protocol_note_entity_proto_rawDesc = "" +
	"\n" +
	"*components/sync/protocol/note_entity.proto\x12\async_pb\"\xfc\x01\n" +
	"\n" +
	"NoteEntity\x12\x1d\n" +
	"\n" +
	"plain_text\x18\x01 \x01(\tR\tplainText\x12\x1b\n" +
	"\trich_text\x18\x02 \x01(\tR\brichText\x12?\n" +
	"\vtarget_type\x18\x03 \x01(\x0e2\x1e.sync_pb.NoteEntity.TargetTypeR\n" +
	"targetType\x120\n" +
	"\x14current_note_version\x18\x04 \x01(\x05R\x12currentNoteVersion\"?\n" +
	"\n" +
	"TargetType\x12\x1b\n" +
	"\x17TARGET_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TARGET_TYPE_PAGE\x10\x01B+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_note_entity_proto_rawDescOnce sync.Once
	file_components_sync_protocol_note_entity_proto_rawDescData []byte
)

func file_components_sync_protocol_note_entity_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_note_entity_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_note_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_note_entity_proto_rawDesc), len(file_components_sync_protocol_note_entity_proto_rawDesc)))
	})
	return file_components_sync_protocol_note_entity_proto_rawDescData
}

var file_components_sync_protocol_note_entity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_components_sync_protocol_note_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_components_sync_protocol_note_entity_proto_goTypes = []any{
	(NoteEntity_TargetType)(0), // 0: sync_pb.NoteEntity.TargetType
	(*NoteEntity)(nil),         // 1: sync_pb.NoteEntity
}
var file_components_sync_protocol_note_entity_proto_depIdxs = []int32{
	0, // 0: sync_pb.NoteEntity.target_type:type_name -> sync_pb.NoteEntity.TargetType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_note_entity_proto_init() }
func file_components_sync_protocol_note_entity_proto_init() {
	if File_components_sync_protocol_note_entity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_note_entity_proto_rawDesc), len(file_components_sync_protocol_note_entity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_note_entity_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_note_entity_proto_depIdxs,
		EnumInfos:         file_components_sync_protocol_note_entity_proto_enumTypes,
		MessageInfos:      file_components_sync_protocol_note_entity_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_note_entity_proto = out.File
	file_components_sync_protocol_note_entity_proto_goTypes = nil
	file_components_sync_protocol_note_entity_proto_depIdxs = nil
}
