// Copyright 2019 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// Sync protocol datatype extension for Chrome OS preferences.

// If you change or add any fields in this file, update proto_visitors.h and
// potentially proto_enum_conversions.{h, cc}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/os_preference_specifics.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Properties of a synced Chrome OS system preference. Uses PreferenceSpecifics
// instead of declaring name and value fields to allow more code sharing in the
// client (e.g. all PrefModelAssociators can operate on PreferenceSpecifics).
type OsPreferenceSpecifics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preference    *PreferenceSpecifics   `protobuf:"bytes,1,opt,name=preference" json:"preference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OsPreferenceSpecifics) Reset() {
	*x = OsPreferenceSpecifics{}
	mi := &file_components_sync_protocol_os_preference_specifics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OsPreferenceSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OsPreferenceSpecifics) ProtoMessage() {}

func (x *OsPreferenceSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_os_preference_specifics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OsPreferenceSpecifics.ProtoReflect.Descriptor instead.
func (*OsPreferenceSpecifics) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_os_preference_specifics_proto_rawDescGZIP(), []int{0}
}

func (x *OsPreferenceSpecifics) GetPreference() *PreferenceSpecifics {
	if x != nil {
		return x.Preference
	}
	return nil
}

var File_components_sync_protocol_os_preference_specifics_proto protoreflect.FileDescriptor

const file_components_sync_protocol_os_preference_specifics_proto_rawDesc = "" +
	"\n" +
	"6components/sync/protocol/os_preference_specifics.proto\x12\async_pb\x1a3components/sync/protocol/preference_specifics.proto\"U\n" +
	"\x15OsPreferenceSpecifics\x12<\n" +
	"\n" +
	"preference\x18\x01 \x01(\v2\x1c.sync_pb.PreferenceSpecificsR\n" +
	"preferenceB+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_os_preference_specifics_proto_rawDescOnce sync.Once
	file_components_sync_protocol_os_preference_specifics_proto_rawDescData []byte
)

func file_components_sync_protocol_os_preference_specifics_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_os_preference_specifics_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_os_preference_specifics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_os_preference_specifics_proto_rawDesc), len(file_components_sync_protocol_os_preference_specifics_proto_rawDesc)))
	})
	return file_components_sync_protocol_os_preference_specifics_proto_rawDescData
}

var file_components_sync_protocol_os_preference_specifics_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_components_sync_protocol_os_preference_specifics_proto_goTypes = []any{
	(*OsPreferenceSpecifics)(nil), // 0: sync_pb.OsPreferenceSpecifics
	(*PreferenceSpecifics)(nil),   // 1: sync_pb.PreferenceSpecifics
}
var file_components_sync_protocol_os_preference_specifics_proto_depIdxs = []int32{
	1, // 0: sync_pb.OsPreferenceSpecifics.preference:type_name -> sync_pb.PreferenceSpecifics
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_os_preference_specifics_proto_init() }
func file_components_sync_protocol_os_preference_specifics_proto_init() {
	if File_components_sync_protocol_os_preference_specifics_proto != nil {
		return
	}
	file_components_sync_protocol_preference_specifics_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_os_preference_specifics_proto_rawDesc), len(file_components_sync_protocol_os_preference_specifics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_os_preference_specifics_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_os_preference_specifics_proto_depIdxs,
		MessageInfos:      file_components_sync_protocol_os_preference_specifics_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_os_preference_specifics_proto = out.File
	file_components_sync_protocol_os_preference_specifics_proto_goTypes = nil
	file_components_sync_protocol_os_preference_specifics_proto_depIdxs = nil
}
