// Copyright 2016 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// Sync protocol datatype extension for the reading list items.

// If you change or add any fields in this file, update proto_visitors.h and
// potentially proto_enum_conversions.{h, cc}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/reading_list_specifics.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadingListSpecifics_ReadingListEntryStatus int32

const (
	ReadingListSpecifics_UNREAD ReadingListSpecifics_ReadingListEntryStatus = 0
	ReadingListSpecifics_READ   ReadingListSpecifics_ReadingListEntryStatus = 1
	ReadingListSpecifics_UNSEEN ReadingListSpecifics_ReadingListEntryStatus = 2
)

// Enum value maps for ReadingListSpecifics_ReadingListEntryStatus.
var (
	ReadingListSpecifics_ReadingListEntryStatus_name = map[int32]string{
		0: "UNREAD",
		1: "READ",
		2: "UNSEEN",
	}
	ReadingListSpecifics_ReadingListEntryStatus_value = map[string]int32{
		"UNREAD": 0,
		"READ":   1,
		"UNSEEN": 2,
	}
)

func (x ReadingListSpecifics_ReadingListEntryStatus) Enum() *ReadingListSpecifics_ReadingListEntryStatus {
	p := new(ReadingListSpecifics_ReadingListEntryStatus)
	*p = x
	return p
}

func (x ReadingListSpecifics_ReadingListEntryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadingListSpecifics_ReadingListEntryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_components_sync_protocol_reading_list_specifics_proto_enumTypes[0].Descriptor()
}

func (ReadingListSpecifics_ReadingListEntryStatus) Type() protoreflect.EnumType {
	return &file_components_sync_protocol_reading_list_specifics_proto_enumTypes[0]
}

func (x ReadingListSpecifics_ReadingListEntryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ReadingListSpecifics_ReadingListEntryStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ReadingListSpecifics_ReadingListEntryStatus(num)
	return nil
}

// Deprecated: Use ReadingListSpecifics_ReadingListEntryStatus.Descriptor instead.
func (ReadingListSpecifics_ReadingListEntryStatus) EnumDescriptor() ([]byte, []int) {
	return file_components_sync_protocol_reading_list_specifics_proto_rawDescGZIP(), []int{0, 0}
}

// Sync Reading list entry. This proto contains the fields synced for a reading
// list entry. It must be kept synced with the reading_list.ReadingListLocal
// protobuf.
type ReadingListSpecifics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entry_id and url must be equal.
	EntryId *string `protobuf:"bytes,1,opt,name=entry_id,json=entryId" json:"entry_id,omitempty"`
	Title   *string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Url     *string `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	// The timestamps are microseconds since the unix epoch.
	// TODO(crbug.com/353449026): Consider renaming the fields to use the
	// preferred naming scheme, i.e. `_unix_epoch_micros`.
	CreationTimeUs           *int64 `protobuf:"varint,4,opt,name=creation_time_us,json=creationTimeUs" json:"creation_time_us,omitempty"`
	UpdateTimeUs             *int64 `protobuf:"varint,5,opt,name=update_time_us,json=updateTimeUs" json:"update_time_us,omitempty"`
	FirstReadTimeUs          *int64 `protobuf:"varint,7,opt,name=first_read_time_us,json=firstReadTimeUs" json:"first_read_time_us,omitempty"`
	UpdateTitleTimeUs        *int64 `protobuf:"varint,8,opt,name=update_title_time_us,json=updateTitleTimeUs" json:"update_title_time_us,omitempty"`
	EstimatedReadTimeSeconds *int32 `protobuf:"varint,9,opt,name=estimated_read_time_seconds,json=estimatedReadTimeSeconds" json:"estimated_read_time_seconds,omitempty"`
	// If the field is not present, it defaults to UNSEEN.
	Status        *ReadingListSpecifics_ReadingListEntryStatus `protobuf:"varint,6,opt,name=status,enum=sync_pb.ReadingListSpecifics_ReadingListEntryStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadingListSpecifics) Reset() {
	*x = ReadingListSpecifics{}
	mi := &file_components_sync_protocol_reading_list_specifics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadingListSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadingListSpecifics) ProtoMessage() {}

func (x *ReadingListSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_reading_list_specifics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadingListSpecifics.ProtoReflect.Descriptor instead.
func (*ReadingListSpecifics) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_reading_list_specifics_proto_rawDescGZIP(), []int{0}
}

func (x *ReadingListSpecifics) GetEntryId() string {
	if x != nil && x.EntryId != nil {
		return *x.EntryId
	}
	return ""
}

func (x *ReadingListSpecifics) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *ReadingListSpecifics) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *ReadingListSpecifics) GetCreationTimeUs() int64 {
	if x != nil && x.CreationTimeUs != nil {
		return *x.CreationTimeUs
	}
	return 0
}

func (x *ReadingListSpecifics) GetUpdateTimeUs() int64 {
	if x != nil && x.UpdateTimeUs != nil {
		return *x.UpdateTimeUs
	}
	return 0
}

func (x *ReadingListSpecifics) GetFirstReadTimeUs() int64 {
	if x != nil && x.FirstReadTimeUs != nil {
		return *x.FirstReadTimeUs
	}
	return 0
}

func (x *ReadingListSpecifics) GetUpdateTitleTimeUs() int64 {
	if x != nil && x.UpdateTitleTimeUs != nil {
		return *x.UpdateTitleTimeUs
	}
	return 0
}

func (x *ReadingListSpecifics) GetEstimatedReadTimeSeconds() int32 {
	if x != nil && x.EstimatedReadTimeSeconds != nil {
		return *x.EstimatedReadTimeSeconds
	}
	return 0
}

func (x *ReadingListSpecifics) GetStatus() ReadingListSpecifics_ReadingListEntryStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ReadingListSpecifics_UNREAD
}

var File_components_sync_protocol_reading_list_specifics_proto protoreflect.FileDescriptor

const file_components_sync_protocol_reading_list_specifics_proto_rawDesc = "" +
	"\n" +
	"5components/sync/protocol/reading_list_specifics.proto\x12\async_pb\"\xd0\x03\n" +
	"\x14ReadingListSpecifics\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12(\n" +
	"\x10creation_time_us\x18\x04 \x01(\x03R\x0ecreationTimeUs\x12$\n" +
	"\x0eupdate_time_us\x18\x05 \x01(\x03R\fupdateTimeUs\x12+\n" +
	"\x12first_read_time_us\x18\a \x01(\x03R\x0ffirstReadTimeUs\x12/\n" +
	"\x14update_title_time_us\x18\b \x01(\x03R\x11updateTitleTimeUs\x12=\n" +
	"\x1bestimated_read_time_seconds\x18\t \x01(\x05R\x18estimatedReadTimeSeconds\x12L\n" +
	"\x06status\x18\x06 \x01(\x0e24.sync_pb.ReadingListSpecifics.ReadingListEntryStatusR\x06status\":\n" +
	"\x16ReadingListEntryStatus\x12\n" +
	"\n" +
	"\x06UNREAD\x10\x00\x12\b\n" +
	"\x04READ\x10\x01\x12\n" +
	"\n" +
	"\x06UNSEEN\x10\x02B+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_reading_list_specifics_proto_rawDescOnce sync.Once
	file_components_sync_protocol_reading_list_specifics_proto_rawDescData []byte
)

func file_components_sync_protocol_reading_list_specifics_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_reading_list_specifics_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_reading_list_specifics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_reading_list_specifics_proto_rawDesc), len(file_components_sync_protocol_reading_list_specifics_proto_rawDesc)))
	})
	return file_components_sync_protocol_reading_list_specifics_proto_rawDescData
}

var file_components_sync_protocol_reading_list_specifics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_components_sync_protocol_reading_list_specifics_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_components_sync_protocol_reading_list_specifics_proto_goTypes = []any{
	(ReadingListSpecifics_ReadingListEntryStatus)(0), // 0: sync_pb.ReadingListSpecifics.ReadingListEntryStatus
	(*ReadingListSpecifics)(nil),                     // 1: sync_pb.ReadingListSpecifics
}
var file_components_sync_protocol_reading_list_specifics_proto_depIdxs = []int32{
	0, // 0: sync_pb.ReadingListSpecifics.status:type_name -> sync_pb.ReadingListSpecifics.ReadingListEntryStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_reading_list_specifics_proto_init() }
func file_components_sync_protocol_reading_list_specifics_proto_init() {
	if File_components_sync_protocol_reading_list_specifics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_reading_list_specifics_proto_rawDesc), len(file_components_sync_protocol_reading_list_specifics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_reading_list_specifics_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_reading_list_specifics_proto_depIdxs,
		EnumInfos:         file_components_sync_protocol_reading_list_specifics_proto_enumTypes,
		MessageInfos:      file_components_sync_protocol_reading_list_specifics_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_reading_list_specifics_proto = out.File
	file_components_sync_protocol_reading_list_specifics_proto_goTypes = nil
	file_components_sync_protocol_reading_list_specifics_proto_depIdxs = nil
}
