// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// If you change or add any fields in this file, update proto_visitors.h and
// potentially proto_enum_conversions.{h, cc}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/skill_specifics.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LINT.IfChange(SkillSource)
type SkillSource int32

const (
	SkillSource_SKILL_SOURCE_UNKNOWN                  SkillSource = 0
	SkillSource_SKILL_SOURCE_FIRST_PARTY              SkillSource = 1
	SkillSource_SKILL_SOURCE_USER_CREATED             SkillSource = 2
	SkillSource_SKILL_SOURCE_DERIVED_FROM_FIRST_PARTY SkillSource = 3
)

// Enum value maps for SkillSource.
var (
	SkillSource_name = map[int32]string{
		0: "SKILL_SOURCE_UNKNOWN",
		1: "SKILL_SOURCE_FIRST_PARTY",
		2: "SKILL_SOURCE_USER_CREATED",
		3: "SKILL_SOURCE_DERIVED_FROM_FIRST_PARTY",
	}
	SkillSource_value = map[string]int32{
		"SKILL_SOURCE_UNKNOWN":                  0,
		"SKILL_SOURCE_FIRST_PARTY":              1,
		"SKILL_SOURCE_USER_CREATED":             2,
		"SKILL_SOURCE_DERIVED_FROM_FIRST_PARTY": 3,
	}
)

func (x SkillSource) Enum() *SkillSource {
	p := new(SkillSource)
	*p = x
	return p
}

func (x SkillSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SkillSource) Descriptor() protoreflect.EnumDescriptor {
	return file_components_sync_protocol_skill_specifics_proto_enumTypes[0].Descriptor()
}

func (SkillSource) Type() protoreflect.EnumType {
	return &file_components_sync_protocol_skill_specifics_proto_enumTypes[0]
}

func (x SkillSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SkillSource) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SkillSource(num)
	return nil
}

// Deprecated: Use SkillSource.Descriptor instead.
func (SkillSource) EnumDescriptor() ([]byte, []int) {
	return file_components_sync_protocol_skill_specifics_proto_rawDescGZIP(), []int{0}
}

// LINT.IfChange(SkillSpecifics)
// Skills stored by the user.
type SkillSpecifics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier for the skill.
	Guid *string `protobuf:"bytes,1,opt,name=guid" json:"guid,omitempty"`
	// The name of the skill.
	Name *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Emoji icon for the skill.
	Icon        *string      `protobuf:"bytes,3,opt,name=icon" json:"icon,omitempty"`
	SimpleSkill *SimpleSkill `protobuf:"bytes,4,opt,name=simple_skill,json=simpleSkill" json:"simple_skill,omitempty"`
	// The time the skill was created.
	CreationTimeWindowsEpochMicros *int64 `protobuf:"varint,5,opt,name=creation_time_windows_epoch_micros,json=creationTimeWindowsEpochMicros" json:"creation_time_windows_epoch_micros,omitempty"`
	// The time the skill was last updated.
	LastUpdateTimeWindowsEpochMicros *int64 `protobuf:"varint,6,opt,name=last_update_time_windows_epoch_micros,json=lastUpdateTimeWindowsEpochMicros" json:"last_update_time_windows_epoch_micros,omitempty"`
	// The schema version of the skill, useful for migrations.
	SchemaVersion *int32 `protobuf:"varint,7,opt,name=schema_version,json=schemaVersion" json:"schema_version,omitempty"`
	// The source of the skill.
	SkillSource *SkillSource `protobuf:"varint,8,opt,name=skill_source,json=skillSource,enum=sync_pb.SkillSource" json:"skill_source,omitempty"`
	// If set, the parent 1p skill that this skill is derived from. This field is
	// only present if the `skill_source` is
	// `SKILL_SOURCE_DERIVED_FROM_FIRST_PARTY`.
	SourceSkillId *string `protobuf:"bytes,9,opt,name=source_skill_id,json=sourceSkillId" json:"source_skill_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillSpecifics) Reset() {
	*x = SkillSpecifics{}
	mi := &file_components_sync_protocol_skill_specifics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillSpecifics) ProtoMessage() {}

func (x *SkillSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_skill_specifics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillSpecifics.ProtoReflect.Descriptor instead.
func (*SkillSpecifics) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_skill_specifics_proto_rawDescGZIP(), []int{0}
}

func (x *SkillSpecifics) GetGuid() string {
	if x != nil && x.Guid != nil {
		return *x.Guid
	}
	return ""
}

func (x *SkillSpecifics) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SkillSpecifics) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *SkillSpecifics) GetSimpleSkill() *SimpleSkill {
	if x != nil {
		return x.SimpleSkill
	}
	return nil
}

func (x *SkillSpecifics) GetCreationTimeWindowsEpochMicros() int64 {
	if x != nil && x.CreationTimeWindowsEpochMicros != nil {
		return *x.CreationTimeWindowsEpochMicros
	}
	return 0
}

func (x *SkillSpecifics) GetLastUpdateTimeWindowsEpochMicros() int64 {
	if x != nil && x.LastUpdateTimeWindowsEpochMicros != nil {
		return *x.LastUpdateTimeWindowsEpochMicros
	}
	return 0
}

func (x *SkillSpecifics) GetSchemaVersion() int32 {
	if x != nil && x.SchemaVersion != nil {
		return *x.SchemaVersion
	}
	return 0
}

func (x *SkillSpecifics) GetSkillSource() SkillSource {
	if x != nil && x.SkillSource != nil {
		return *x.SkillSource
	}
	return SkillSource_SKILL_SOURCE_UNKNOWN
}

func (x *SkillSpecifics) GetSourceSkillId() string {
	if x != nil && x.SourceSkillId != nil {
		return *x.SourceSkillId
	}
	return ""
}

// Represents a simple skill, primarily defined by a natural language prompt.
type SimpleSkill struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The core prompt text that instructs the model.
	Prompt *string `protobuf:"bytes,1,opt,name=prompt" json:"prompt,omitempty"`
	// The description of the skill.
	Description   *string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleSkill) Reset() {
	*x = SimpleSkill{}
	mi := &file_components_sync_protocol_skill_specifics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleSkill) ProtoMessage() {}

func (x *SimpleSkill) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_skill_specifics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleSkill.ProtoReflect.Descriptor instead.
func (*SimpleSkill) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_skill_specifics_proto_rawDescGZIP(), []int{1}
}

func (x *SimpleSkill) GetPrompt() string {
	if x != nil && x.Prompt != nil {
		return *x.Prompt
	}
	return ""
}

func (x *SimpleSkill) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

var File_components_sync_protocol_skill_specifics_proto protoreflect.FileDescriptor

const file_components_sync_protocol_skill_specifics_proto_rawDesc = "" +
	"\n" +
	".components/sync/protocol/skill_specifics.proto\x12\async_pb\"\xaa\x03\n" +
	"\x0eSkillSpecifics\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x127\n" +
	"\fsimple_skill\x18\x04 \x01(\v2\x14.sync_pb.SimpleSkillR\vsimpleSkill\x12J\n" +
	"\"creation_time_windows_epoch_micros\x18\x05 \x01(\x03R\x1ecreationTimeWindowsEpochMicros\x12O\n" +
	"%last_update_time_windows_epoch_micros\x18\x06 \x01(\x03R lastUpdateTimeWindowsEpochMicros\x12%\n" +
	"\x0eschema_version\x18\a \x01(\x05R\rschemaVersion\x127\n" +
	"\fskill_source\x18\b \x01(\x0e2\x14.sync_pb.SkillSourceR\vskillSource\x12&\n" +
	"\x0fsource_skill_id\x18\t \x01(\tR\rsourceSkillId\"G\n" +
	"\vSimpleSkill\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription*\x8f\x01\n" +
	"\vSkillSource\x12\x18\n" +
	"\x14SKILL_SOURCE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18SKILL_SOURCE_FIRST_PARTY\x10\x01\x12\x1d\n" +
	"\x19SKILL_SOURCE_USER_CREATED\x10\x02\x12)\n" +
	"%SKILL_SOURCE_DERIVED_FROM_FIRST_PARTY\x10\x03B+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_skill_specifics_proto_rawDescOnce sync.Once
	file_components_sync_protocol_skill_specifics_proto_rawDescData []byte
)

func file_components_sync_protocol_skill_specifics_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_skill_specifics_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_skill_specifics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_skill_specifics_proto_rawDesc), len(file_components_sync_protocol_skill_specifics_proto_rawDesc)))
	})
	return file_components_sync_protocol_skill_specifics_proto_rawDescData
}

var file_components_sync_protocol_skill_specifics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_components_sync_protocol_skill_specifics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_components_sync_protocol_skill_specifics_proto_goTypes = []any{
	(SkillSource)(0),       // 0: sync_pb.SkillSource
	(*SkillSpecifics)(nil), // 1: sync_pb.SkillSpecifics
	(*SimpleSkill)(nil),    // 2: sync_pb.SimpleSkill
}
var file_components_sync_protocol_skill_specifics_proto_depIdxs = []int32{
	2, // 0: sync_pb.SkillSpecifics.simple_skill:type_name -> sync_pb.SimpleSkill
	0, // 1: sync_pb.SkillSpecifics.skill_source:type_name -> sync_pb.SkillSource
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_skill_specifics_proto_init() }
func file_components_sync_protocol_skill_specifics_proto_init() {
	if File_components_sync_protocol_skill_specifics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_skill_specifics_proto_rawDesc), len(file_components_sync_protocol_skill_specifics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_skill_specifics_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_skill_specifics_proto_depIdxs,
		EnumInfos:         file_components_sync_protocol_skill_specifics_proto_enumTypes,
		MessageInfos:      file_components_sync_protocol_skill_specifics_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_skill_specifics_proto = out.File
	file_components_sync_protocol_skill_specifics_proto_goTypes = nil
	file_components_sync_protocol_skill_specifics_proto_depIdxs = nil
}
