// Copyright 2021 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/sync_entity.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncEntity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This item's identifier.  In a commit of a new item, this will be a
	// client-generated ID.  If the commit succeeds, the server will generate
	// a globally unique ID and return it to the committing client in the
	// CommitResponse.EntryResponse.  In the context of a GetUpdatesResponse,
	// `id_string` is always the server generated ID.  The original
	// client-generated ID is preserved in the `originator_client_id` field.
	// Present in both GetUpdatesResponse and CommitMessage.
	// Prior to M123, this field was empty for commit-only types.
	IdString *string `protobuf:"bytes,1,opt,name=id_string,json=idString" json:"id_string,omitempty"`
	// An id referencing this item's parent in the hierarchy.  In a
	// CommitMessage, it is accepted for this to be a client-generated temporary
	// ID if there was a new created item with that ID appearing earlier
	// in the message.  In all other situations, it is a server ID.
	// Present in both GetUpdatesResponse and CommitMessage.
	//
	// Starting with M99, this field is optional and used for legacy bookmarks
	// only:
	// 1. When processing GetUpdatesResponse, it is unused for modern data created
	//    or reuploaded by M94 or above, which populates the parent's GUID in
	//    BookmarkSpecifics (which is sufficient).
	// 2. When issuing CommitMessage, the field is populated for compatibility
	//    with clients before M99.
	ParentIdString *string `protobuf:"bytes,2,opt,name=parent_id_string,json=parentIdString" json:"parent_id_string,omitempty"`
	// The version of this item -- a monotonically increasing value that is
	// maintained by the server (or more precisely, the storage backend). It is
	// typically a timestamp, in microseconds since the Unix epoch, of the last
	// backend write. Present in both CommitMessage (set by the client) and
	// GetUpdatesResponse (set by the server), and there's also an equivalent
	// field in CommitResponse.
	//
	// In a CommitMessage, `version` is set to zero for newly-created items. For
	// updates to existing items, it is set by the client to the last version the
	// client knew about when sending the commit. If this version does not match
	// the latest version on the server, the commit *may* fail for that item with
	// a result code of CONFLICT. However, this is not guaranteed, and in
	// practice is not implemented for most data types.
	//
	// In a GetUpdatesResponse, `version` is always positive and identifies the
	// revision of the item stored in the server backend. If the returned version
	// is smaller than the version the client already knew, the client will ignore
	// the response.
	//
	// WARNING: This field used to be required before M60. Any client before this
	// will fail to deserialize if this field is missing.
	Version *int64 `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
	// Last modification time, in milliseconds since Unix epoch.
	// Present in both GetUpdatesResponse and CommitMessage.
	Mtime *int64 `protobuf:"varint,5,opt,name=mtime" json:"mtime,omitempty"`
	// Creation time, in milliseconds since Unix epoch.
	// Present in both GetUpdatesResponse and CommitMessage.
	Ctime *int64 `protobuf:"varint,6,opt,name=ctime" json:"ctime,omitempty"`
	// The name of this item.
	// Historical note:
	//   Since November 2010, this value is no different from non_unique_name.
	//   Before then, server implementations would maintain a unique-within-parent
	//   value separate from its base, "non-unique" value.  Clients had not
	//   depended on the uniqueness of the property since November 2009; it was
	//   removed from Chromium by http://codereview.chromium.org/371029 .
	// Present in both GetUpdatesResponse and CommitMessage.
	// WARNING: This field used to be required before M60. Any client before this
	// will fail to deserialize if this field is missing.
	Name *string `protobuf:"bytes,7,opt,name=name" json:"name,omitempty"`
	// The name of this item.  Same as `name`.
	// `non_unique_name` should take precedence over the `name` value if both
	// are supplied.  For efficiency, clients and servers should avoid setting
	// this redundant value.
	// Present in both GetUpdatesResponse and CommitMessage.
	NonUniqueName *string `protobuf:"bytes,8,opt,name=non_unique_name,json=nonUniqueName" json:"non_unique_name,omitempty"`
	// If present, this tag identifies this item as being a uniquely
	// instanced item.  The server ensures that there is never more
	// than one entity in a user's store with the same tag value.
	// This value is used to identify and find e.g. the "Bookmark Bar" folder
	// without relying on a particular ID or name.
	//
	// This variant of the tag is created by the server, so clients can't create
	// an item with a tag using this field.
	//
	// Use client_tag_hash if you want to create one from the client.
	//
	// An item can't have both a client_tag_hash and
	// a server_defined_unique_tag.
	//
	// Present only in GetUpdatesResponse.
	ServerDefinedUniqueTag *string `protobuf:"bytes,10,opt,name=server_defined_unique_tag,json=serverDefinedUniqueTag" json:"server_defined_unique_tag,omitempty"`
	// Ancient fields, predecessors for `unique_position`, deprecated with M26 and
	// still supported to deal with old incoming data. See field `unique_position`
	// for details as well as the data-upgrading implementation in
	// GetUniquePositionFromSyncEntity().
	//
	// Deprecated: Marked as deprecated in components/sync/protocol/sync_entity.proto.
	PositionInParent *int64 `protobuf:"varint,15,opt,name=position_in_parent,json=positionInParent" json:"position_in_parent,omitempty"`
	// Deprecated: Marked as deprecated in components/sync/protocol/sync_entity.proto.
	InsertAfterItemId *string `protobuf:"bytes,16,opt,name=insert_after_item_id,json=insertAfterItemId" json:"insert_after_item_id,omitempty"`
	// If true, indicates that this item has been (or should be) deleted.
	// Present in both GetUpdatesResponse and CommitMessage.
	Deleted *bool `protobuf:"varint,18,opt,name=deleted,def=0" json:"deleted,omitempty"`
	// A unique ID that identifies the the sync client who initially committed
	// this entity.  This value corresponds to `cache_guid` in CommitMessage.
	// This field, along with `originator_client_item_id`, can be used to
	// reunite the original with its official committed version in the case
	// where a client does not receive or process the commit response for
	// some reason.
	//
	// Present only in GetUpdatesResponse.
	//
	// This field is also used in determining the unique identifier used in
	// bookmarks' unique_position field.
	OriginatorCacheGuid *string `protobuf:"bytes,19,opt,name=originator_cache_guid,json=originatorCacheGuid" json:"originator_cache_guid,omitempty"`
	// Item ID as generated by the client that initially created this entity. Used
	// exclusively for bookmarks (other datatypes use client_tag_hash).
	// There are three generation of bookmarks that have populated this field
	// differently, depending on which version of the browser created the
	// bookmark:
	// 1. For bookmarks created before M44 (2015), the field got populated with an
	//    ID that is locally unique, but not globally unique (usually a negative
	//    number).
	// 2. For bookmarks created between M45 and M51, both inclusive, the field got
	//    populated with a globally unique GUID in uppercase form.
	// 3. For bookmarks created with M52 or above, the field gets populated with
	//    a globally unique GUID in lowercase form.
	//
	// Present only in GetUpdatesResponse.
	OriginatorClientItemId *string `protobuf:"bytes,20,opt,name=originator_client_item_id,json=originatorClientItemId" json:"originator_client_item_id,omitempty"`
	// Extensible container for datatype-specific data.
	// This became available in version 23 of the protocol.
	Specifics *EntitySpecifics `protobuf:"bytes,21,opt,name=specifics" json:"specifics,omitempty"`
	// Indicate whether this is a folder or not. Available in version 23+.
	Folder *bool `protobuf:"varint,22,opt,name=folder,def=0" json:"folder,omitempty"`
	// A client defined unique hash for this entity.
	// Analogous to server_defined_unique_tag, but allows the client to determine
	// an immutable attribute of the entity in hashed form that makes it unique
	// per user (i.e. at most one entity may exist per client tag hash).
	//
	// This value must be of the form base64(SHA1(client_tag)) where the
	// client_tag is a value derived from the contents of an entity in a
	// type-specific way. Since the hashed contents of the client_tag are exposed
	// to the server via this field, take care when defining it that there is
	// enough entropy to mask any secrets that the server shouldn't learn.
	//
	// The difference between server_defined_unique_tag and
	// client_tag_hash is the creator of the entity. Server defined
	// tags are entities created by the server at account creation,
	// while client defined tags are entities created by the client at any time.
	//
	// During GetUpdates, a sync entity update will come back with ONE of:
	// a) Originator item and cache id - for bookmarks created using old versions
	//    of the browser (latest M93, before https://crrev.com/c/2945119).
	// b) Server tag - If server committed the item as unique
	// c) Client tag - If client committed the item as unique
	//
	// May be present in CommitMessages for the initial creation of an entity.
	// If present in Commit updates for the entity, it will be ignored.
	//
	// May be returned in GetUpdatesMessage and sent up in CommitMessage.
	ClientTagHash *string `protobuf:"bytes,23,opt,name=client_tag_hash,json=clientTagHash" json:"client_tag_hash,omitempty"`
	// Introduced in M26, represents ordering among entities, in practice used for
	// bookmarks only. Clients should not assume it is always populated in
	// GetUpdatesMessage due to the following caveats:
	// 1. Tombstones and permanent folders do not populate it (ordering is
	//    irrelevant).
	// 2. It may remain unset by future versions of the client, as long as the
	//    field with the same name is populated inside BookmarkSpecifics. M94 and
	//    above populate both for backward compatibility reasons, but when support
	//    for M93 is retired, modern clients at the time may stop populating this
	//    field.
	// 3. Very old data (last committed by M25 or below, before the field was
	//    introduced) does not include this field, and in that case the legacy
	//    fields `position_in_parent` or `insert_after_item_id` must be honored
	//    instead.
	//
	// May be returned in GetUpdatesMessage and sent up in CommitMessage.
	UniquePosition *UniquePosition                   `protobuf:"bytes,25,opt,name=unique_position,json=uniquePosition" json:"unique_position,omitempty"`
	Collaboration  *SyncEntity_CollaborationMetadata `protobuf:"bytes,27,opt,name=collaboration" json:"collaboration,omitempty"`
	// Optionally present in CommitMessage for committed deletions (but may remain
	// unset if the origin is unspecified), it represents which piece of code
	// triggered a deletion. It is a debug-only field with no compatibility
	// guarantees, subject to change over time. The main purpose is to help with
	// investigating and mitigating user reports or incidents that cause data
	// deletion. Introduced in M126.
	DeletionOrigin *DeletionOrigin `protobuf:"bytes,28,opt,name=deletion_origin,json=deletionOrigin" json:"deletion_origin,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

// Default values for SyncEntity fields.
const (
	Default_SyncEntity_Deleted = bool(false)
	Default_SyncEntity_Folder  = bool(false)
)

func (x *SyncEntity) Reset() {
	*x = SyncEntity{}
	mi := &file_components_sync_protocol_sync_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEntity) ProtoMessage() {}

func (x *SyncEntity) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_sync_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEntity.ProtoReflect.Descriptor instead.
func (*SyncEntity) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_sync_entity_proto_rawDescGZIP(), []int{0}
}

func (x *SyncEntity) GetIdString() string {
	if x != nil && x.IdString != nil {
		return *x.IdString
	}
	return ""
}

func (x *SyncEntity) GetParentIdString() string {
	if x != nil && x.ParentIdString != nil {
		return *x.ParentIdString
	}
	return ""
}

func (x *SyncEntity) GetVersion() int64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *SyncEntity) GetMtime() int64 {
	if x != nil && x.Mtime != nil {
		return *x.Mtime
	}
	return 0
}

func (x *SyncEntity) GetCtime() int64 {
	if x != nil && x.Ctime != nil {
		return *x.Ctime
	}
	return 0
}

func (x *SyncEntity) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SyncEntity) GetNonUniqueName() string {
	if x != nil && x.NonUniqueName != nil {
		return *x.NonUniqueName
	}
	return ""
}

func (x *SyncEntity) GetServerDefinedUniqueTag() string {
	if x != nil && x.ServerDefinedUniqueTag != nil {
		return *x.ServerDefinedUniqueTag
	}
	return ""
}

// Deprecated: Marked as deprecated in components/sync/protocol/sync_entity.proto.
func (x *SyncEntity) GetPositionInParent() int64 {
	if x != nil && x.PositionInParent != nil {
		return *x.PositionInParent
	}
	return 0
}

// Deprecated: Marked as deprecated in components/sync/protocol/sync_entity.proto.
func (x *SyncEntity) GetInsertAfterItemId() string {
	if x != nil && x.InsertAfterItemId != nil {
		return *x.InsertAfterItemId
	}
	return ""
}

func (x *SyncEntity) GetDeleted() bool {
	if x != nil && x.Deleted != nil {
		return *x.Deleted
	}
	return Default_SyncEntity_Deleted
}

func (x *SyncEntity) GetOriginatorCacheGuid() string {
	if x != nil && x.OriginatorCacheGuid != nil {
		return *x.OriginatorCacheGuid
	}
	return ""
}

func (x *SyncEntity) GetOriginatorClientItemId() string {
	if x != nil && x.OriginatorClientItemId != nil {
		return *x.OriginatorClientItemId
	}
	return ""
}

func (x *SyncEntity) GetSpecifics() *EntitySpecifics {
	if x != nil {
		return x.Specifics
	}
	return nil
}

func (x *SyncEntity) GetFolder() bool {
	if x != nil && x.Folder != nil {
		return *x.Folder
	}
	return Default_SyncEntity_Folder
}

func (x *SyncEntity) GetClientTagHash() string {
	if x != nil && x.ClientTagHash != nil {
		return *x.ClientTagHash
	}
	return ""
}

func (x *SyncEntity) GetUniquePosition() *UniquePosition {
	if x != nil {
		return x.UniquePosition
	}
	return nil
}

func (x *SyncEntity) GetCollaboration() *SyncEntity_CollaborationMetadata {
	if x != nil {
		return x.Collaboration
	}
	return nil
}

func (x *SyncEntity) GetDeletionOrigin() *DeletionOrigin {
	if x != nil {
		return x.DeletionOrigin
	}
	return nil
}

// Metadata used for shared data types. Must not be present for regular data
// types.
// Introduced in M124.
type SyncEntity_CollaborationMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Collaboration ID which the current entity belongs to.
	CollaborationId *string `protobuf:"bytes,1,opt,name=collaboration_id,json=collaborationId" json:"collaboration_id,omitempty"`
	// Information about when the specifics was created.
	CreationAttribution *SyncEntity_CollaborationMetadata_Attribution `protobuf:"bytes,2,opt,name=creation_attribution,json=creationAttribution" json:"creation_attribution,omitempty"`
	// Information about when the specifics was last updated.
	LastUpdateAttribution *SyncEntity_CollaborationMetadata_Attribution           `protobuf:"bytes,3,opt,name=last_update_attribution,json=lastUpdateAttribution" json:"last_update_attribution,omitempty"`
	PerFieldAttributions  []*SyncEntity_CollaborationMetadata_PerFieldAttribution `protobuf:"bytes,4,rep,name=per_field_attributions,json=perFieldAttributions" json:"per_field_attributions,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SyncEntity_CollaborationMetadata) Reset() {
	*x = SyncEntity_CollaborationMetadata{}
	mi := &file_components_sync_protocol_sync_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEntity_CollaborationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEntity_CollaborationMetadata) ProtoMessage() {}

func (x *SyncEntity_CollaborationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_sync_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEntity_CollaborationMetadata.ProtoReflect.Descriptor instead.
func (*SyncEntity_CollaborationMetadata) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_sync_entity_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SyncEntity_CollaborationMetadata) GetCollaborationId() string {
	if x != nil && x.CollaborationId != nil {
		return *x.CollaborationId
	}
	return ""
}

func (x *SyncEntity_CollaborationMetadata) GetCreationAttribution() *SyncEntity_CollaborationMetadata_Attribution {
	if x != nil {
		return x.CreationAttribution
	}
	return nil
}

func (x *SyncEntity_CollaborationMetadata) GetLastUpdateAttribution() *SyncEntity_CollaborationMetadata_Attribution {
	if x != nil {
		return x.LastUpdateAttribution
	}
	return nil
}

func (x *SyncEntity_CollaborationMetadata) GetPerFieldAttributions() []*SyncEntity_CollaborationMetadata_PerFieldAttribution {
	if x != nil {
		return x.PerFieldAttributions
	}
	return nil
}

// Attribution metadata for this whole SyncEntity.
type SyncEntity_CollaborationMetadata_Attribution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Obfuscated Gaia ID of the user.
	ObfuscatedGaiaId *string `protobuf:"bytes,1,opt,name=obfuscated_gaia_id,json=obfuscatedGaiaId" json:"obfuscated_gaia_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncEntity_CollaborationMetadata_Attribution) Reset() {
	*x = SyncEntity_CollaborationMetadata_Attribution{}
	mi := &file_components_sync_protocol_sync_entity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEntity_CollaborationMetadata_Attribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEntity_CollaborationMetadata_Attribution) ProtoMessage() {}

func (x *SyncEntity_CollaborationMetadata_Attribution) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_sync_entity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEntity_CollaborationMetadata_Attribution.ProtoReflect.Descriptor instead.
func (*SyncEntity_CollaborationMetadata_Attribution) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_sync_entity_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *SyncEntity_CollaborationMetadata_Attribution) GetObfuscatedGaiaId() string {
	if x != nil && x.ObfuscatedGaiaId != nil {
		return *x.ObfuscatedGaiaId
	}
	return ""
}

// Per field attribution metadata (e.g, tab_group_color, tab_group_name.)
// Introduced in M141.
type SyncEntity_CollaborationMetadata_PerFieldAttribution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the attribution that uniquely identifies the changed field
	// (e.g. tab_group_title). These should have the same values as those
	// provided through the proto FieldOptions. See
	// `SharedTabGroupDataSpecifics` for examples.
	AttributionName *string `protobuf:"bytes,1,opt,name=attribution_name,json=attributionName" json:"attribution_name,omitempty"`
	// Obfuscated Gaia ID of the user that last modified this.
	LastUpdateObfuscatedGaiaId *string `protobuf:"bytes,2,opt,name=last_update_obfuscated_gaia_id,json=lastUpdateObfuscatedGaiaId" json:"last_update_obfuscated_gaia_id,omitempty"`
	// Last modification time of the specific attribution, in milliseconds
	// since Unix epoch.
	Mtime         *int64 `protobuf:"varint,3,opt,name=mtime" json:"mtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncEntity_CollaborationMetadata_PerFieldAttribution) Reset() {
	*x = SyncEntity_CollaborationMetadata_PerFieldAttribution{}
	mi := &file_components_sync_protocol_sync_entity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEntity_CollaborationMetadata_PerFieldAttribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEntity_CollaborationMetadata_PerFieldAttribution) ProtoMessage() {}

func (x *SyncEntity_CollaborationMetadata_PerFieldAttribution) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_sync_entity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEntity_CollaborationMetadata_PerFieldAttribution.ProtoReflect.Descriptor instead.
func (*SyncEntity_CollaborationMetadata_PerFieldAttribution) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_sync_entity_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *SyncEntity_CollaborationMetadata_PerFieldAttribution) GetAttributionName() string {
	if x != nil && x.AttributionName != nil {
		return *x.AttributionName
	}
	return ""
}

func (x *SyncEntity_CollaborationMetadata_PerFieldAttribution) GetLastUpdateObfuscatedGaiaId() string {
	if x != nil && x.LastUpdateObfuscatedGaiaId != nil {
		return *x.LastUpdateObfuscatedGaiaId
	}
	return ""
}

func (x *SyncEntity_CollaborationMetadata_PerFieldAttribution) GetMtime() int64 {
	if x != nil && x.Mtime != nil {
		return *x.Mtime
	}
	return 0
}

var File_components_sync_protocol_sync_entity_proto protoreflect.FileDescriptor

const file_components_sync_protocol_sync_entity_proto_rawDesc = "" +
	"\n" +
	"*components/sync/protocol/sync_entity.proto\x12\async_pb\x1a.components/sync/protocol/deletion_origin.proto\x1a/components/sync/protocol/entity_specifics.proto\x1a.components/sync/protocol/unique_position.proto\"\xae\r\n" +
	"\n" +
	"SyncEntity\x12\x1b\n" +
	"\tid_string\x18\x01 \x01(\tR\bidString\x12(\n" +
	"\x10parent_id_string\x18\x02 \x01(\tR\x0eparentIdString\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x14\n" +
	"\x05mtime\x18\x05 \x01(\x03R\x05mtime\x12\x14\n" +
	"\x05ctime\x18\x06 \x01(\x03R\x05ctime\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12&\n" +
	"\x0fnon_unique_name\x18\b \x01(\tR\rnonUniqueName\x129\n" +
	"\x19server_defined_unique_tag\x18\n" +
	" \x01(\tR\x16serverDefinedUniqueTag\x120\n" +
	"\x12position_in_parent\x18\x0f \x01(\x03B\x02\x18\x01R\x10positionInParent\x123\n" +
	"\x14insert_after_item_id\x18\x10 \x01(\tB\x02\x18\x01R\x11insertAfterItemId\x12\x1f\n" +
	"\adeleted\x18\x12 \x01(\b:\x05falseR\adeleted\x122\n" +
	"\x15originator_cache_guid\x18\x13 \x01(\tR\x13originatorCacheGuid\x129\n" +
	"\x19originator_client_item_id\x18\x14 \x01(\tR\x16originatorClientItemId\x126\n" +
	"\tspecifics\x18\x15 \x01(\v2\x18.sync_pb.EntitySpecificsR\tspecifics\x12\x1d\n" +
	"\x06folder\x18\x16 \x01(\b:\x05falseR\x06folder\x12&\n" +
	"\x0fclient_tag_hash\x18\x17 \x01(\tR\rclientTagHash\x12@\n" +
	"\x0funique_position\x18\x19 \x01(\v2\x17.sync_pb.UniquePositionR\x0euniquePosition\x12O\n" +
	"\rcollaboration\x18\x1b \x01(\v2).sync_pb.SyncEntity.CollaborationMetadataR\rcollaboration\x12@\n" +
	"\x0fdeletion_origin\x18\x1c \x01(\v2\x17.sync_pb.DeletionOriginR\x0edeletionOrigin\x1a\xea\x04\n" +
	"\x15CollaborationMetadata\x12)\n" +
	"\x10collaboration_id\x18\x01 \x01(\tR\x0fcollaborationId\x12h\n" +
	"\x14creation_attribution\x18\x02 \x01(\v25.sync_pb.SyncEntity.CollaborationMetadata.AttributionR\x13creationAttribution\x12m\n" +
	"\x17last_update_attribution\x18\x03 \x01(\v25.sync_pb.SyncEntity.CollaborationMetadata.AttributionR\x15lastUpdateAttribution\x12s\n" +
	"\x16per_field_attributions\x18\x04 \x03(\v2=.sync_pb.SyncEntity.CollaborationMetadata.PerFieldAttributionR\x14perFieldAttributions\x1a;\n" +
	"\vAttribution\x12,\n" +
	"\x12obfuscated_gaia_id\x18\x01 \x01(\tR\x10obfuscatedGaiaId\x1a\x9a\x01\n" +
	"\x13PerFieldAttribution\x12)\n" +
	"\x10attribution_name\x18\x01 \x01(\tR\x0fattributionName\x12B\n" +
	"\x1elast_update_obfuscated_gaia_id\x18\x02 \x01(\tR\x1alastUpdateObfuscatedGaiaId\x12\x14\n" +
	"\x05mtime\x18\x03 \x01(\x03R\x05mtimeJ\x04\b\x03\x10\x04J\x04\b\t\x10\n" +
	"J\x04\b\v\x10\fJ\x04\b\f\x10\rJ\x04\b\r\x10\x0eJ\x04\b\x0e\x10\x0fJ\x04\b\x11\x10\x12J\x04\b\x18\x10\x19J\x04\b\x1a\x10\x1bR\rold_parent_idR\x0esync_timestampR\fBookmarkDataR\x0fbookmark_folderR\fbookmark_urlR\x10bookmark_faviconR\x13extended_attributesR\x19client_defined_unique_tagR\x11ordinal_in_parentR\rattachment_idB+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_sync_entity_proto_rawDescOnce sync.Once
	file_components_sync_protocol_sync_entity_proto_rawDescData []byte
)

func file_components_sync_protocol_sync_entity_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_sync_entity_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_sync_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_sync_entity_proto_rawDesc), len(file_components_sync_protocol_sync_entity_proto_rawDesc)))
	})
	return file_components_sync_protocol_sync_entity_proto_rawDescData
}

var file_components_sync_protocol_sync_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_components_sync_protocol_sync_entity_proto_goTypes = []any{
	(*SyncEntity)(nil),                                           // 0: sync_pb.SyncEntity
	(*SyncEntity_CollaborationMetadata)(nil),                     // 1: sync_pb.SyncEntity.CollaborationMetadata
	(*SyncEntity_CollaborationMetadata_Attribution)(nil),         // 2: sync_pb.SyncEntity.CollaborationMetadata.Attribution
	(*SyncEntity_CollaborationMetadata_PerFieldAttribution)(nil), // 3: sync_pb.SyncEntity.CollaborationMetadata.PerFieldAttribution
	(*EntitySpecifics)(nil),                                      // 4: sync_pb.EntitySpecifics
	(*UniquePosition)(nil),                                       // 5: sync_pb.UniquePosition
	(*DeletionOrigin)(nil),                                       // 6: sync_pb.DeletionOrigin
}
var file_components_sync_protocol_sync_entity_proto_depIdxs = []int32{
	4, // 0: sync_pb.SyncEntity.specifics:type_name -> sync_pb.EntitySpecifics
	5, // 1: sync_pb.SyncEntity.unique_position:type_name -> sync_pb.UniquePosition
	1, // 2: sync_pb.SyncEntity.collaboration:type_name -> sync_pb.SyncEntity.CollaborationMetadata
	6, // 3: sync_pb.SyncEntity.deletion_origin:type_name -> sync_pb.DeletionOrigin
	2, // 4: sync_pb.SyncEntity.CollaborationMetadata.creation_attribution:type_name -> sync_pb.SyncEntity.CollaborationMetadata.Attribution
	2, // 5: sync_pb.SyncEntity.CollaborationMetadata.last_update_attribution:type_name -> sync_pb.SyncEntity.CollaborationMetadata.Attribution
	3, // 6: sync_pb.SyncEntity.CollaborationMetadata.per_field_attributions:type_name -> sync_pb.SyncEntity.CollaborationMetadata.PerFieldAttribution
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_sync_entity_proto_init() }
func file_components_sync_protocol_sync_entity_proto_init() {
	if File_components_sync_protocol_sync_entity_proto != nil {
		return
	}
	file_components_sync_protocol_deletion_origin_proto_init()
	file_components_sync_protocol_entity_specifics_proto_init()
	file_components_sync_protocol_unique_position_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_sync_entity_proto_rawDesc), len(file_components_sync_protocol_sync_entity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_sync_entity_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_sync_entity_proto_depIdxs,
		MessageInfos:      file_components_sync_protocol_sync_entity_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_sync_entity_proto = out.File
	file_components_sync_protocol_sync_entity_proto_goTypes = nil
	file_components_sync_protocol_sync_entity_proto_depIdxs = nil
}
