// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/sync_collaboration_attribution.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncCollaborationAttribution_AttributionType int32

const (
	// Default value. No attribution tracking for this field.
	SyncCollaborationAttribution_NONE SyncCollaborationAttribution_AttributionType = 0
	// Track the user who last modified this field.
	SyncCollaborationAttribution_LAST_MODIFIED_BY_USER SyncCollaborationAttribution_AttributionType = 1
)

// Enum value maps for SyncCollaborationAttribution_AttributionType.
var (
	SyncCollaborationAttribution_AttributionType_name = map[int32]string{
		0: "NONE",
		1: "LAST_MODIFIED_BY_USER",
	}
	SyncCollaborationAttribution_AttributionType_value = map[string]int32{
		"NONE":                  0,
		"LAST_MODIFIED_BY_USER": 1,
	}
)

func (x SyncCollaborationAttribution_AttributionType) Enum() *SyncCollaborationAttribution_AttributionType {
	p := new(SyncCollaborationAttribution_AttributionType)
	*p = x
	return p
}

func (x SyncCollaborationAttribution_AttributionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncCollaborationAttribution_AttributionType) Descriptor() protoreflect.EnumDescriptor {
	return file_components_sync_protocol_sync_collaboration_attribution_proto_enumTypes[0].Descriptor()
}

func (SyncCollaborationAttribution_AttributionType) Type() protoreflect.EnumType {
	return &file_components_sync_protocol_sync_collaboration_attribution_proto_enumTypes[0]
}

func (x SyncCollaborationAttribution_AttributionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SyncCollaborationAttribution_AttributionType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SyncCollaborationAttribution_AttributionType(num)
	return nil
}

// Deprecated: Use SyncCollaborationAttribution_AttributionType.Descriptor instead.
func (SyncCollaborationAttribution_AttributionType) EnumDescriptor() ([]byte, []int) {
	return file_components_sync_protocol_sync_collaboration_attribution_proto_rawDescGZIP(), []int{0, 0}
}

// Configuration for per-field attribution in collaborative Sync data types.
// Attaching this as an option to a field within a Sync entity's proto
// definition (e.g., in a SharedTab or SharedTabGroup) enables the tracking of
// metadata related to cross-user collaboration, such as which user last
// modified that specific field.
type SyncCollaborationAttribution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifies the type of attribution to be applied to the annotated field.
	AttributionType *SyncCollaborationAttribution_AttributionType `protobuf:"varint,1,opt,name=attribution_type,json=attributionType,enum=sync_pb.SyncCollaborationAttribution_AttributionType" json:"attribution_type,omitempty"`
	// A stable identifier for the annotated field, used to distinguish it from
	// other fields within the same Chrome Sync data type message that also
	// have attribution annotations. This identifier is used to associate
	// attribution information (like the last modifier) with this specific field
	// of the Sync Entity.
	//
	// This name is also used in the metadata of SyncEntity that are sent to
	// clients, such that the client code key to find the related attribution
	// data.
	//
	// Because of this, the name MUST be unique across all fields annotated with
	// `sync_collaboration_attribution` within a single EntitySpecifics. For
	// example, all `name` values within `SharedTabGroupData` must be distinct.
	//
	// Recommended format: `lower_snake_case`.
	// Examples: "tab_group_title", "tab_url", "tab_group_color".
	Name          *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncCollaborationAttribution) Reset() {
	*x = SyncCollaborationAttribution{}
	mi := &file_components_sync_protocol_sync_collaboration_attribution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCollaborationAttribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCollaborationAttribution) ProtoMessage() {}

func (x *SyncCollaborationAttribution) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_sync_collaboration_attribution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCollaborationAttribution.ProtoReflect.Descriptor instead.
func (*SyncCollaborationAttribution) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_sync_collaboration_attribution_proto_rawDescGZIP(), []int{0}
}

func (x *SyncCollaborationAttribution) GetAttributionType() SyncCollaborationAttribution_AttributionType {
	if x != nil && x.AttributionType != nil {
		return *x.AttributionType
	}
	return SyncCollaborationAttribution_NONE
}

func (x *SyncCollaborationAttribution) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var file_components_sync_protocol_sync_collaboration_attribution_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*SyncCollaborationAttribution)(nil),
		Field:         535801565,
		Name:          "sync_pb.sync_collaboration_attribution",
		Tag:           "bytes,535801565,opt,name=sync_collaboration_attribution",
		Filename:      "components/sync/protocol/sync_collaboration_attribution.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// IMPORTANT: the extension number needs to be declared. See
	// go/extension-declaration-reserved-numbers for more information.
	//
	// optional sync_pb.SyncCollaborationAttribution sync_collaboration_attribution = 535801565;
	E_SyncCollaborationAttribution = &file_components_sync_protocol_sync_collaboration_attribution_proto_extTypes[0]
)

var File_components_sync_protocol_sync_collaboration_attribution_proto protoreflect.FileDescriptor

const file_components_sync_protocol_sync_collaboration_attribution_proto_rawDesc = "" +
	"\n" +
	"=components/sync/protocol/sync_collaboration_attribution.proto\x12\async_pb\x1a google/protobuf/descriptor.proto\"\xcc\x01\n" +
	"\x1cSyncCollaborationAttribution\x12`\n" +
	"\x10attribution_type\x18\x01 \x01(\x0e25.sync_pb.SyncCollaborationAttribution.AttributionTypeR\x0fattributionType\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"6\n" +
	"\x0fAttributionType\x12\b\n" +
	"\x04NONE\x10\x00\x12\x19\n" +
	"\x15LAST_MODIFIED_BY_USER\x10\x01:\x8e\x01\n" +
	"\x1esync_collaboration_attribution\x12\x1d.google.protobuf.FieldOptions\x18\xddݾ\xff\x01 \x01(\v2%.sync_pb.SyncCollaborationAttributionR\x1csyncCollaborationAttributionB)\n" +
	"%org.chromium.components.sync.protocolP\x01"

var (
	file_components_sync_protocol_sync_collaboration_attribution_proto_rawDescOnce sync.Once
	file_components_sync_protocol_sync_collaboration_attribution_proto_rawDescData []byte
)

func file_components_sync_protocol_sync_collaboration_attribution_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_sync_collaboration_attribution_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_sync_collaboration_attribution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_sync_collaboration_attribution_proto_rawDesc), len(file_components_sync_protocol_sync_collaboration_attribution_proto_rawDesc)))
	})
	return file_components_sync_protocol_sync_collaboration_attribution_proto_rawDescData
}

var file_components_sync_protocol_sync_collaboration_attribution_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_components_sync_protocol_sync_collaboration_attribution_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_components_sync_protocol_sync_collaboration_attribution_proto_goTypes = []any{
	(SyncCollaborationAttribution_AttributionType)(0), // 0: sync_pb.SyncCollaborationAttribution.AttributionType
	(*SyncCollaborationAttribution)(nil),              // 1: sync_pb.SyncCollaborationAttribution
	(*descriptorpb.FieldOptions)(nil),                 // 2: google.protobuf.FieldOptions
}
var file_components_sync_protocol_sync_collaboration_attribution_proto_depIdxs = []int32{
	0, // 0: sync_pb.SyncCollaborationAttribution.attribution_type:type_name -> sync_pb.SyncCollaborationAttribution.AttributionType
	2, // 1: sync_pb.sync_collaboration_attribution:extendee -> google.protobuf.FieldOptions
	1, // 2: sync_pb.sync_collaboration_attribution:type_name -> sync_pb.SyncCollaborationAttribution
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_sync_collaboration_attribution_proto_init() }
func file_components_sync_protocol_sync_collaboration_attribution_proto_init() {
	if File_components_sync_protocol_sync_collaboration_attribution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_sync_collaboration_attribution_proto_rawDesc), len(file_components_sync_protocol_sync_collaboration_attribution_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_sync_collaboration_attribution_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_sync_collaboration_attribution_proto_depIdxs,
		EnumInfos:         file_components_sync_protocol_sync_collaboration_attribution_proto_enumTypes,
		MessageInfos:      file_components_sync_protocol_sync_collaboration_attribution_proto_msgTypes,
		ExtensionInfos:    file_components_sync_protocol_sync_collaboration_attribution_proto_extTypes,
	}.Build()
	File_components_sync_protocol_sync_collaboration_attribution_proto = out.File
	file_components_sync_protocol_sync_collaboration_attribution_proto_goTypes = nil
	file_components_sync_protocol_sync_collaboration_attribution_proto_depIdxs = nil
}
