// Copyright 2020 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// If you change or add any fields in this file, update proto_visitors.h and
// potentially proto_enum_conversions.{h, cc}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/sync_invalidations_payload.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The payload coming from the server for all invalidated data types.
type SyncInvalidationsPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field contains information about each data type which needs to be
	// updated. Note that it may contain data types which current client is not
	// interested in.
	DataTypeInvalidations []*SyncInvalidationsPayload_DataTypeInvalidation `protobuf:"bytes,1,rep,name=data_type_invalidations,json=dataTypeInvalidations" json:"data_type_invalidations,omitempty"`
	// Opaque field, which has to be provided as part of resulting GetUpdates
	// back to the server.
	Hint []byte `protobuf:"bytes,2,opt,name=hint" json:"hint,omitempty"`
	// Version of invalidation, used to order incoming invalidations.
	Version *int64 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	// The server-publish time of the invalidation, representing milliseconds
	// since the Unix epoch.
	ServerPublishTimeUnixEpochMillis *int64 `protobuf:"varint,4,opt,name=server_publish_time_unix_epoch_millis,json=serverPublishTimeUnixEpochMillis" json:"server_publish_time_unix_epoch_millis,omitempty"`
	// The server-dispatch time of the invalidation, representing milliseconds
	// since the Unix epoch (exactly when dispatched to FCM).
	ServerDispatchTimeUnixEpochMillis *int64 `protobuf:"varint,5,opt,name=server_dispatch_time_unix_epoch_millis,json=serverDispatchTimeUnixEpochMillis" json:"server_dispatch_time_unix_epoch_millis,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *SyncInvalidationsPayload) Reset() {
	*x = SyncInvalidationsPayload{}
	mi := &file_components_sync_protocol_sync_invalidations_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncInvalidationsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncInvalidationsPayload) ProtoMessage() {}

func (x *SyncInvalidationsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_sync_invalidations_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncInvalidationsPayload.ProtoReflect.Descriptor instead.
func (*SyncInvalidationsPayload) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_sync_invalidations_payload_proto_rawDescGZIP(), []int{0}
}

func (x *SyncInvalidationsPayload) GetDataTypeInvalidations() []*SyncInvalidationsPayload_DataTypeInvalidation {
	if x != nil {
		return x.DataTypeInvalidations
	}
	return nil
}

func (x *SyncInvalidationsPayload) GetHint() []byte {
	if x != nil {
		return x.Hint
	}
	return nil
}

func (x *SyncInvalidationsPayload) GetVersion() int64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *SyncInvalidationsPayload) GetServerPublishTimeUnixEpochMillis() int64 {
	if x != nil && x.ServerPublishTimeUnixEpochMillis != nil {
		return *x.ServerPublishTimeUnixEpochMillis
	}
	return 0
}

func (x *SyncInvalidationsPayload) GetServerDispatchTimeUnixEpochMillis() int64 {
	if x != nil && x.ServerDispatchTimeUnixEpochMillis != nil {
		return *x.ServerDispatchTimeUnixEpochMillis
	}
	return 0
}

type SyncInvalidationsPayload_DataTypeInvalidation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The legitimate values of this field correspond to the protobuf field
	// numbers of all EntitySpecifics fields supported by the server (see
	// components/sync/protocol/sync.proto).
	DataTypeId    *int32 `protobuf:"varint,1,opt,name=data_type_id,json=dataTypeId" json:"data_type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncInvalidationsPayload_DataTypeInvalidation) Reset() {
	*x = SyncInvalidationsPayload_DataTypeInvalidation{}
	mi := &file_components_sync_protocol_sync_invalidations_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncInvalidationsPayload_DataTypeInvalidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncInvalidationsPayload_DataTypeInvalidation) ProtoMessage() {}

func (x *SyncInvalidationsPayload_DataTypeInvalidation) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_sync_invalidations_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncInvalidationsPayload_DataTypeInvalidation.ProtoReflect.Descriptor instead.
func (*SyncInvalidationsPayload_DataTypeInvalidation) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_sync_invalidations_payload_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SyncInvalidationsPayload_DataTypeInvalidation) GetDataTypeId() int32 {
	if x != nil && x.DataTypeId != nil {
		return *x.DataTypeId
	}
	return 0
}

var File_components_sync_protocol_sync_invalidations_payload_proto protoreflect.FileDescriptor

const file_components_sync_protocol_sync_invalidations_payload_proto_rawDesc = "" +
	"\n" +
	"9components/sync/protocol/sync_invalidations_payload.proto\x12\async_pb\"\x96\x03\n" +
	"\x18SyncInvalidationsPayload\x12n\n" +
	"\x17data_type_invalidations\x18\x01 \x03(\v26.sync_pb.SyncInvalidationsPayload.DataTypeInvalidationR\x15dataTypeInvalidations\x12\x12\n" +
	"\x04hint\x18\x02 \x01(\fR\x04hint\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12O\n" +
	"%server_publish_time_unix_epoch_millis\x18\x04 \x01(\x03R serverPublishTimeUnixEpochMillis\x12Q\n" +
	"&server_dispatch_time_unix_epoch_millis\x18\x05 \x01(\x03R!serverDispatchTimeUnixEpochMillis\x1a8\n" +
	"\x14DataTypeInvalidation\x12 \n" +
	"\fdata_type_id\x18\x01 \x01(\x05R\n" +
	"dataTypeIdB+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_sync_invalidations_payload_proto_rawDescOnce sync.Once
	file_components_sync_protocol_sync_invalidations_payload_proto_rawDescData []byte
)

func file_components_sync_protocol_sync_invalidations_payload_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_sync_invalidations_payload_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_sync_invalidations_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_sync_invalidations_payload_proto_rawDesc), len(file_components_sync_protocol_sync_invalidations_payload_proto_rawDesc)))
	})
	return file_components_sync_protocol_sync_invalidations_payload_proto_rawDescData
}

var file_components_sync_protocol_sync_invalidations_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_components_sync_protocol_sync_invalidations_payload_proto_goTypes = []any{
	(*SyncInvalidationsPayload)(nil),                      // 0: sync_pb.SyncInvalidationsPayload
	(*SyncInvalidationsPayload_DataTypeInvalidation)(nil), // 1: sync_pb.SyncInvalidationsPayload.DataTypeInvalidation
}
var file_components_sync_protocol_sync_invalidations_payload_proto_depIdxs = []int32{
	1, // 0: sync_pb.SyncInvalidationsPayload.data_type_invalidations:type_name -> sync_pb.SyncInvalidationsPayload.DataTypeInvalidation
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_sync_invalidations_payload_proto_init() }
func file_components_sync_protocol_sync_invalidations_payload_proto_init() {
	if File_components_sync_protocol_sync_invalidations_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_sync_invalidations_payload_proto_rawDesc), len(file_components_sync_protocol_sync_invalidations_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_sync_invalidations_payload_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_sync_invalidations_payload_proto_depIdxs,
		MessageInfos:      file_components_sync_protocol_sync_invalidations_payload_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_sync_invalidations_payload_proto = out.File
	file_components_sync_protocol_sync_invalidations_payload_proto_goTypes = nil
	file_components_sync_protocol_sync_invalidations_payload_proto_depIdxs = nil
}
