// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// If you change or add any fields in this file, update proto_visitors.h and
// potentially proto_enum_conversions.{h, cc}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/tab_group_attribution_metadata.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stores information about the creation and modification of a tab group or tab.
type AttributionMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Information about when the specifics was created.
	// The cache guid should only be set on creation and not be edited if the
	// value is missing.
	Created *AttributionMetadata_Attribution `protobuf:"bytes,1,opt,name=created" json:"created,omitempty"`
	// Information about when the specifics was last updated.
	Updated       *AttributionMetadata_Attribution `protobuf:"bytes,2,opt,name=updated" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributionMetadata) Reset() {
	*x = AttributionMetadata{}
	mi := &file_components_sync_protocol_tab_group_attribution_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributionMetadata) ProtoMessage() {}

func (x *AttributionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_tab_group_attribution_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributionMetadata.ProtoReflect.Descriptor instead.
func (*AttributionMetadata) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_tab_group_attribution_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *AttributionMetadata) GetCreated() *AttributionMetadata_Attribution {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *AttributionMetadata) GetUpdated() *AttributionMetadata_Attribution {
	if x != nil {
		return x.Updated
	}
	return nil
}

// Details about a single attribution event (creation or modification).
type AttributionMetadata_Attribution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Information about the device.
	DeviceInfo    *AttributionMetadata_Attribution_AttributionDeviceInfo `protobuf:"bytes,1,opt,name=device_info,json=deviceInfo" json:"device_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributionMetadata_Attribution) Reset() {
	*x = AttributionMetadata_Attribution{}
	mi := &file_components_sync_protocol_tab_group_attribution_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributionMetadata_Attribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributionMetadata_Attribution) ProtoMessage() {}

func (x *AttributionMetadata_Attribution) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_tab_group_attribution_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributionMetadata_Attribution.ProtoReflect.Descriptor instead.
func (*AttributionMetadata_Attribution) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_tab_group_attribution_metadata_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AttributionMetadata_Attribution) GetDeviceInfo() *AttributionMetadata_Attribution_AttributionDeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

// Information about the device where the attribution event occurred.
type AttributionMetadata_Attribution_AttributionDeviceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier for the device in the sync system.
	CacheGuid     *string `protobuf:"bytes,1,opt,name=cache_guid,json=cacheGuid" json:"cache_guid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributionMetadata_Attribution_AttributionDeviceInfo) Reset() {
	*x = AttributionMetadata_Attribution_AttributionDeviceInfo{}
	mi := &file_components_sync_protocol_tab_group_attribution_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributionMetadata_Attribution_AttributionDeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributionMetadata_Attribution_AttributionDeviceInfo) ProtoMessage() {}

func (x *AttributionMetadata_Attribution_AttributionDeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_tab_group_attribution_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributionMetadata_Attribution_AttributionDeviceInfo.ProtoReflect.Descriptor instead.
func (*AttributionMetadata_Attribution_AttributionDeviceInfo) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_tab_group_attribution_metadata_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *AttributionMetadata_Attribution_AttributionDeviceInfo) GetCacheGuid() string {
	if x != nil && x.CacheGuid != nil {
		return *x.CacheGuid
	}
	return ""
}

var File_components_sync_protocol_tab_group_attribution_metadata_proto protoreflect.FileDescriptor

const file_components_sync_protocol_tab_group_attribution_metadata_proto_rawDesc = "" +
	"\n" +
	"=components/sync/protocol/tab_group_attribution_metadata.proto\x12\async_pb\"\xc6\x02\n" +
	"\x13AttributionMetadata\x12B\n" +
	"\acreated\x18\x01 \x01(\v2(.sync_pb.AttributionMetadata.AttributionR\acreated\x12B\n" +
	"\aupdated\x18\x02 \x01(\v2(.sync_pb.AttributionMetadata.AttributionR\aupdated\x1a\xa6\x01\n" +
	"\vAttribution\x12_\n" +
	"\vdevice_info\x18\x01 \x01(\v2>.sync_pb.AttributionMetadata.Attribution.AttributionDeviceInfoR\n" +
	"deviceInfo\x1a6\n" +
	"\x15AttributionDeviceInfo\x12\x1d\n" +
	"\n" +
	"cache_guid\x18\x01 \x01(\tR\tcacheGuidB+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_tab_group_attribution_metadata_proto_rawDescOnce sync.Once
	file_components_sync_protocol_tab_group_attribution_metadata_proto_rawDescData []byte
)

func file_components_sync_protocol_tab_group_attribution_metadata_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_tab_group_attribution_metadata_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_tab_group_attribution_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_tab_group_attribution_metadata_proto_rawDesc), len(file_components_sync_protocol_tab_group_attribution_metadata_proto_rawDesc)))
	})
	return file_components_sync_protocol_tab_group_attribution_metadata_proto_rawDescData
}

var file_components_sync_protocol_tab_group_attribution_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_components_sync_protocol_tab_group_attribution_metadata_proto_goTypes = []any{
	(*AttributionMetadata)(nil),                                   // 0: sync_pb.AttributionMetadata
	(*AttributionMetadata_Attribution)(nil),                       // 1: sync_pb.AttributionMetadata.Attribution
	(*AttributionMetadata_Attribution_AttributionDeviceInfo)(nil), // 2: sync_pb.AttributionMetadata.Attribution.AttributionDeviceInfo
}
var file_components_sync_protocol_tab_group_attribution_metadata_proto_depIdxs = []int32{
	1, // 0: sync_pb.AttributionMetadata.created:type_name -> sync_pb.AttributionMetadata.Attribution
	1, // 1: sync_pb.AttributionMetadata.updated:type_name -> sync_pb.AttributionMetadata.Attribution
	2, // 2: sync_pb.AttributionMetadata.Attribution.device_info:type_name -> sync_pb.AttributionMetadata.Attribution.AttributionDeviceInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_tab_group_attribution_metadata_proto_init() }
func file_components_sync_protocol_tab_group_attribution_metadata_proto_init() {
	if File_components_sync_protocol_tab_group_attribution_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_tab_group_attribution_metadata_proto_rawDesc), len(file_components_sync_protocol_tab_group_attribution_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_tab_group_attribution_metadata_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_tab_group_attribution_metadata_proto_depIdxs,
		MessageInfos:      file_components_sync_protocol_tab_group_attribution_metadata_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_tab_group_attribution_metadata_proto = out.File
	file_components_sync_protocol_tab_group_attribution_metadata_proto_goTypes = nil
	file_components_sync_protocol_tab_group_attribution_metadata_proto_depIdxs = nil
}
