// Copyright 2012 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// Sync protocol datatype extension for themes.

// If you change or add any fields in this file, update proto_visitors.h and
// potentially proto_enum_conversions.{h, cc}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/theme_specifics.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThemeSpecifics_BrowserColorScheme int32

const (
	ThemeSpecifics_BROWSER_COLOR_SCHEME_UNSPECIFIED ThemeSpecifics_BrowserColorScheme = 0
	ThemeSpecifics_SYSTEM                           ThemeSpecifics_BrowserColorScheme = 1
	ThemeSpecifics_LIGHT                            ThemeSpecifics_BrowserColorScheme = 2
	ThemeSpecifics_DARK                             ThemeSpecifics_BrowserColorScheme = 3
)

// Enum value maps for ThemeSpecifics_BrowserColorScheme.
var (
	ThemeSpecifics_BrowserColorScheme_name = map[int32]string{
		0: "BROWSER_COLOR_SCHEME_UNSPECIFIED",
		1: "SYSTEM",
		2: "LIGHT",
		3: "DARK",
	}
	ThemeSpecifics_BrowserColorScheme_value = map[string]int32{
		"BROWSER_COLOR_SCHEME_UNSPECIFIED": 0,
		"SYSTEM":                           1,
		"LIGHT":                            2,
		"DARK":                             3,
	}
)

func (x ThemeSpecifics_BrowserColorScheme) Enum() *ThemeSpecifics_BrowserColorScheme {
	p := new(ThemeSpecifics_BrowserColorScheme)
	*p = x
	return p
}

func (x ThemeSpecifics_BrowserColorScheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThemeSpecifics_BrowserColorScheme) Descriptor() protoreflect.EnumDescriptor {
	return file_components_sync_protocol_theme_specifics_proto_enumTypes[0].Descriptor()
}

func (ThemeSpecifics_BrowserColorScheme) Type() protoreflect.EnumType {
	return &file_components_sync_protocol_theme_specifics_proto_enumTypes[0]
}

func (x ThemeSpecifics_BrowserColorScheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ThemeSpecifics_BrowserColorScheme) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ThemeSpecifics_BrowserColorScheme(num)
	return nil
}

// Deprecated: Use ThemeSpecifics_BrowserColorScheme.Descriptor instead.
func (ThemeSpecifics_BrowserColorScheme) EnumDescriptor() ([]byte, []int) {
	return file_components_sync_protocol_theme_specifics_proto_rawDescGZIP(), []int{0, 0}
}

// Properties of theme sync objects.
type ThemeSpecifics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Set iff a theme extension exists, in which case, all custom_ fields should
	// be present. This is false for all other theme types (for example,
	// autogenerated or user color theme). If not set, all custom_* fields
	// should be omitted.
	UseCustomTheme *bool `protobuf:"varint,1,opt,name=use_custom_theme,json=useCustomTheme" json:"use_custom_theme,omitempty"`
	// This field is only relevant on platforms that have a distinction between
	// the system theme and the default theme, but other platforms must be careful
	// to pass through the value of this flag.
	//
	// If true, we use the system theme by default (i.e., when we don't use a
	// custom theme) for platforms that make a distinction between the default
	// theme and the system theme. Has no effect if use_custom_theme is true.
	UseSystemThemeByDefault *bool `protobuf:"varint,2,opt,name=use_system_theme_by_default,json=useSystemThemeByDefault" json:"use_system_theme_by_default,omitempty"`
	// Extension specific fields. Ignored unless `use_custom_theme` is true.
	CustomThemeName      *string `protobuf:"bytes,3,opt,name=custom_theme_name,json=customThemeName" json:"custom_theme_name,omitempty"`
	CustomThemeId        *string `protobuf:"bytes,4,opt,name=custom_theme_id,json=customThemeId" json:"custom_theme_id,omitempty"`
	CustomThemeUpdateUrl *string `protobuf:"bytes,5,opt,name=custom_theme_update_url,json=customThemeUpdateUrl" json:"custom_theme_update_url,omitempty"`
	// The browser-built color theme can be either be autogenerated,
	// user-selected, or grayscale.
	//
	// Types that are valid to be assigned to Color:
	//
	//	*ThemeSpecifics_AutogeneratedColorTheme_
	//	*ThemeSpecifics_UserColorTheme
	//	*ThemeSpecifics_GrayscaleThemeEnabled
	Color              isThemeSpecifics_Color             `protobuf_oneof:"color"`
	BrowserColorScheme *ThemeSpecifics_BrowserColorScheme `protobuf:"varint,9,opt,name=browser_color_scheme,json=browserColorScheme,enum=sync_pb.ThemeSpecifics_BrowserColorScheme" json:"browser_color_scheme,omitempty"`
	NtpBackground      *NtpCustomBackground               `protobuf:"bytes,10,opt,name=ntp_background,json=ntpBackground" json:"ntp_background,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ThemeSpecifics) Reset() {
	*x = ThemeSpecifics{}
	mi := &file_components_sync_protocol_theme_specifics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThemeSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThemeSpecifics) ProtoMessage() {}

func (x *ThemeSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_theme_specifics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThemeSpecifics.ProtoReflect.Descriptor instead.
func (*ThemeSpecifics) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_theme_specifics_proto_rawDescGZIP(), []int{0}
}

func (x *ThemeSpecifics) GetUseCustomTheme() bool {
	if x != nil && x.UseCustomTheme != nil {
		return *x.UseCustomTheme
	}
	return false
}

func (x *ThemeSpecifics) GetUseSystemThemeByDefault() bool {
	if x != nil && x.UseSystemThemeByDefault != nil {
		return *x.UseSystemThemeByDefault
	}
	return false
}

func (x *ThemeSpecifics) GetCustomThemeName() string {
	if x != nil && x.CustomThemeName != nil {
		return *x.CustomThemeName
	}
	return ""
}

func (x *ThemeSpecifics) GetCustomThemeId() string {
	if x != nil && x.CustomThemeId != nil {
		return *x.CustomThemeId
	}
	return ""
}

func (x *ThemeSpecifics) GetCustomThemeUpdateUrl() string {
	if x != nil && x.CustomThemeUpdateUrl != nil {
		return *x.CustomThemeUpdateUrl
	}
	return ""
}

func (x *ThemeSpecifics) GetColor() isThemeSpecifics_Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *ThemeSpecifics) GetAutogeneratedColorTheme() *ThemeSpecifics_AutogeneratedColorTheme {
	if x != nil {
		if x, ok := x.Color.(*ThemeSpecifics_AutogeneratedColorTheme_); ok {
			return x.AutogeneratedColorTheme
		}
	}
	return nil
}

func (x *ThemeSpecifics) GetUserColorTheme() *UserColorTheme {
	if x != nil {
		if x, ok := x.Color.(*ThemeSpecifics_UserColorTheme); ok {
			return x.UserColorTheme
		}
	}
	return nil
}

func (x *ThemeSpecifics) GetGrayscaleThemeEnabled() *ThemeSpecifics_Empty {
	if x != nil {
		if x, ok := x.Color.(*ThemeSpecifics_GrayscaleThemeEnabled); ok {
			return x.GrayscaleThemeEnabled
		}
	}
	return nil
}

func (x *ThemeSpecifics) GetBrowserColorScheme() ThemeSpecifics_BrowserColorScheme {
	if x != nil && x.BrowserColorScheme != nil {
		return *x.BrowserColorScheme
	}
	return ThemeSpecifics_BROWSER_COLOR_SCHEME_UNSPECIFIED
}

func (x *ThemeSpecifics) GetNtpBackground() *NtpCustomBackground {
	if x != nil {
		return x.NtpBackground
	}
	return nil
}

type isThemeSpecifics_Color interface {
	isThemeSpecifics_Color()
}

type ThemeSpecifics_AutogeneratedColorTheme_ struct {
	AutogeneratedColorTheme *ThemeSpecifics_AutogeneratedColorTheme `protobuf:"bytes,6,opt,name=autogenerated_color_theme,json=autogeneratedColorTheme,oneof"`
}

type ThemeSpecifics_UserColorTheme struct {
	UserColorTheme *UserColorTheme `protobuf:"bytes,7,opt,name=user_color_theme,json=userColorTheme,oneof"`
}

type ThemeSpecifics_GrayscaleThemeEnabled struct {
	GrayscaleThemeEnabled *ThemeSpecifics_Empty `protobuf:"bytes,8,opt,name=grayscale_theme_enabled,json=grayscaleThemeEnabled,oneof"`
}

func (*ThemeSpecifics_AutogeneratedColorTheme_) isThemeSpecifics_Color() {}

func (*ThemeSpecifics_UserColorTheme) isThemeSpecifics_Color() {}

func (*ThemeSpecifics_GrayscaleThemeEnabled) isThemeSpecifics_Color() {}

type ThemeSpecifics_AutogeneratedColorTheme struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SkColor used to autogenerate theme.
	Color         *uint32 `protobuf:"varint,1,opt,name=color" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThemeSpecifics_AutogeneratedColorTheme) Reset() {
	*x = ThemeSpecifics_AutogeneratedColorTheme{}
	mi := &file_components_sync_protocol_theme_specifics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThemeSpecifics_AutogeneratedColorTheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThemeSpecifics_AutogeneratedColorTheme) ProtoMessage() {}

func (x *ThemeSpecifics_AutogeneratedColorTheme) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_theme_specifics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThemeSpecifics_AutogeneratedColorTheme.ProtoReflect.Descriptor instead.
func (*ThemeSpecifics_AutogeneratedColorTheme) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_theme_specifics_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ThemeSpecifics_AutogeneratedColorTheme) GetColor() uint32 {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return 0
}

type ThemeSpecifics_Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThemeSpecifics_Empty) Reset() {
	*x = ThemeSpecifics_Empty{}
	mi := &file_components_sync_protocol_theme_specifics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThemeSpecifics_Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThemeSpecifics_Empty) ProtoMessage() {}

func (x *ThemeSpecifics_Empty) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_theme_specifics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThemeSpecifics_Empty.ProtoReflect.Descriptor instead.
func (*ThemeSpecifics_Empty) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_theme_specifics_proto_rawDescGZIP(), []int{0, 1}
}

var File_components_sync_protocol_theme_specifics_proto protoreflect.FileDescriptor

const file_components_sync_protocol_theme_specifics_proto_rawDesc = "" +
	"\n" +
	".components/sync/protocol/theme_specifics.proto\x12\async_pb\x1a*components/sync/protocol/theme_types.proto\"\xd3\x06\n" +
	"\x0eThemeSpecifics\x12(\n" +
	"\x10use_custom_theme\x18\x01 \x01(\bR\x0euseCustomTheme\x12<\n" +
	"\x1buse_system_theme_by_default\x18\x02 \x01(\bR\x17useSystemThemeByDefault\x12*\n" +
	"\x11custom_theme_name\x18\x03 \x01(\tR\x0fcustomThemeName\x12&\n" +
	"\x0fcustom_theme_id\x18\x04 \x01(\tR\rcustomThemeId\x125\n" +
	"\x17custom_theme_update_url\x18\x05 \x01(\tR\x14customThemeUpdateUrl\x12m\n" +
	"\x19autogenerated_color_theme\x18\x06 \x01(\v2/.sync_pb.ThemeSpecifics.AutogeneratedColorThemeH\x00R\x17autogeneratedColorTheme\x12C\n" +
	"\x10user_color_theme\x18\a \x01(\v2\x17.sync_pb.UserColorThemeH\x00R\x0euserColorTheme\x12W\n" +
	"\x17grayscale_theme_enabled\x18\b \x01(\v2\x1d.sync_pb.ThemeSpecifics.EmptyH\x00R\x15grayscaleThemeEnabled\x12\\\n" +
	"\x14browser_color_scheme\x18\t \x01(\x0e2*.sync_pb.ThemeSpecifics.BrowserColorSchemeR\x12browserColorScheme\x12C\n" +
	"\x0entp_background\x18\n" +
	" \x01(\v2\x1c.sync_pb.NtpCustomBackgroundR\rntpBackground\x1a/\n" +
	"\x17AutogeneratedColorTheme\x12\x14\n" +
	"\x05color\x18\x01 \x01(\rR\x05color\x1a\a\n" +
	"\x05Empty\"[\n" +
	"\x12BrowserColorScheme\x12$\n" +
	" BROWSER_COLOR_SCHEME_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x01\x12\t\n" +
	"\x05LIGHT\x10\x02\x12\b\n" +
	"\x04DARK\x10\x03B\a\n" +
	"\x05colorB+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_theme_specifics_proto_rawDescOnce sync.Once
	file_components_sync_protocol_theme_specifics_proto_rawDescData []byte
)

func file_components_sync_protocol_theme_specifics_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_theme_specifics_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_theme_specifics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_theme_specifics_proto_rawDesc), len(file_components_sync_protocol_theme_specifics_proto_rawDesc)))
	})
	return file_components_sync_protocol_theme_specifics_proto_rawDescData
}

var file_components_sync_protocol_theme_specifics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_components_sync_protocol_theme_specifics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_components_sync_protocol_theme_specifics_proto_goTypes = []any{
	(ThemeSpecifics_BrowserColorScheme)(0),         // 0: sync_pb.ThemeSpecifics.BrowserColorScheme
	(*ThemeSpecifics)(nil),                         // 1: sync_pb.ThemeSpecifics
	(*ThemeSpecifics_AutogeneratedColorTheme)(nil), // 2: sync_pb.ThemeSpecifics.AutogeneratedColorTheme
	(*ThemeSpecifics_Empty)(nil),                   // 3: sync_pb.ThemeSpecifics.Empty
	(*UserColorTheme)(nil),                         // 4: sync_pb.UserColorTheme
	(*NtpCustomBackground)(nil),                    // 5: sync_pb.NtpCustomBackground
}
var file_components_sync_protocol_theme_specifics_proto_depIdxs = []int32{
	2, // 0: sync_pb.ThemeSpecifics.autogenerated_color_theme:type_name -> sync_pb.ThemeSpecifics.AutogeneratedColorTheme
	4, // 1: sync_pb.ThemeSpecifics.user_color_theme:type_name -> sync_pb.UserColorTheme
	3, // 2: sync_pb.ThemeSpecifics.grayscale_theme_enabled:type_name -> sync_pb.ThemeSpecifics.Empty
	0, // 3: sync_pb.ThemeSpecifics.browser_color_scheme:type_name -> sync_pb.ThemeSpecifics.BrowserColorScheme
	5, // 4: sync_pb.ThemeSpecifics.ntp_background:type_name -> sync_pb.NtpCustomBackground
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_theme_specifics_proto_init() }
func file_components_sync_protocol_theme_specifics_proto_init() {
	if File_components_sync_protocol_theme_specifics_proto != nil {
		return
	}
	file_components_sync_protocol_theme_types_proto_init()
	file_components_sync_protocol_theme_specifics_proto_msgTypes[0].OneofWrappers = []any{
		(*ThemeSpecifics_AutogeneratedColorTheme_)(nil),
		(*ThemeSpecifics_UserColorTheme)(nil),
		(*ThemeSpecifics_GrayscaleThemeEnabled)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_theme_specifics_proto_rawDesc), len(file_components_sync_protocol_theme_specifics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_theme_specifics_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_theme_specifics_proto_depIdxs,
		EnumInfos:         file_components_sync_protocol_theme_specifics_proto_enumTypes,
		MessageInfos:      file_components_sync_protocol_theme_specifics_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_theme_specifics_proto = out.File
	file_components_sync_protocol_theme_specifics_proto_goTypes = nil
	file_components_sync_protocol_theme_specifics_proto_depIdxs = nil
}
