// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// Helper sync types for theme syncing.

// If you change or add any fields in this file, update proto_visitors.h and
// potentially proto_enum_conversions.{h, cc}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/theme_types.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserColorTheme_BrowserColorVariant int32

const (
	UserColorTheme_BROWSER_COLOR_VARIANT_UNSPECIFIED UserColorTheme_BrowserColorVariant = 0
	UserColorTheme_SYSTEM                            UserColorTheme_BrowserColorVariant = 1
	UserColorTheme_TONAL_SPOT                        UserColorTheme_BrowserColorVariant = 2
	UserColorTheme_NEUTRAL                           UserColorTheme_BrowserColorVariant = 3
	UserColorTheme_VIBRANT                           UserColorTheme_BrowserColorVariant = 4
	UserColorTheme_EXPRESSIVE                        UserColorTheme_BrowserColorVariant = 5
)

// Enum value maps for UserColorTheme_BrowserColorVariant.
var (
	UserColorTheme_BrowserColorVariant_name = map[int32]string{
		0: "BROWSER_COLOR_VARIANT_UNSPECIFIED",
		1: "SYSTEM",
		2: "TONAL_SPOT",
		3: "NEUTRAL",
		4: "VIBRANT",
		5: "EXPRESSIVE",
	}
	UserColorTheme_BrowserColorVariant_value = map[string]int32{
		"BROWSER_COLOR_VARIANT_UNSPECIFIED": 0,
		"SYSTEM":                            1,
		"TONAL_SPOT":                        2,
		"NEUTRAL":                           3,
		"VIBRANT":                           4,
		"EXPRESSIVE":                        5,
	}
)

func (x UserColorTheme_BrowserColorVariant) Enum() *UserColorTheme_BrowserColorVariant {
	p := new(UserColorTheme_BrowserColorVariant)
	*p = x
	return p
}

func (x UserColorTheme_BrowserColorVariant) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserColorTheme_BrowserColorVariant) Descriptor() protoreflect.EnumDescriptor {
	return file_components_sync_protocol_theme_types_proto_enumTypes[0].Descriptor()
}

func (UserColorTheme_BrowserColorVariant) Type() protoreflect.EnumType {
	return &file_components_sync_protocol_theme_types_proto_enumTypes[0]
}

func (x UserColorTheme_BrowserColorVariant) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *UserColorTheme_BrowserColorVariant) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = UserColorTheme_BrowserColorVariant(num)
	return nil
}

// Deprecated: Use UserColorTheme_BrowserColorVariant.Descriptor instead.
func (UserColorTheme_BrowserColorVariant) EnumDescriptor() ([]byte, []int) {
	return file_components_sync_protocol_theme_types_proto_rawDescGZIP(), []int{0, 0}
}

type UserColorTheme struct {
	state               protoimpl.MessageState              `protogen:"open.v1"`
	Color               *uint32                             `protobuf:"varint,1,opt,name=color" json:"color,omitempty"`
	BrowserColorVariant *UserColorTheme_BrowserColorVariant `protobuf:"varint,2,opt,name=browser_color_variant,json=browserColorVariant,enum=sync_pb.UserColorTheme_BrowserColorVariant" json:"browser_color_variant,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UserColorTheme) Reset() {
	*x = UserColorTheme{}
	mi := &file_components_sync_protocol_theme_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserColorTheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserColorTheme) ProtoMessage() {}

func (x *UserColorTheme) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_theme_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserColorTheme.ProtoReflect.Descriptor instead.
func (*UserColorTheme) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_theme_types_proto_rawDescGZIP(), []int{0}
}

func (x *UserColorTheme) GetColor() uint32 {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return 0
}

func (x *UserColorTheme) GetBrowserColorVariant() UserColorTheme_BrowserColorVariant {
	if x != nil && x.BrowserColorVariant != nil {
		return *x.BrowserColorVariant
	}
	return UserColorTheme_BROWSER_COLOR_VARIANT_UNSPECIFIED
}

// Custom NTP background info.
type NtpCustomBackground struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Background image url.
	Url *string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	// Attribution strings for the image.
	AttributionLine_1 *string `protobuf:"bytes,2,opt,name=attribution_line_1,json=attributionLine1" json:"attribution_line_1,omitempty"`
	AttributionLine_2 *string `protobuf:"bytes,3,opt,name=attribution_line_2,json=attributionLine2" json:"attribution_line_2,omitempty"`
	// Url to learn more info about the image.
	AttributionActionUrl *string `protobuf:"bytes,4,opt,name=attribution_action_url,json=attributionActionUrl" json:"attribution_action_url,omitempty"`
	// Id of the collection being used.
	CollectionId *string `protobuf:"bytes,5,opt,name=collection_id,json=collectionId" json:"collection_id,omitempty"`
	// Token to get the next image from collection and avoid duplicates.
	ResumeToken *string `protobuf:"bytes,6,opt,name=resume_token,json=resumeToken" json:"resume_token,omitempty"`
	// Timestamp after which the next image should be fetched from the
	// collection.
	RefreshTimestampUnixEpochSeconds *int64 `protobuf:"varint,7,opt,name=refresh_timestamp_unix_epoch_seconds,json=refreshTimestampUnixEpochSeconds" json:"refresh_timestamp_unix_epoch_seconds,omitempty"`
	// Main color of the image.
	MainColor     *uint32 `protobuf:"varint,8,opt,name=main_color,json=mainColor" json:"main_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NtpCustomBackground) Reset() {
	*x = NtpCustomBackground{}
	mi := &file_components_sync_protocol_theme_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NtpCustomBackground) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NtpCustomBackground) ProtoMessage() {}

func (x *NtpCustomBackground) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_theme_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NtpCustomBackground.ProtoReflect.Descriptor instead.
func (*NtpCustomBackground) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_theme_types_proto_rawDescGZIP(), []int{1}
}

func (x *NtpCustomBackground) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *NtpCustomBackground) GetAttributionLine_1() string {
	if x != nil && x.AttributionLine_1 != nil {
		return *x.AttributionLine_1
	}
	return ""
}

func (x *NtpCustomBackground) GetAttributionLine_2() string {
	if x != nil && x.AttributionLine_2 != nil {
		return *x.AttributionLine_2
	}
	return ""
}

func (x *NtpCustomBackground) GetAttributionActionUrl() string {
	if x != nil && x.AttributionActionUrl != nil {
		return *x.AttributionActionUrl
	}
	return ""
}

func (x *NtpCustomBackground) GetCollectionId() string {
	if x != nil && x.CollectionId != nil {
		return *x.CollectionId
	}
	return ""
}

func (x *NtpCustomBackground) GetResumeToken() string {
	if x != nil && x.ResumeToken != nil {
		return *x.ResumeToken
	}
	return ""
}

func (x *NtpCustomBackground) GetRefreshTimestampUnixEpochSeconds() int64 {
	if x != nil && x.RefreshTimestampUnixEpochSeconds != nil {
		return *x.RefreshTimestampUnixEpochSeconds
	}
	return 0
}

func (x *NtpCustomBackground) GetMainColor() uint32 {
	if x != nil && x.MainColor != nil {
		return *x.MainColor
	}
	return 0
}

var File_components_sync_protocol_theme_types_proto protoreflect.FileDescriptor

const file_components_sync_protocol_theme_types_proto_rawDesc = "" +
	"\n" +
	"*components/sync/protocol/theme_types.proto\x12\async_pb\"\x8c\x02\n" +
	"\x0eUserColorTheme\x12\x14\n" +
	"\x05color\x18\x01 \x01(\rR\x05color\x12_\n" +
	"\x15browser_color_variant\x18\x02 \x01(\x0e2+.sync_pb.UserColorTheme.BrowserColorVariantR\x13browserColorVariant\"\x82\x01\n" +
	"\x13BrowserColorVariant\x12%\n" +
	"!BROWSER_COLOR_VARIANT_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x01\x12\x0e\n" +
	"\n" +
	"TONAL_SPOT\x10\x02\x12\v\n" +
	"\aNEUTRAL\x10\x03\x12\v\n" +
	"\aVIBRANT\x10\x04\x12\x0e\n" +
	"\n" +
	"EXPRESSIVE\x10\x05\"\xf0\x02\n" +
	"\x13NtpCustomBackground\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12,\n" +
	"\x12attribution_line_1\x18\x02 \x01(\tR\x10attributionLine1\x12,\n" +
	"\x12attribution_line_2\x18\x03 \x01(\tR\x10attributionLine2\x124\n" +
	"\x16attribution_action_url\x18\x04 \x01(\tR\x14attributionActionUrl\x12#\n" +
	"\rcollection_id\x18\x05 \x01(\tR\fcollectionId\x12!\n" +
	"\fresume_token\x18\x06 \x01(\tR\vresumeToken\x12N\n" +
	"$refresh_timestamp_unix_epoch_seconds\x18\a \x01(\x03R refreshTimestampUnixEpochSeconds\x12\x1d\n" +
	"\n" +
	"main_color\x18\b \x01(\rR\tmainColorB+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_theme_types_proto_rawDescOnce sync.Once
	file_components_sync_protocol_theme_types_proto_rawDescData []byte
)

func file_components_sync_protocol_theme_types_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_theme_types_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_theme_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_theme_types_proto_rawDesc), len(file_components_sync_protocol_theme_types_proto_rawDesc)))
	})
	return file_components_sync_protocol_theme_types_proto_rawDescData
}

var file_components_sync_protocol_theme_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_components_sync_protocol_theme_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_components_sync_protocol_theme_types_proto_goTypes = []any{
	(UserColorTheme_BrowserColorVariant)(0), // 0: sync_pb.UserColorTheme.BrowserColorVariant
	(*UserColorTheme)(nil),                  // 1: sync_pb.UserColorTheme
	(*NtpCustomBackground)(nil),             // 2: sync_pb.NtpCustomBackground
}
var file_components_sync_protocol_theme_types_proto_depIdxs = []int32{
	0, // 0: sync_pb.UserColorTheme.browser_color_variant:type_name -> sync_pb.UserColorTheme.BrowserColorVariant
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_theme_types_proto_init() }
func file_components_sync_protocol_theme_types_proto_init() {
	if File_components_sync_protocol_theme_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_theme_types_proto_rawDesc), len(file_components_sync_protocol_theme_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_theme_types_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_theme_types_proto_depIdxs,
		EnumInfos:         file_components_sync_protocol_theme_types_proto_enumTypes,
		MessageInfos:      file_components_sync_protocol_theme_types_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_theme_types_proto = out.File
	file_components_sync_protocol_theme_types_proto_goTypes = nil
	file_components_sync_protocol_theme_types_proto_depIdxs = nil
}
