// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// Sync protocol datatype extension for themes on Android.

// If you change or add any fields in this file, update proto_visitors.h and
// potentially proto_enum_conversions.{h, cc}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/theme_android_specifics.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Properties of theme sync objects for Android themes.
type ThemeAndroidSpecifics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the user has a custom theme.
	UseCustomTheme *bool `protobuf:"varint,1,opt,name=use_custom_theme,json=useCustomTheme" json:"use_custom_theme,omitempty"`
	// Info about the custom background (URL, collection ID, etc.).
	NtpBackground *NtpCustomBackground `protobuf:"bytes,2,opt,name=ntp_background,json=ntpBackground" json:"ntp_background,omitempty"`
	// The selected Chrome color.
	// Note: `user_color_theme` and `chrome_color_info` refer to the same color
	// theme and exist to allow cross-platform compatibility.
	UserColorTheme  *UserColorTheme  `protobuf:"bytes,3,opt,name=user_color_theme,json=userColorTheme" json:"user_color_theme,omitempty"`
	ChromeColorInfo *ChromeColorInfo `protobuf:"bytes,4,opt,name=chrome_color_info,json=chromeColorInfo" json:"chrome_color_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ThemeAndroidSpecifics) Reset() {
	*x = ThemeAndroidSpecifics{}
	mi := &file_components_sync_protocol_theme_android_specifics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThemeAndroidSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThemeAndroidSpecifics) ProtoMessage() {}

func (x *ThemeAndroidSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_theme_android_specifics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThemeAndroidSpecifics.ProtoReflect.Descriptor instead.
func (*ThemeAndroidSpecifics) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_theme_android_specifics_proto_rawDescGZIP(), []int{0}
}

func (x *ThemeAndroidSpecifics) GetUseCustomTheme() bool {
	if x != nil && x.UseCustomTheme != nil {
		return *x.UseCustomTheme
	}
	return false
}

func (x *ThemeAndroidSpecifics) GetNtpBackground() *NtpCustomBackground {
	if x != nil {
		return x.NtpBackground
	}
	return nil
}

func (x *ThemeAndroidSpecifics) GetUserColorTheme() *UserColorTheme {
	if x != nil {
		return x.UserColorTheme
	}
	return nil
}

func (x *ThemeAndroidSpecifics) GetChromeColorInfo() *ChromeColorInfo {
	if x != nil {
		return x.ChromeColorInfo
	}
	return nil
}

// Information regarding the selected Chrome color on Android devices.
// It is only used for sync between clank devices.
type ChromeColorInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The selected Chrome color ID.
	ThemeColorId *int32 `protobuf:"varint,1,opt,name=theme_color_id,json=themeColorId" json:"theme_color_id,omitempty"`
	// The timestamp when the Chrome color was refreshed as part of the daily
	// cycle.
	LastDailyUpdateTimestampUnixEpochMillis *int64 `protobuf:"varint,2,opt,name=last_daily_update_timestamp_unix_epoch_millis,json=lastDailyUpdateTimestampUnixEpochMillis" json:"last_daily_update_timestamp_unix_epoch_millis,omitempty"`
	unknownFields                           protoimpl.UnknownFields
	sizeCache                               protoimpl.SizeCache
}

func (x *ChromeColorInfo) Reset() {
	*x = ChromeColorInfo{}
	mi := &file_components_sync_protocol_theme_android_specifics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChromeColorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChromeColorInfo) ProtoMessage() {}

func (x *ChromeColorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_theme_android_specifics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChromeColorInfo.ProtoReflect.Descriptor instead.
func (*ChromeColorInfo) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_theme_android_specifics_proto_rawDescGZIP(), []int{1}
}

func (x *ChromeColorInfo) GetThemeColorId() int32 {
	if x != nil && x.ThemeColorId != nil {
		return *x.ThemeColorId
	}
	return 0
}

func (x *ChromeColorInfo) GetLastDailyUpdateTimestampUnixEpochMillis() int64 {
	if x != nil && x.LastDailyUpdateTimestampUnixEpochMillis != nil {
		return *x.LastDailyUpdateTimestampUnixEpochMillis
	}
	return 0
}

var File_components_sync_protocol_theme_android_specifics_proto protoreflect.FileDescriptor

const file_components_sync_protocol_theme_android_specifics_proto_rawDesc = "" +
	"\n" +
	"6components/sync/protocol/theme_android_specifics.proto\x12\async_pb\x1a*components/sync/protocol/theme_types.proto\"\x8f\x02\n" +
	"\x15ThemeAndroidSpecifics\x12(\n" +
	"\x10use_custom_theme\x18\x01 \x01(\bR\x0euseCustomTheme\x12C\n" +
	"\x0entp_background\x18\x02 \x01(\v2\x1c.sync_pb.NtpCustomBackgroundR\rntpBackground\x12A\n" +
	"\x10user_color_theme\x18\x03 \x01(\v2\x17.sync_pb.UserColorThemeR\x0euserColorTheme\x12D\n" +
	"\x11chrome_color_info\x18\x04 \x01(\v2\x18.sync_pb.ChromeColorInfoR\x0fchromeColorInfo\"\x97\x01\n" +
	"\x0fChromeColorInfo\x12$\n" +
	"\x0etheme_color_id\x18\x01 \x01(\x05R\fthemeColorId\x12^\n" +
	"-last_daily_update_timestamp_unix_epoch_millis\x18\x02 \x01(\x03R'lastDailyUpdateTimestampUnixEpochMillisB+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_theme_android_specifics_proto_rawDescOnce sync.Once
	file_components_sync_protocol_theme_android_specifics_proto_rawDescData []byte
)

func file_components_sync_protocol_theme_android_specifics_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_theme_android_specifics_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_theme_android_specifics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_theme_android_specifics_proto_rawDesc), len(file_components_sync_protocol_theme_android_specifics_proto_rawDesc)))
	})
	return file_components_sync_protocol_theme_android_specifics_proto_rawDescData
}

var file_components_sync_protocol_theme_android_specifics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_components_sync_protocol_theme_android_specifics_proto_goTypes = []any{
	(*ThemeAndroidSpecifics)(nil), // 0: sync_pb.ThemeAndroidSpecifics
	(*ChromeColorInfo)(nil),       // 1: sync_pb.ChromeColorInfo
	(*NtpCustomBackground)(nil),   // 2: sync_pb.NtpCustomBackground
	(*UserColorTheme)(nil),        // 3: sync_pb.UserColorTheme
}
var file_components_sync_protocol_theme_android_specifics_proto_depIdxs = []int32{
	2, // 0: sync_pb.ThemeAndroidSpecifics.ntp_background:type_name -> sync_pb.NtpCustomBackground
	3, // 1: sync_pb.ThemeAndroidSpecifics.user_color_theme:type_name -> sync_pb.UserColorTheme
	1, // 2: sync_pb.ThemeAndroidSpecifics.chrome_color_info:type_name -> sync_pb.ChromeColorInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_theme_android_specifics_proto_init() }
func file_components_sync_protocol_theme_android_specifics_proto_init() {
	if File_components_sync_protocol_theme_android_specifics_proto != nil {
		return
	}
	file_components_sync_protocol_theme_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_theme_android_specifics_proto_rawDesc), len(file_components_sync_protocol_theme_android_specifics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_theme_android_specifics_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_theme_android_specifics_proto_depIdxs,
		MessageInfos:      file_components_sync_protocol_theme_android_specifics_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_theme_android_specifics_proto = out.File
	file_components_sync_protocol_theme_android_specifics_proto_goTypes = nil
	file_components_sync_protocol_theme_android_specifics_proto_depIdxs = nil
}
