// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/unencrypted_sharing_message.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message for sending between devices in Sharing. Messages defined here should
// be set to the unencrypted_payload field of SharingMessageSpecifics.
type UnencryptedSharingMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of sender.
	SenderGuid *string `protobuf:"bytes,1,opt,name=sender_guid,json=senderGuid" json:"sender_guid,omitempty"`
	// Payload of the message, contains one of the messages below.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*UnencryptedSharingMessage_SendTabMessage
	//	*UnencryptedSharingMessage_DesktopToMobilePromoMessage
	Payload isUnencryptedSharingMessage_Payload `protobuf_oneof:"payload"`
	// The name of the device sending this message.
	SenderDeviceName *string `protobuf:"bytes,3,opt,name=sender_device_name,json=senderDeviceName" json:"sender_device_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UnencryptedSharingMessage) Reset() {
	*x = UnencryptedSharingMessage{}
	mi := &file_components_sync_protocol_unencrypted_sharing_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnencryptedSharingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnencryptedSharingMessage) ProtoMessage() {}

func (x *UnencryptedSharingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_unencrypted_sharing_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnencryptedSharingMessage.ProtoReflect.Descriptor instead.
func (*UnencryptedSharingMessage) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_unencrypted_sharing_message_proto_rawDescGZIP(), []int{0}
}

func (x *UnencryptedSharingMessage) GetSenderGuid() string {
	if x != nil && x.SenderGuid != nil {
		return *x.SenderGuid
	}
	return ""
}

func (x *UnencryptedSharingMessage) GetPayload() isUnencryptedSharingMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UnencryptedSharingMessage) GetSendTabMessage() *SendTabToSelfPush {
	if x != nil {
		if x, ok := x.Payload.(*UnencryptedSharingMessage_SendTabMessage); ok {
			return x.SendTabMessage
		}
	}
	return nil
}

func (x *UnencryptedSharingMessage) GetDesktopToMobilePromoMessage() *DesktopToMobilePromoMessage {
	if x != nil {
		if x, ok := x.Payload.(*UnencryptedSharingMessage_DesktopToMobilePromoMessage); ok {
			return x.DesktopToMobilePromoMessage
		}
	}
	return nil
}

func (x *UnencryptedSharingMessage) GetSenderDeviceName() string {
	if x != nil && x.SenderDeviceName != nil {
		return *x.SenderDeviceName
	}
	return ""
}

type isUnencryptedSharingMessage_Payload interface {
	isUnencryptedSharingMessage_Payload()
}

type UnencryptedSharingMessage_SendTabMessage struct {
	SendTabMessage *SendTabToSelfPush `protobuf:"bytes,2,opt,name=send_tab_message,json=sendTabMessage,oneof"`
}

type UnencryptedSharingMessage_DesktopToMobilePromoMessage struct {
	DesktopToMobilePromoMessage *DesktopToMobilePromoMessage `protobuf:"bytes,4,opt,name=desktop_to_mobile_promo_message,json=desktopToMobilePromoMessage,oneof"`
}

func (*UnencryptedSharingMessage_SendTabMessage) isUnencryptedSharingMessage_Payload() {}

func (*UnencryptedSharingMessage_DesktopToMobilePromoMessage) isUnencryptedSharingMessage_Payload() {}

// Generic push notification message.
type PushNotificationMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Notification title text to display.
	Title *string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	// Required. Actual body text to display.
	Text *string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	// Optional. An icon to be displayed alongside the notification, or a series
	// of icons to be put in a collage. If no icon is specified, the frontend
	// will display a generic icon image.
	Icon []*PushNotificationMessage_Image `protobuf:"bytes,3,rep,name=icon" json:"icon,omitempty"`
	// Optional. A small app icon to display in certain notification views. This
	// field can be omitted in favor of using a favicon specified in the
	// chrome_chime client config. If this field is omitted and the client config
	// favicon is unspecified, no icon is displayed.
	Favicon *PushNotificationMessage_Image `protobuf:"bytes,4,opt,name=favicon" json:"favicon,omitempty"`
	// Required. A URL that will be visited when clicking on this notification.
	DestinationUrl *string `protobuf:"bytes,5,opt,name=destination_url,json=destinationUrl" json:"destination_url,omitempty"`
	// Placeholder title. Will be used if payload is not properly assembled on
	// receiving device. Will not get encrypted by Chime.
	PlaceholderTitle *string `protobuf:"bytes,6,opt,name=placeholder_title,json=placeholderTitle" json:"placeholder_title,omitempty"`
	// Placeholder body. Will be used if payload is not properly assembled on
	// receiving device. Will not get encrypted by Chime.
	PlaceholderBody *string `protobuf:"bytes,7,opt,name=placeholder_body,json=placeholderBody" json:"placeholder_body,omitempty"`
	// Required. Should match Chromium enum at
	// ios/chrome/browser/push_notification/model/push_notification_client_id.h.
	PushNotificationClientId *string `protobuf:"bytes,8,opt,name=push_notification_client_id,json=pushNotificationClientId" json:"push_notification_client_id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PushNotificationMessage) Reset() {
	*x = PushNotificationMessage{}
	mi := &file_components_sync_protocol_unencrypted_sharing_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushNotificationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushNotificationMessage) ProtoMessage() {}

func (x *PushNotificationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_unencrypted_sharing_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushNotificationMessage.ProtoReflect.Descriptor instead.
func (*PushNotificationMessage) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_unencrypted_sharing_message_proto_rawDescGZIP(), []int{1}
}

func (x *PushNotificationMessage) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *PushNotificationMessage) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *PushNotificationMessage) GetIcon() []*PushNotificationMessage_Image {
	if x != nil {
		return x.Icon
	}
	return nil
}

func (x *PushNotificationMessage) GetFavicon() *PushNotificationMessage_Image {
	if x != nil {
		return x.Favicon
	}
	return nil
}

func (x *PushNotificationMessage) GetDestinationUrl() string {
	if x != nil && x.DestinationUrl != nil {
		return *x.DestinationUrl
	}
	return ""
}

func (x *PushNotificationMessage) GetPlaceholderTitle() string {
	if x != nil && x.PlaceholderTitle != nil {
		return *x.PlaceholderTitle
	}
	return ""
}

func (x *PushNotificationMessage) GetPlaceholderBody() string {
	if x != nil && x.PlaceholderBody != nil {
		return *x.PlaceholderBody
	}
	return ""
}

func (x *PushNotificationMessage) GetPushNotificationClientId() string {
	if x != nil && x.PushNotificationClientId != nil {
		return *x.PushNotificationClientId
	}
	return ""
}

// Message specific to desktop-to-mobile promo notifications.
type DesktopToMobilePromoMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Contains the common fields required to configure a push
	// notification.
	PushNotification *PushNotificationMessage `protobuf:"bytes,1,opt,name=push_notification,json=pushNotification" json:"push_notification,omitempty"`
	// Required. Should match Chromium enum desktop_to_mobile_promos::PromoType at
	// components/desktop_to_mobile_promos/promos_types.h.
	PromoType     *int32 `protobuf:"varint,2,opt,name=promo_type,json=promoType" json:"promo_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesktopToMobilePromoMessage) Reset() {
	*x = DesktopToMobilePromoMessage{}
	mi := &file_components_sync_protocol_unencrypted_sharing_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesktopToMobilePromoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopToMobilePromoMessage) ProtoMessage() {}

func (x *DesktopToMobilePromoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_unencrypted_sharing_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopToMobilePromoMessage.ProtoReflect.Descriptor instead.
func (*DesktopToMobilePromoMessage) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_unencrypted_sharing_message_proto_rawDescGZIP(), []int{2}
}

func (x *DesktopToMobilePromoMessage) GetPushNotification() *PushNotificationMessage {
	if x != nil {
		return x.PushNotification
	}
	return nil
}

func (x *DesktopToMobilePromoMessage) GetPromoType() int32 {
	if x != nil && x.PromoType != nil {
		return *x.PromoType
	}
	return 0
}

// Message for Send Tab To Self notifications.
type SendTabToSelfPush struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Notification title text to display.
	Title *string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	// Required. Actual body text to display.
	Text *string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	// Optional. An icon to be displayed alongside the notification, or a series
	// of icons to be put in a collage. If no icon is specified, the frontend
	// will display a generic icon image.
	Icon []*SendTabToSelfPush_Image `protobuf:"bytes,3,rep,name=icon" json:"icon,omitempty"`
	// Optional. A small app icon to display in certain notification views. This
	// field can be omitted in favor of using a favicon specified in the
	// chrome_chime client config. If this field is omitted and the client config
	// favicon is unspecified, no icon is displayed.
	Favicon *SendTabToSelfPush_Image `protobuf:"bytes,4,opt,name=favicon" json:"favicon,omitempty"`
	// Required. A URL that will be visited when clicking on this notification.
	DestinationUrl *string `protobuf:"bytes,5,opt,name=destination_url,json=destinationUrl" json:"destination_url,omitempty"`
	// Placeholder title. Will be used if payload is not properly assembled on
	// receiving device. Will not get encrypted by Chime.
	PlaceholderTitle *string `protobuf:"bytes,6,opt,name=placeholder_title,json=placeholderTitle" json:"placeholder_title,omitempty"`
	// Placeholder body. Will be used if payload is not properly assembled on
	// receiving device. Will not get encrypted by Chime.
	PlaceholderBody *string `protobuf:"bytes,7,opt,name=placeholder_body,json=placeholderBody" json:"placeholder_body,omitempty"`
	// Unique identifier of the associated SendTabToSelfEntry. Will be used to
	// dismiss the entry upon push notification interaction.
	EntryUniqueGuid *string `protobuf:"bytes,8,opt,name=entry_unique_guid,json=entryUniqueGuid" json:"entry_unique_guid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendTabToSelfPush) Reset() {
	*x = SendTabToSelfPush{}
	mi := &file_components_sync_protocol_unencrypted_sharing_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTabToSelfPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTabToSelfPush) ProtoMessage() {}

func (x *SendTabToSelfPush) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_unencrypted_sharing_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTabToSelfPush.ProtoReflect.Descriptor instead.
func (*SendTabToSelfPush) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_unencrypted_sharing_message_proto_rawDescGZIP(), []int{3}
}

func (x *SendTabToSelfPush) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *SendTabToSelfPush) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *SendTabToSelfPush) GetIcon() []*SendTabToSelfPush_Image {
	if x != nil {
		return x.Icon
	}
	return nil
}

func (x *SendTabToSelfPush) GetFavicon() *SendTabToSelfPush_Image {
	if x != nil {
		return x.Favicon
	}
	return nil
}

func (x *SendTabToSelfPush) GetDestinationUrl() string {
	if x != nil && x.DestinationUrl != nil {
		return *x.DestinationUrl
	}
	return ""
}

func (x *SendTabToSelfPush) GetPlaceholderTitle() string {
	if x != nil && x.PlaceholderTitle != nil {
		return *x.PlaceholderTitle
	}
	return ""
}

func (x *SendTabToSelfPush) GetPlaceholderBody() string {
	if x != nil && x.PlaceholderBody != nil {
		return *x.PlaceholderBody
	}
	return ""
}

func (x *SendTabToSelfPush) GetEntryUniqueGuid() string {
	if x != nil && x.EntryUniqueGuid != nil {
		return *x.EntryUniqueGuid
	}
	return ""
}

type PushNotificationMessage_Image struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. URL of this image resource. FIFE hosted URLs are preferred.
	Url *string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	// Optional. Alternate text to display if the image cannot be found and for
	// accessibility reasons.
	AltText       *string `protobuf:"bytes,2,opt,name=alt_text,json=altText" json:"alt_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushNotificationMessage_Image) Reset() {
	*x = PushNotificationMessage_Image{}
	mi := &file_components_sync_protocol_unencrypted_sharing_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushNotificationMessage_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushNotificationMessage_Image) ProtoMessage() {}

func (x *PushNotificationMessage_Image) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_unencrypted_sharing_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushNotificationMessage_Image.ProtoReflect.Descriptor instead.
func (*PushNotificationMessage_Image) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_unencrypted_sharing_message_proto_rawDescGZIP(), []int{1, 0}
}

func (x *PushNotificationMessage_Image) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *PushNotificationMessage_Image) GetAltText() string {
	if x != nil && x.AltText != nil {
		return *x.AltText
	}
	return ""
}

type SendTabToSelfPush_Image struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. URL of this image resource. FIFE hosted URLs are preferred.
	Url *string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	// Optional. Alternate text to display if the image cannot be found and for
	// accessibility reasons.
	AltText       *string `protobuf:"bytes,2,opt,name=alt_text,json=altText" json:"alt_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTabToSelfPush_Image) Reset() {
	*x = SendTabToSelfPush_Image{}
	mi := &file_components_sync_protocol_unencrypted_sharing_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTabToSelfPush_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTabToSelfPush_Image) ProtoMessage() {}

func (x *SendTabToSelfPush_Image) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_unencrypted_sharing_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTabToSelfPush_Image.ProtoReflect.Descriptor instead.
func (*SendTabToSelfPush_Image) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_unencrypted_sharing_message_proto_rawDescGZIP(), []int{3, 0}
}

func (x *SendTabToSelfPush_Image) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *SendTabToSelfPush_Image) GetAltText() string {
	if x != nil && x.AltText != nil {
		return *x.AltText
	}
	return ""
}

var File_components_sync_protocol_unencrypted_sharing_message_proto protoreflect.FileDescriptor

const file_components_sync_protocol_unencrypted_sharing_message_proto_rawDesc = "" +
	"\n" +
	":components/sync/protocol/unencrypted_sharing_message.proto\x12\async_pb\"\xab\x02\n" +
	"\x19UnencryptedSharingMessage\x12\x1f\n" +
	"\vsender_guid\x18\x01 \x01(\tR\n" +
	"senderGuid\x12F\n" +
	"\x10send_tab_message\x18\x02 \x01(\v2\x1a.sync_pb.SendTabToSelfPushH\x00R\x0esendTabMessage\x12l\n" +
	"\x1fdesktop_to_mobile_promo_message\x18\x04 \x01(\v2$.sync_pb.DesktopToMobilePromoMessageH\x00R\x1bdesktopToMobilePromoMessage\x12,\n" +
	"\x12sender_device_name\x18\x03 \x01(\tR\x10senderDeviceNameB\t\n" +
	"\apayload\"\xb7\x03\n" +
	"\x17PushNotificationMessage\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12:\n" +
	"\x04icon\x18\x03 \x03(\v2&.sync_pb.PushNotificationMessage.ImageR\x04icon\x12@\n" +
	"\afavicon\x18\x04 \x01(\v2&.sync_pb.PushNotificationMessage.ImageR\afavicon\x12'\n" +
	"\x0fdestination_url\x18\x05 \x01(\tR\x0edestinationUrl\x12+\n" +
	"\x11placeholder_title\x18\x06 \x01(\tR\x10placeholderTitle\x12)\n" +
	"\x10placeholder_body\x18\a \x01(\tR\x0fplaceholderBody\x12=\n" +
	"\x1bpush_notification_client_id\x18\b \x01(\tR\x18pushNotificationClientId\x1a4\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x19\n" +
	"\balt_text\x18\x02 \x01(\tR\aaltText\"\x8b\x01\n" +
	"\x1bDesktopToMobilePromoMessage\x12M\n" +
	"\x11push_notification\x18\x01 \x01(\v2 .sync_pb.PushNotificationMessageR\x10pushNotification\x12\x1d\n" +
	"\n" +
	"promo_type\x18\x02 \x01(\x05R\tpromoType\"\x92\x03\n" +
	"\x11SendTabToSelfPush\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x124\n" +
	"\x04icon\x18\x03 \x03(\v2 .sync_pb.SendTabToSelfPush.ImageR\x04icon\x12:\n" +
	"\afavicon\x18\x04 \x01(\v2 .sync_pb.SendTabToSelfPush.ImageR\afavicon\x12'\n" +
	"\x0fdestination_url\x18\x05 \x01(\tR\x0edestinationUrl\x12+\n" +
	"\x11placeholder_title\x18\x06 \x01(\tR\x10placeholderTitle\x12)\n" +
	"\x10placeholder_body\x18\a \x01(\tR\x0fplaceholderBody\x12*\n" +
	"\x11entry_unique_guid\x18\b \x01(\tR\x0fentryUniqueGuid\x1a4\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x19\n" +
	"\balt_text\x18\x02 \x01(\tR\aaltTextB+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_unencrypted_sharing_message_proto_rawDescOnce sync.Once
	file_components_sync_protocol_unencrypted_sharing_message_proto_rawDescData []byte
)

func file_components_sync_protocol_unencrypted_sharing_message_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_unencrypted_sharing_message_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_unencrypted_sharing_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_unencrypted_sharing_message_proto_rawDesc), len(file_components_sync_protocol_unencrypted_sharing_message_proto_rawDesc)))
	})
	return file_components_sync_protocol_unencrypted_sharing_message_proto_rawDescData
}

var file_components_sync_protocol_unencrypted_sharing_message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_components_sync_protocol_unencrypted_sharing_message_proto_goTypes = []any{
	(*UnencryptedSharingMessage)(nil),     // 0: sync_pb.UnencryptedSharingMessage
	(*PushNotificationMessage)(nil),       // 1: sync_pb.PushNotificationMessage
	(*DesktopToMobilePromoMessage)(nil),   // 2: sync_pb.DesktopToMobilePromoMessage
	(*SendTabToSelfPush)(nil),             // 3: sync_pb.SendTabToSelfPush
	(*PushNotificationMessage_Image)(nil), // 4: sync_pb.PushNotificationMessage.Image
	(*SendTabToSelfPush_Image)(nil),       // 5: sync_pb.SendTabToSelfPush.Image
}
var file_components_sync_protocol_unencrypted_sharing_message_proto_depIdxs = []int32{
	3, // 0: sync_pb.UnencryptedSharingMessage.send_tab_message:type_name -> sync_pb.SendTabToSelfPush
	2, // 1: sync_pb.UnencryptedSharingMessage.desktop_to_mobile_promo_message:type_name -> sync_pb.DesktopToMobilePromoMessage
	4, // 2: sync_pb.PushNotificationMessage.icon:type_name -> sync_pb.PushNotificationMessage.Image
	4, // 3: sync_pb.PushNotificationMessage.favicon:type_name -> sync_pb.PushNotificationMessage.Image
	1, // 4: sync_pb.DesktopToMobilePromoMessage.push_notification:type_name -> sync_pb.PushNotificationMessage
	5, // 5: sync_pb.SendTabToSelfPush.icon:type_name -> sync_pb.SendTabToSelfPush.Image
	5, // 6: sync_pb.SendTabToSelfPush.favicon:type_name -> sync_pb.SendTabToSelfPush.Image
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_unencrypted_sharing_message_proto_init() }
func file_components_sync_protocol_unencrypted_sharing_message_proto_init() {
	if File_components_sync_protocol_unencrypted_sharing_message_proto != nil {
		return
	}
	file_components_sync_protocol_unencrypted_sharing_message_proto_msgTypes[0].OneofWrappers = []any{
		(*UnencryptedSharingMessage_SendTabMessage)(nil),
		(*UnencryptedSharingMessage_DesktopToMobilePromoMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_unencrypted_sharing_message_proto_rawDesc), len(file_components_sync_protocol_unencrypted_sharing_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_unencrypted_sharing_message_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_unencrypted_sharing_message_proto_depIdxs,
		MessageInfos:      file_components_sync_protocol_unencrypted_sharing_message_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_unencrypted_sharing_message_proto = out.File
	file_components_sync_protocol_unencrypted_sharing_message_proto_goTypes = nil
	file_components_sync_protocol_unencrypted_sharing_message_proto_depIdxs = nil
}
