// Copyright 2019 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// If you change or add any fields in this file, update
// components/sync/protocol/proto_visitors.h and potentially
// components/sync/protocol/proto_enum_conversions.{h, cc}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/web_app_specifics.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebAppIconInfo_Purpose int32

const (
	WebAppIconInfo_UNSPECIFIED WebAppIconInfo_Purpose = 0
	// Suitable for any purpose.
	WebAppIconInfo_ANY WebAppIconInfo_Purpose = 1
	// Designed for masking.
	WebAppIconInfo_MASKABLE WebAppIconInfo_Purpose = 2
	// Suitable for monochrome purposes.
	WebAppIconInfo_MONOCHROME WebAppIconInfo_Purpose = 3
)

// Enum value maps for WebAppIconInfo_Purpose.
var (
	WebAppIconInfo_Purpose_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ANY",
		2: "MASKABLE",
		3: "MONOCHROME",
	}
	WebAppIconInfo_Purpose_value = map[string]int32{
		"UNSPECIFIED": 0,
		"ANY":         1,
		"MASKABLE":    2,
		"MONOCHROME":  3,
	}
)

func (x WebAppIconInfo_Purpose) Enum() *WebAppIconInfo_Purpose {
	p := new(WebAppIconInfo_Purpose)
	*p = x
	return p
}

func (x WebAppIconInfo_Purpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebAppIconInfo_Purpose) Descriptor() protoreflect.EnumDescriptor {
	return file_components_sync_protocol_web_app_specifics_proto_enumTypes[0].Descriptor()
}

func (WebAppIconInfo_Purpose) Type() protoreflect.EnumType {
	return &file_components_sync_protocol_web_app_specifics_proto_enumTypes[0]
}

func (x WebAppIconInfo_Purpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *WebAppIconInfo_Purpose) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = WebAppIconInfo_Purpose(num)
	return nil
}

// Deprecated: Use WebAppIconInfo_Purpose.Descriptor instead.
func (WebAppIconInfo_Purpose) EnumDescriptor() ([]byte, []int) {
	return file_components_sync_protocol_web_app_specifics_proto_rawDescGZIP(), []int{0, 0}
}

// This enum should be a subset of the DisplayMode enum in
// chrome/browser/web_applications/proto/web_app.proto and
// third_party/blink/public/mojom/manifest/display_mode.mojom
type WebAppSpecifics_UserDisplayMode int32

const (
	WebAppSpecifics_UNSPECIFIED WebAppSpecifics_UserDisplayMode = 0
	WebAppSpecifics_BROWSER     WebAppSpecifics_UserDisplayMode = 1
	// MINIMAL_UI is never serialized.
	WebAppSpecifics_STANDALONE WebAppSpecifics_UserDisplayMode = 3
	// FULLSCREEN is never serialized.
	// WINDOW_CONTROLS_OVERLAY is never serialized.
	WebAppSpecifics_TABBED WebAppSpecifics_UserDisplayMode = 6
)

// Enum value maps for WebAppSpecifics_UserDisplayMode.
var (
	WebAppSpecifics_UserDisplayMode_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "BROWSER",
		3: "STANDALONE",
		6: "TABBED",
	}
	WebAppSpecifics_UserDisplayMode_value = map[string]int32{
		"UNSPECIFIED": 0,
		"BROWSER":     1,
		"STANDALONE":  3,
		"TABBED":      6,
	}
)

func (x WebAppSpecifics_UserDisplayMode) Enum() *WebAppSpecifics_UserDisplayMode {
	p := new(WebAppSpecifics_UserDisplayMode)
	*p = x
	return p
}

func (x WebAppSpecifics_UserDisplayMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebAppSpecifics_UserDisplayMode) Descriptor() protoreflect.EnumDescriptor {
	return file_components_sync_protocol_web_app_specifics_proto_enumTypes[1].Descriptor()
}

func (WebAppSpecifics_UserDisplayMode) Type() protoreflect.EnumType {
	return &file_components_sync_protocol_web_app_specifics_proto_enumTypes[1]
}

func (x WebAppSpecifics_UserDisplayMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *WebAppSpecifics_UserDisplayMode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = WebAppSpecifics_UserDisplayMode(num)
	return nil
}

// Deprecated: Use WebAppSpecifics_UserDisplayMode.Descriptor instead.
func (WebAppSpecifics_UserDisplayMode) EnumDescriptor() ([]byte, []int) {
	return file_components_sync_protocol_web_app_specifics_proto_rawDescGZIP(), []int{1, 0}
}

// Sync & local data: Information about web app icon.
type WebAppIconInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The size of the square app icon, in raw pixels.
	SizeInPx *int32 `protobuf:"varint,1,opt,name=size_in_px,json=sizeInPx" json:"size_in_px,omitempty"`
	// The URL of the app icon.
	Url *string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	// The purpose or context in which the icon should be used.
	Purpose       *WebAppIconInfo_Purpose `protobuf:"varint,3,opt,name=purpose,enum=sync_pb.WebAppIconInfo_Purpose" json:"purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebAppIconInfo) Reset() {
	*x = WebAppIconInfo{}
	mi := &file_components_sync_protocol_web_app_specifics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAppIconInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAppIconInfo) ProtoMessage() {}

func (x *WebAppIconInfo) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_web_app_specifics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAppIconInfo.ProtoReflect.Descriptor instead.
func (*WebAppIconInfo) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_web_app_specifics_proto_rawDescGZIP(), []int{0}
}

func (x *WebAppIconInfo) GetSizeInPx() int32 {
	if x != nil && x.SizeInPx != nil {
		return *x.SizeInPx
	}
	return 0
}

func (x *WebAppIconInfo) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *WebAppIconInfo) GetPurpose() WebAppIconInfo_Purpose {
	if x != nil && x.Purpose != nil {
		return *x.Purpose
	}
	return WebAppIconInfo_UNSPECIFIED
}

// WebApp data. This is a synced part of
// chrome/browser/web_applications/proto/web_app.proto data.
// Note: Pre-M125 clients will incorrectly drop any unrecognized new fields
// added to the proto. Handling should be added to ApplySyncDataToApp in
// web_app_sync_bridge.cc if new fields need to be preserved.
type WebAppSpecifics struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	StartUrl *string                `protobuf:"bytes,1,opt,name=start_url,json=startUrl" json:"start_url,omitempty"`
	Name     *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// User-selected display setting, which may be used if no platform-specific
	// setting is available (eg. on Windows, Mac, and Linux). If absent,
	// user_display_mode_cros may be used as fallback (if populated). On pre-M122
	// devices this field is used by all platforms (ie. ChromeOS, Windows, Mac,
	// Linux) and always replaces any locally-stored value, with
	// absent/unspecified falling back to standalone.
	UserDisplayModeDefault *WebAppSpecifics_UserDisplayMode `protobuf:"varint,3,opt,name=user_display_mode_default,json=userDisplayModeDefault,enum=sync_pb.WebAppSpecifics_UserDisplayMode" json:"user_display_mode_default,omitempty"`
	ThemeColor             *uint32                          `protobuf:"varint,4,opt,name=theme_color,json=themeColor" json:"theme_color,omitempty"`
	Scope                  *string                          `protobuf:"bytes,5,opt,name=scope" json:"scope,omitempty"`
	IconInfos              []*WebAppIconInfo                `protobuf:"bytes,6,rep,name=icon_infos,json=iconInfos" json:"icon_infos,omitempty"`
	// Used to store the page number that the app is displayed on in
	// chrome://apps.
	UserPageOrdinal *string `protobuf:"bytes,7,opt,name=user_page_ordinal,json=userPageOrdinal" json:"user_page_ordinal,omitempty"`
	// Used to store the in-page ranking for ordering apps in its given
	// `user_page_ordinal` page.
	UserLaunchOrdinal *string `protobuf:"bytes,8,opt,name=user_launch_ordinal,json=userLaunchOrdinal" json:"user_launch_ordinal,omitempty"`
	// Used to store id specified in the manifest. This is a path that is relative
	// to the start_url, similar to how the id field is parsed in
	// https://www.w3.org/TR/appmanifest/#id-member, except this field does not
	// include a scheme or origin. This is only the path after the origin,
	// excluding the first "/".
	// Note: If this field is not set, then the manifest_id is generated using the
	// start_url in GenerateManifestIdFromStartUrlOnly. This is different than if
	// this is set to "", which means the manifest_id will be set to the origin of
	// the start_url.
	RelativeManifestId *string `protobuf:"bytes,9,opt,name=relative_manifest_id,json=relativeManifestId" json:"relative_manifest_id,omitempty"`
	// User-selected display setting for ChromeOS.
	// If absent, user_display_mode_default may be used as fallback (if
	// populated).
	// Introduced in M122.
	UserDisplayModeCros *WebAppSpecifics_UserDisplayMode `protobuf:"varint,10,opt,name=user_display_mode_cros,json=userDisplayModeCros,enum=sync_pb.WebAppSpecifics_UserDisplayMode" json:"user_display_mode_cros,omitempty"`
	// Contains the metadata for the trusted icons to be shown on security
	// sensitive surfaces by the web app.
	TrustedIcons []*WebAppIconInfo `protobuf:"bytes,11,rep,name=trusted_icons,json=trustedIcons" json:"trusted_icons,omitempty"`
	// If this app has been migrated from another app, set the source manifest id
	// to allow handling of the app migration handled on the device this app gets
	// synced into.
	MigratedFromManifestId *string `protobuf:"bytes,12,opt,name=migrated_from_manifest_id,json=migratedFromManifestId" json:"migrated_from_manifest_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *WebAppSpecifics) Reset() {
	*x = WebAppSpecifics{}
	mi := &file_components_sync_protocol_web_app_specifics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAppSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAppSpecifics) ProtoMessage() {}

func (x *WebAppSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_web_app_specifics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAppSpecifics.ProtoReflect.Descriptor instead.
func (*WebAppSpecifics) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_web_app_specifics_proto_rawDescGZIP(), []int{1}
}

func (x *WebAppSpecifics) GetStartUrl() string {
	if x != nil && x.StartUrl != nil {
		return *x.StartUrl
	}
	return ""
}

func (x *WebAppSpecifics) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *WebAppSpecifics) GetUserDisplayModeDefault() WebAppSpecifics_UserDisplayMode {
	if x != nil && x.UserDisplayModeDefault != nil {
		return *x.UserDisplayModeDefault
	}
	return WebAppSpecifics_UNSPECIFIED
}

func (x *WebAppSpecifics) GetThemeColor() uint32 {
	if x != nil && x.ThemeColor != nil {
		return *x.ThemeColor
	}
	return 0
}

func (x *WebAppSpecifics) GetScope() string {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return ""
}

func (x *WebAppSpecifics) GetIconInfos() []*WebAppIconInfo {
	if x != nil {
		return x.IconInfos
	}
	return nil
}

func (x *WebAppSpecifics) GetUserPageOrdinal() string {
	if x != nil && x.UserPageOrdinal != nil {
		return *x.UserPageOrdinal
	}
	return ""
}

func (x *WebAppSpecifics) GetUserLaunchOrdinal() string {
	if x != nil && x.UserLaunchOrdinal != nil {
		return *x.UserLaunchOrdinal
	}
	return ""
}

func (x *WebAppSpecifics) GetRelativeManifestId() string {
	if x != nil && x.RelativeManifestId != nil {
		return *x.RelativeManifestId
	}
	return ""
}

func (x *WebAppSpecifics) GetUserDisplayModeCros() WebAppSpecifics_UserDisplayMode {
	if x != nil && x.UserDisplayModeCros != nil {
		return *x.UserDisplayModeCros
	}
	return WebAppSpecifics_UNSPECIFIED
}

func (x *WebAppSpecifics) GetTrustedIcons() []*WebAppIconInfo {
	if x != nil {
		return x.TrustedIcons
	}
	return nil
}

func (x *WebAppSpecifics) GetMigratedFromManifestId() string {
	if x != nil && x.MigratedFromManifestId != nil {
		return *x.MigratedFromManifestId
	}
	return ""
}

var File_components_sync_protocol_web_app_specifics_proto protoreflect.FileDescriptor

const file_components_sync_protocol_web_app_specifics_proto_rawDesc = "" +
	"\n" +
	"0components/sync/protocol/web_app_specifics.proto\x12\async_pb\"\xbe\x01\n" +
	"\x0eWebAppIconInfo\x12\x1c\n" +
	"\n" +
	"size_in_px\x18\x01 \x01(\x05R\bsizeInPx\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x129\n" +
	"\apurpose\x18\x03 \x01(\x0e2\x1f.sync_pb.WebAppIconInfo.PurposeR\apurpose\"A\n" +
	"\aPurpose\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\a\n" +
	"\x03ANY\x10\x01\x12\f\n" +
	"\bMASKABLE\x10\x02\x12\x0e\n" +
	"\n" +
	"MONOCHROME\x10\x03\"\xf8\x05\n" +
	"\x0fWebAppSpecifics\x12\x1b\n" +
	"\tstart_url\x18\x01 \x01(\tR\bstartUrl\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12c\n" +
	"\x19user_display_mode_default\x18\x03 \x01(\x0e2(.sync_pb.WebAppSpecifics.UserDisplayModeR\x16userDisplayModeDefault\x12\x1f\n" +
	"\vtheme_color\x18\x04 \x01(\rR\n" +
	"themeColor\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x126\n" +
	"\n" +
	"icon_infos\x18\x06 \x03(\v2\x17.sync_pb.WebAppIconInfoR\ticonInfos\x12*\n" +
	"\x11user_page_ordinal\x18\a \x01(\tR\x0fuserPageOrdinal\x12.\n" +
	"\x13user_launch_ordinal\x18\b \x01(\tR\x11userLaunchOrdinal\x120\n" +
	"\x14relative_manifest_id\x18\t \x01(\tR\x12relativeManifestId\x12]\n" +
	"\x16user_display_mode_cros\x18\n" +
	" \x01(\x0e2(.sync_pb.WebAppSpecifics.UserDisplayModeR\x13userDisplayModeCros\x12<\n" +
	"\rtrusted_icons\x18\v \x03(\v2\x17.sync_pb.WebAppIconInfoR\ftrustedIcons\x129\n" +
	"\x19migrated_from_manifest_id\x18\f \x01(\tR\x16migratedFromManifestId\"K\n" +
	"\x0fUserDisplayMode\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aBROWSER\x10\x01\x12\x0e\n" +
	"\n" +
	"STANDALONE\x10\x03\x12\n" +
	"\n" +
	"\x06TABBED\x10\x06R\x1auser_display_mode_non_crosR\x11user_display_modeB+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_web_app_specifics_proto_rawDescOnce sync.Once
	file_components_sync_protocol_web_app_specifics_proto_rawDescData []byte
)

func file_components_sync_protocol_web_app_specifics_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_web_app_specifics_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_web_app_specifics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_web_app_specifics_proto_rawDesc), len(file_components_sync_protocol_web_app_specifics_proto_rawDesc)))
	})
	return file_components_sync_protocol_web_app_specifics_proto_rawDescData
}

var file_components_sync_protocol_web_app_specifics_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_components_sync_protocol_web_app_specifics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_components_sync_protocol_web_app_specifics_proto_goTypes = []any{
	(WebAppIconInfo_Purpose)(0),          // 0: sync_pb.WebAppIconInfo.Purpose
	(WebAppSpecifics_UserDisplayMode)(0), // 1: sync_pb.WebAppSpecifics.UserDisplayMode
	(*WebAppIconInfo)(nil),               // 2: sync_pb.WebAppIconInfo
	(*WebAppSpecifics)(nil),              // 3: sync_pb.WebAppSpecifics
}
var file_components_sync_protocol_web_app_specifics_proto_depIdxs = []int32{
	0, // 0: sync_pb.WebAppIconInfo.purpose:type_name -> sync_pb.WebAppIconInfo.Purpose
	1, // 1: sync_pb.WebAppSpecifics.user_display_mode_default:type_name -> sync_pb.WebAppSpecifics.UserDisplayMode
	2, // 2: sync_pb.WebAppSpecifics.icon_infos:type_name -> sync_pb.WebAppIconInfo
	1, // 3: sync_pb.WebAppSpecifics.user_display_mode_cros:type_name -> sync_pb.WebAppSpecifics.UserDisplayMode
	2, // 4: sync_pb.WebAppSpecifics.trusted_icons:type_name -> sync_pb.WebAppIconInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_web_app_specifics_proto_init() }
func file_components_sync_protocol_web_app_specifics_proto_init() {
	if File_components_sync_protocol_web_app_specifics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_web_app_specifics_proto_rawDesc), len(file_components_sync_protocol_web_app_specifics_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_web_app_specifics_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_web_app_specifics_proto_depIdxs,
		EnumInfos:         file_components_sync_protocol_web_app_specifics_proto_enumTypes,
		MessageInfos:      file_components_sync_protocol_web_app_specifics_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_web_app_specifics_proto = out.File
	file_components_sync_protocol_web_app_specifics_proto_goTypes = nil
	file_components_sync_protocol_web_app_specifics_proto_depIdxs = nil
}
