// Copyright 2023 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// If you change or add any fields in this file, update
// components/sync/protocol/proto_visitors.h and potentially
// components/sync/protocol/proto_enum_conversions.{h, cc}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/web_apk_specifics.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebApkIconInfo_Purpose int32

const (
	WebApkIconInfo_UNSPECIFIED WebApkIconInfo_Purpose = 0
	// Suitable for any purpose.
	WebApkIconInfo_ANY WebApkIconInfo_Purpose = 1
	// Designed for masking.
	WebApkIconInfo_MASKABLE WebApkIconInfo_Purpose = 2
	// Suitable for monochrome purposes.
	WebApkIconInfo_MONOCHROME WebApkIconInfo_Purpose = 3
)

// Enum value maps for WebApkIconInfo_Purpose.
var (
	WebApkIconInfo_Purpose_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ANY",
		2: "MASKABLE",
		3: "MONOCHROME",
	}
	WebApkIconInfo_Purpose_value = map[string]int32{
		"UNSPECIFIED": 0,
		"ANY":         1,
		"MASKABLE":    2,
		"MONOCHROME":  3,
	}
)

func (x WebApkIconInfo_Purpose) Enum() *WebApkIconInfo_Purpose {
	p := new(WebApkIconInfo_Purpose)
	*p = x
	return p
}

func (x WebApkIconInfo_Purpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebApkIconInfo_Purpose) Descriptor() protoreflect.EnumDescriptor {
	return file_components_sync_protocol_web_apk_specifics_proto_enumTypes[0].Descriptor()
}

func (WebApkIconInfo_Purpose) Type() protoreflect.EnumType {
	return &file_components_sync_protocol_web_apk_specifics_proto_enumTypes[0]
}

func (x WebApkIconInfo_Purpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *WebApkIconInfo_Purpose) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = WebApkIconInfo_Purpose(num)
	return nil
}

// Deprecated: Use WebApkIconInfo_Purpose.Descriptor instead.
func (WebApkIconInfo_Purpose) EnumDescriptor() ([]byte, []int) {
	return file_components_sync_protocol_web_apk_specifics_proto_rawDescGZIP(), []int{0, 0}
}

// Sync & local data: Information about web app icon.
type WebApkIconInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The size of the square app icon, in raw pixels.
	SizeInPx *int32 `protobuf:"varint,1,opt,name=size_in_px,json=sizeInPx" json:"size_in_px,omitempty"`
	// The URL of the app icon.
	Url *string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	// The purpose or context in which the icon should be used.
	Purpose       *WebApkIconInfo_Purpose `protobuf:"varint,3,opt,name=purpose,enum=sync_pb.WebApkIconInfo_Purpose" json:"purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebApkIconInfo) Reset() {
	*x = WebApkIconInfo{}
	mi := &file_components_sync_protocol_web_apk_specifics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebApkIconInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebApkIconInfo) ProtoMessage() {}

func (x *WebApkIconInfo) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_web_apk_specifics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebApkIconInfo.ProtoReflect.Descriptor instead.
func (*WebApkIconInfo) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_web_apk_specifics_proto_rawDescGZIP(), []int{0}
}

func (x *WebApkIconInfo) GetSizeInPx() int32 {
	if x != nil && x.SizeInPx != nil {
		return *x.SizeInPx
	}
	return 0
}

func (x *WebApkIconInfo) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *WebApkIconInfo) GetPurpose() WebApkIconInfo_Purpose {
	if x != nil && x.Purpose != nil {
		return *x.Purpose
	}
	return WebApkIconInfo_UNSPECIFIED
}

// WebApk data.
type WebApkSpecifics struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ManifestId *string                `protobuf:"bytes,1,opt,name=manifest_id,json=manifestId" json:"manifest_id,omitempty"`
	StartUrl   *string                `protobuf:"bytes,2,opt,name=start_url,json=startUrl" json:"start_url,omitempty"`
	Name       *string                `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	ThemeColor *uint32                `protobuf:"varint,4,opt,name=theme_color,json=themeColor" json:"theme_color,omitempty"`
	Scope      *string                `protobuf:"bytes,5,opt,name=scope" json:"scope,omitempty"`
	IconInfos  []*WebApkIconInfo      `protobuf:"bytes,6,rep,name=icon_infos,json=iconInfos" json:"icon_infos,omitempty"`
	// Time when this WebApk was last used or installed.
	// Number of microseconds since 1601, aka Windows epoch.
	LastUsedTimeWindowsEpochMicros *int64 `protobuf:"varint,7,opt,name=last_used_time_windows_epoch_micros,json=lastUsedTimeWindowsEpochMicros" json:"last_used_time_windows_epoch_micros,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *WebApkSpecifics) Reset() {
	*x = WebApkSpecifics{}
	mi := &file_components_sync_protocol_web_apk_specifics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebApkSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebApkSpecifics) ProtoMessage() {}

func (x *WebApkSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_web_apk_specifics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebApkSpecifics.ProtoReflect.Descriptor instead.
func (*WebApkSpecifics) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_web_apk_specifics_proto_rawDescGZIP(), []int{1}
}

func (x *WebApkSpecifics) GetManifestId() string {
	if x != nil && x.ManifestId != nil {
		return *x.ManifestId
	}
	return ""
}

func (x *WebApkSpecifics) GetStartUrl() string {
	if x != nil && x.StartUrl != nil {
		return *x.StartUrl
	}
	return ""
}

func (x *WebApkSpecifics) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *WebApkSpecifics) GetThemeColor() uint32 {
	if x != nil && x.ThemeColor != nil {
		return *x.ThemeColor
	}
	return 0
}

func (x *WebApkSpecifics) GetScope() string {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return ""
}

func (x *WebApkSpecifics) GetIconInfos() []*WebApkIconInfo {
	if x != nil {
		return x.IconInfos
	}
	return nil
}

func (x *WebApkSpecifics) GetLastUsedTimeWindowsEpochMicros() int64 {
	if x != nil && x.LastUsedTimeWindowsEpochMicros != nil {
		return *x.LastUsedTimeWindowsEpochMicros
	}
	return 0
}

var File_components_sync_protocol_web_apk_specifics_proto protoreflect.FileDescriptor

const file_components_sync_protocol_web_apk_specifics_proto_rawDesc = "" +
	"\n" +
	"0components/sync/protocol/web_apk_specifics.proto\x12\async_pb\"\xbe\x01\n" +
	"\x0eWebApkIconInfo\x12\x1c\n" +
	"\n" +
	"size_in_px\x18\x01 \x01(\x05R\bsizeInPx\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x129\n" +
	"\apurpose\x18\x03 \x01(\x0e2\x1f.sync_pb.WebApkIconInfo.PurposeR\apurpose\"A\n" +
	"\aPurpose\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\a\n" +
	"\x03ANY\x10\x01\x12\f\n" +
	"\bMASKABLE\x10\x02\x12\x0e\n" +
	"\n" +
	"MONOCHROME\x10\x03\"\x9f\x02\n" +
	"\x0fWebApkSpecifics\x12\x1f\n" +
	"\vmanifest_id\x18\x01 \x01(\tR\n" +
	"manifestId\x12\x1b\n" +
	"\tstart_url\x18\x02 \x01(\tR\bstartUrl\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vtheme_color\x18\x04 \x01(\rR\n" +
	"themeColor\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x126\n" +
	"\n" +
	"icon_infos\x18\x06 \x03(\v2\x17.sync_pb.WebApkIconInfoR\ticonInfos\x12K\n" +
	"#last_used_time_windows_epoch_micros\x18\a \x01(\x03R\x1elastUsedTimeWindowsEpochMicrosB+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_web_apk_specifics_proto_rawDescOnce sync.Once
	file_components_sync_protocol_web_apk_specifics_proto_rawDescData []byte
)

func file_components_sync_protocol_web_apk_specifics_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_web_apk_specifics_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_web_apk_specifics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_web_apk_specifics_proto_rawDesc), len(file_components_sync_protocol_web_apk_specifics_proto_rawDesc)))
	})
	return file_components_sync_protocol_web_apk_specifics_proto_rawDescData
}

var file_components_sync_protocol_web_apk_specifics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_components_sync_protocol_web_apk_specifics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_components_sync_protocol_web_apk_specifics_proto_goTypes = []any{
	(WebApkIconInfo_Purpose)(0), // 0: sync_pb.WebApkIconInfo.Purpose
	(*WebApkIconInfo)(nil),      // 1: sync_pb.WebApkIconInfo
	(*WebApkSpecifics)(nil),     // 2: sync_pb.WebApkSpecifics
}
var file_components_sync_protocol_web_apk_specifics_proto_depIdxs = []int32{
	0, // 0: sync_pb.WebApkIconInfo.purpose:type_name -> sync_pb.WebApkIconInfo.Purpose
	1, // 1: sync_pb.WebApkSpecifics.icon_infos:type_name -> sync_pb.WebApkIconInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_web_apk_specifics_proto_init() }
func file_components_sync_protocol_web_apk_specifics_proto_init() {
	if File_components_sync_protocol_web_apk_specifics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_web_apk_specifics_proto_rawDesc), len(file_components_sync_protocol_web_apk_specifics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_web_apk_specifics_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_web_apk_specifics_proto_depIdxs,
		EnumInfos:         file_components_sync_protocol_web_apk_specifics_proto_enumTypes,
		MessageInfos:      file_components_sync_protocol_web_apk_specifics_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_web_apk_specifics_proto = out.File
	file_components_sync_protocol_web_apk_specifics_proto_goTypes = nil
	file_components_sync_protocol_web_apk_specifics_proto_depIdxs = nil
}
