// Copyright 2021 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// If you change or add any fields in this file, update proto_visitors.h and
// potentially proto_enum_conversions.{h, cc}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: components/sync/protocol/webauthn_credential_specifics.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WebauthnCredentialSpecifics is an entity that backs a WebAuthn
// PublicKeyCredential. Since it contains the authenticator’s view of this
// object, it has a private key rather than a public key.
// (https://www.w3.org/TR/webauthn-2/#iface-pkcredential).
//
// Names of fields are taken from WebAuthn where possible. E.g.
// user.displayName in WebAuthn becomes user_display_name here.
//
// All fields are immutable after creation except for user_name and
// user_display_name, which may be updated by a user.
type WebauthnCredentialSpecifics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sync's ID for this entity (sometimes called the client unique tag), 16
	// random bytes. This value is used within Sync to identify this entity. The
	// credential ID is not used because the (hashed) sync_id is exposed to the
	// Sync server, and we don’t want Google to be able to map a credential ID to
	// an account. Password entities construct this value from the concatenation
	// of many fields and depend on the fact that the server only sees a hash of
	// it. But the only high-entropy secret here is the private key, which will
	// have different encryption in the future, and private keys are not the sort
	// of data to copy into other fields. Therefore this independent value is
	// provided to form the client's ID.
	SyncId []byte `protobuf:"bytes,1,opt,name=sync_id,json=syncId" json:"sync_id,omitempty"`
	// The credential ID, 16 random bytes. This is a value surfaced in
	// the WebAuthn API (https://www.w3.org/TR/webauthn-2/#credential-id).
	CredentialId []byte `protobuf:"bytes,2,opt,name=credential_id,json=credentialId" json:"credential_id,omitempty"`
	// An RP ID is a WebAuthn concept:
	// https://www.w3.org/TR/webauthn-2/#rp-id. It’s usually a domain name,
	// although in non-Web contexts it can be a URL with a non-Web scheme.
	RpId *string `protobuf:"bytes,3,opt,name=rp_id,json=rpId" json:"rp_id,omitempty"`
	// The user ID, which is also called a “user handle” in WebAuthn
	// (https://www.w3.org/TR/webauthn-2/#user-handle), is an RP-specific
	// identifier that is up to 64-bytes long. An authenticator conceptually only
	// stores a single credential for a given (rp_id, user_id) pair, but there
	// may be several credentials in Sync. They are prioritised using
	// newly_shadowed_credential_ids and creation_time. See below.
	//
	// (We wish to be able to retain several entities for a single (rp_id,
	// user_id) pair because there’s an edge case where we may wish to revert to
	// an older entry and thus need to keep the older entry around in Sync. The
	// revert could happen on a different device too.)
	UserId []byte `protobuf:"bytes,4,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	// The id of credentials with the same (rp_id, user_id) that were
	// shadowed by the creation of this entity.
	//
	// A credential is shadowed if one or more other credentials (from the same
	// account, and with the same (rp_id, user_id)) include its credential_id in
	// their list of shadowed IDs. Shadowed credentials are ignored when finding
	// a credential to sign with. If there is more than one candidate remaining
	// after filtering shadowed credentials then the most recently created (based
	// on creation_time) is used.
	//
	// The reason for all this is that sites can replace a credential by creating
	// another one with the same (rp_id, user_id) pair. However, we don't
	// immediately know whether the WebAuthn response reached the website's
	// server. Consider a user with a poor internet connection. Javascript in the
	// site's origin triggers a credential creation that “overwrites” an existing
	// credential, but the Javascript is unable to send the new public key to the
	// website's server. The user is now locked out: the old credential has been
	// over-written but the website's server doesn't know about the new one.
	//
	// Thus we wish to keep “overwritten” credentials around for a while to allow
	// for some sort of recovery. In the simple case, a new credential shadows
	// the single, previous old credential. We could depend on creation_time, but
	// client clocks aren't always accurate, thus this field.
	//
	// In complicated cases two devices might race to replace a credential, in
	// which case (after mutual syncing) two candidate credentials exist for the
	// same (rp_id, user_id) pair because neither shadows the other. In this case
	// we pick the newest based on `creation_time` but it's quite possible that
	// some recovery will be needed because the website's server thinks the other
	// one is correct.
	//
	// A generation counter isn't used because a single device might replace a
	// series of credentials as it tries to update the website's server. But that
	// doesn't mean that it should dominate a different device that replaced it
	// only once, but later.
	NewlyShadowedCredentialIds [][]byte `protobuf:"bytes,5,rep,name=newly_shadowed_credential_ids,json=newlyShadowedCredentialIds" json:"newly_shadowed_credential_ids,omitempty"`
	// The local time on the device when this credential was created. Given in
	// milliseconds since the UNIX epoch. This is used to break ties between
	// credentials. See newly_shadowed_credential_ids.
	CreationTime *int64 `protobuf:"varint,6,opt,name=creation_time,json=creationTime" json:"creation_time,omitempty"`
	// The human-readable account identifier. Usually an email address. This is
	// mutable.
	// https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialentity-name
	UserName *string `protobuf:"bytes,7,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	// The human-readable name. Usually a legal name. This is mutable.
	// https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialuserentity-displayname.
	UserDisplayName *string `protobuf:"bytes,8,opt,name=user_display_name,json=userDisplayName" json:"user_display_name,omitempty"`
	// Credentials may optionally be enabled for Secure Payment Confirmation[1] on
	// third-party sites. This is opt-in at creation time.
	//
	// [1] https://www.w3.org/TR/secure-payment-confirmation/
	ThirdPartyPaymentsSupport *bool `protobuf:"varint,11,opt,name=third_party_payments_support,json=thirdPartyPaymentsSupport" json:"third_party_payments_support,omitempty"`
	// Time when this passkey was last successfully asserted. Number of
	// microseconds since 1601, aka Windows epoch. This mirrors the
	// `date_last_used` field in PasswordSpecificsData.
	LastUsedTimeWindowsEpochMicros *int64 `protobuf:"varint,13,opt,name=last_used_time_windows_epoch_micros,json=lastUsedTimeWindowsEpochMicros" json:"last_used_time_windows_epoch_micros,omitempty"`
	// The "version" (sometimes called the epoch) of the key that `encrypted_data`
	// is encrypted with. This allows trial decryption to be avoided when present.
	KeyVersion *int32 `protobuf:"varint,14,opt,name=key_version,json=keyVersion" json:"key_version,omitempty"`
	// The key version of the device authorization key that
	// `device_authorization_encrypted` in `SecurityDomainEncrypted` is encrypted
	// with.
	DeviceAuthorizationKeyVersion *int32 `protobuf:"varint,18,opt,name=device_authorization_key_version,json=deviceAuthorizationKeyVersion" json:"device_authorization_key_version,omitempty"`
	// Types that are valid to be assigned to EncryptedData:
	//
	//	*WebauthnCredentialSpecifics_PrivateKey
	//	*WebauthnCredentialSpecifics_Encrypted_
	//	*WebauthnCredentialSpecifics_SecurityDomainEncrypted_
	EncryptedData isWebauthnCredentialSpecifics_EncryptedData `protobuf_oneof:"encrypted_data"`
	// `edited_by_user` is set to `true` the first time a user manually changes
	// the credential's `user_name` or `user_display_name`.
	EditedByUser *bool `protobuf:"varint,15,opt,name=edited_by_user,json=editedByUser" json:"edited_by_user,omitempty"`
	// `hidden` is set to `true` if the credential should not be shown on
	// authentication surfaces, e.g. because a site marked it as obsolete.
	Hidden *bool `protobuf:"varint,16,opt,name=hidden" json:"hidden,omitempty"`
	// The local time on the device when this credential was hidden. Given in
	// milliseconds since the UNIX epoch. This is used to permanently delete
	// credentials after they've been hidden for a while.
	HiddenTime    *int64 `protobuf:"varint,17,opt,name=hidden_time,json=hiddenTime" json:"hidden_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebauthnCredentialSpecifics) Reset() {
	*x = WebauthnCredentialSpecifics{}
	mi := &file_components_sync_protocol_webauthn_credential_specifics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebauthnCredentialSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebauthnCredentialSpecifics) ProtoMessage() {}

func (x *WebauthnCredentialSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_webauthn_credential_specifics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebauthnCredentialSpecifics.ProtoReflect.Descriptor instead.
func (*WebauthnCredentialSpecifics) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_webauthn_credential_specifics_proto_rawDescGZIP(), []int{0}
}

func (x *WebauthnCredentialSpecifics) GetSyncId() []byte {
	if x != nil {
		return x.SyncId
	}
	return nil
}

func (x *WebauthnCredentialSpecifics) GetCredentialId() []byte {
	if x != nil {
		return x.CredentialId
	}
	return nil
}

func (x *WebauthnCredentialSpecifics) GetRpId() string {
	if x != nil && x.RpId != nil {
		return *x.RpId
	}
	return ""
}

func (x *WebauthnCredentialSpecifics) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *WebauthnCredentialSpecifics) GetNewlyShadowedCredentialIds() [][]byte {
	if x != nil {
		return x.NewlyShadowedCredentialIds
	}
	return nil
}

func (x *WebauthnCredentialSpecifics) GetCreationTime() int64 {
	if x != nil && x.CreationTime != nil {
		return *x.CreationTime
	}
	return 0
}

func (x *WebauthnCredentialSpecifics) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *WebauthnCredentialSpecifics) GetUserDisplayName() string {
	if x != nil && x.UserDisplayName != nil {
		return *x.UserDisplayName
	}
	return ""
}

func (x *WebauthnCredentialSpecifics) GetThirdPartyPaymentsSupport() bool {
	if x != nil && x.ThirdPartyPaymentsSupport != nil {
		return *x.ThirdPartyPaymentsSupport
	}
	return false
}

func (x *WebauthnCredentialSpecifics) GetLastUsedTimeWindowsEpochMicros() int64 {
	if x != nil && x.LastUsedTimeWindowsEpochMicros != nil {
		return *x.LastUsedTimeWindowsEpochMicros
	}
	return 0
}

func (x *WebauthnCredentialSpecifics) GetKeyVersion() int32 {
	if x != nil && x.KeyVersion != nil {
		return *x.KeyVersion
	}
	return 0
}

func (x *WebauthnCredentialSpecifics) GetDeviceAuthorizationKeyVersion() int32 {
	if x != nil && x.DeviceAuthorizationKeyVersion != nil {
		return *x.DeviceAuthorizationKeyVersion
	}
	return 0
}

func (x *WebauthnCredentialSpecifics) GetEncryptedData() isWebauthnCredentialSpecifics_EncryptedData {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *WebauthnCredentialSpecifics) GetPrivateKey() []byte {
	if x != nil {
		if x, ok := x.EncryptedData.(*WebauthnCredentialSpecifics_PrivateKey); ok {
			return x.PrivateKey
		}
	}
	return nil
}

func (x *WebauthnCredentialSpecifics) GetEncrypted() []byte {
	if x != nil {
		if x, ok := x.EncryptedData.(*WebauthnCredentialSpecifics_Encrypted_); ok {
			return x.Encrypted
		}
	}
	return nil
}

func (x *WebauthnCredentialSpecifics) GetSecurityDomainEncrypted() []byte {
	if x != nil {
		if x, ok := x.EncryptedData.(*WebauthnCredentialSpecifics_SecurityDomainEncrypted_); ok {
			return x.SecurityDomainEncrypted
		}
	}
	return nil
}

func (x *WebauthnCredentialSpecifics) GetEditedByUser() bool {
	if x != nil && x.EditedByUser != nil {
		return *x.EditedByUser
	}
	return false
}

func (x *WebauthnCredentialSpecifics) GetHidden() bool {
	if x != nil && x.Hidden != nil {
		return *x.Hidden
	}
	return false
}

func (x *WebauthnCredentialSpecifics) GetHiddenTime() int64 {
	if x != nil && x.HiddenTime != nil {
		return *x.HiddenTime
	}
	return 0
}

type isWebauthnCredentialSpecifics_EncryptedData interface {
	isWebauthnCredentialSpecifics_EncryptedData()
}

type WebauthnCredentialSpecifics_PrivateKey struct {
	// The bytes of the private key, encrypted with a feature-specific security
	// domain.
	PrivateKey []byte `protobuf:"bytes,9,opt,name=private_key,json=privateKey,oneof"`
}

type WebauthnCredentialSpecifics_Encrypted_ struct {
	// A serialized, `Encrypted` message, encrypted with a feature-specific
	// security domain.
	Encrypted []byte `protobuf:"bytes,12,opt,name=encrypted,oneof"`
}

type WebauthnCredentialSpecifics_SecurityDomainEncrypted_ struct {
	// A serialized `SecurityDomainEncrypted` message, encrypted with a
	// feature-specific security domain key.
	SecurityDomainEncrypted []byte `protobuf:"bytes,19,opt,name=security_domain_encrypted,json=securityDomainEncrypted,oneof"`
}

func (*WebauthnCredentialSpecifics_PrivateKey) isWebauthnCredentialSpecifics_EncryptedData() {}

func (*WebauthnCredentialSpecifics_Encrypted_) isWebauthnCredentialSpecifics_EncryptedData() {}

func (*WebauthnCredentialSpecifics_SecurityDomainEncrypted_) isWebauthnCredentialSpecifics_EncryptedData() {
}

type WebauthnCredentialSpecifics_Encrypted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The bytes of the private key, in PKCS#8 format.
	PrivateKey []byte `protobuf:"bytes,1,opt,name=private_key,json=privateKey" json:"private_key,omitempty"`
	// The secret for implementing the hmac-secret extension
	// https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#sctn-hmac-secret-extension
	HmacSecret []byte `protobuf:"bytes,2,opt,name=hmac_secret,json=hmacSecret" json:"hmac_secret,omitempty"`
	// The contents of the credential's credBlob.
	// https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#sctn-credBlob-extension
	CredBlob []byte `protobuf:"bytes,3,opt,name=cred_blob,json=credBlob" json:"cred_blob,omitempty"`
	// The contents of the credential's largeBlob value(*). Unlike with security
	// keys, largeBlob data is not stored in a single lump for all credentials,
	// but as per-credential data. This data is presented to the authenticator
	// over CTAP and thus has already had the required DEFLATE compression
	// applied by the remote platform. The uncompressed size of this data is in
	// the next field.
	//
	// (*) "large" with respect to embedded devices. Maximum length is 2KiB for
	// Google Password Manager.
	//
	// https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#authenticatorLargeBlobs
	LargeBlob []byte `protobuf:"bytes,4,opt,name=large_blob,json=largeBlob" json:"large_blob,omitempty"`
	// The claimed uncompressed size of the DEFLATE-compressed data in
	// `large_blob`. This corresponds to the `origSize` field from the spec:
	// https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#large-blob
	LargeBlobUncompressedSize *uint64 `protobuf:"varint,5,opt,name=large_blob_uncompressed_size,json=largeBlobUncompressedSize" json:"large_blob_uncompressed_size,omitempty"`
	// The list of Credential Manager Trust Group (CMTG) keys.
	CmtgKeys      []*WebauthnCredentialSpecifics_Encrypted_CmtgKey `protobuf:"bytes,6,rep,name=cmtg_keys,json=cmtgKeys" json:"cmtg_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebauthnCredentialSpecifics_Encrypted) Reset() {
	*x = WebauthnCredentialSpecifics_Encrypted{}
	mi := &file_components_sync_protocol_webauthn_credential_specifics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebauthnCredentialSpecifics_Encrypted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebauthnCredentialSpecifics_Encrypted) ProtoMessage() {}

func (x *WebauthnCredentialSpecifics_Encrypted) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_webauthn_credential_specifics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebauthnCredentialSpecifics_Encrypted.ProtoReflect.Descriptor instead.
func (*WebauthnCredentialSpecifics_Encrypted) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_webauthn_credential_specifics_proto_rawDescGZIP(), []int{0, 0}
}

func (x *WebauthnCredentialSpecifics_Encrypted) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *WebauthnCredentialSpecifics_Encrypted) GetHmacSecret() []byte {
	if x != nil {
		return x.HmacSecret
	}
	return nil
}

func (x *WebauthnCredentialSpecifics_Encrypted) GetCredBlob() []byte {
	if x != nil {
		return x.CredBlob
	}
	return nil
}

func (x *WebauthnCredentialSpecifics_Encrypted) GetLargeBlob() []byte {
	if x != nil {
		return x.LargeBlob
	}
	return nil
}

func (x *WebauthnCredentialSpecifics_Encrypted) GetLargeBlobUncompressedSize() uint64 {
	if x != nil && x.LargeBlobUncompressedSize != nil {
		return *x.LargeBlobUncompressedSize
	}
	return 0
}

func (x *WebauthnCredentialSpecifics_Encrypted) GetCmtgKeys() []*WebauthnCredentialSpecifics_Encrypted_CmtgKey {
	if x != nil {
		return x.CmtgKeys
	}
	return nil
}

type WebauthnCredentialSpecifics_SecurityDomainEncrypted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A serialized `Encrypted` message, encrypted with the device authorization
	// key (see `device_authorization_key_version` for the key version).
	DeviceAuthorizationEncrypted []byte `protobuf:"bytes,1,opt,name=device_authorization_encrypted,json=deviceAuthorizationEncrypted" json:"device_authorization_encrypted,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *WebauthnCredentialSpecifics_SecurityDomainEncrypted) Reset() {
	*x = WebauthnCredentialSpecifics_SecurityDomainEncrypted{}
	mi := &file_components_sync_protocol_webauthn_credential_specifics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebauthnCredentialSpecifics_SecurityDomainEncrypted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebauthnCredentialSpecifics_SecurityDomainEncrypted) ProtoMessage() {}

func (x *WebauthnCredentialSpecifics_SecurityDomainEncrypted) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_webauthn_credential_specifics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebauthnCredentialSpecifics_SecurityDomainEncrypted.ProtoReflect.Descriptor instead.
func (*WebauthnCredentialSpecifics_SecurityDomainEncrypted) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_webauthn_credential_specifics_proto_rawDescGZIP(), []int{0, 1}
}

func (x *WebauthnCredentialSpecifics_SecurityDomainEncrypted) GetDeviceAuthorizationEncrypted() []byte {
	if x != nil {
		return x.DeviceAuthorizationEncrypted
	}
	return nil
}

// Credential Manager Trust Group (CMTG) Keys.
type WebauthnCredentialSpecifics_Encrypted_CmtgKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The private key, encrypted by the Cryptauth provided device keys and
	// encoded in PKCS#8 format. The algorithm matches the passkey private
	// key.
	PrivateKey []byte `protobuf:"bytes,1,opt,name=private_key,json=privateKey" json:"private_key,omitempty"`
	// The local time on the device when this credential was created. Given in
	// milliseconds since the UNIX epoch.
	CreationTimeUnixEpochMillis *int64 `protobuf:"varint,2,opt,name=creation_time_unix_epoch_millis,json=creationTimeUnixEpochMillis" json:"creation_time_unix_epoch_millis,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *WebauthnCredentialSpecifics_Encrypted_CmtgKey) Reset() {
	*x = WebauthnCredentialSpecifics_Encrypted_CmtgKey{}
	mi := &file_components_sync_protocol_webauthn_credential_specifics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebauthnCredentialSpecifics_Encrypted_CmtgKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebauthnCredentialSpecifics_Encrypted_CmtgKey) ProtoMessage() {}

func (x *WebauthnCredentialSpecifics_Encrypted_CmtgKey) ProtoReflect() protoreflect.Message {
	mi := &file_components_sync_protocol_webauthn_credential_specifics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebauthnCredentialSpecifics_Encrypted_CmtgKey.ProtoReflect.Descriptor instead.
func (*WebauthnCredentialSpecifics_Encrypted_CmtgKey) Descriptor() ([]byte, []int) {
	return file_components_sync_protocol_webauthn_credential_specifics_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *WebauthnCredentialSpecifics_Encrypted_CmtgKey) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *WebauthnCredentialSpecifics_Encrypted_CmtgKey) GetCreationTimeUnixEpochMillis() int64 {
	if x != nil && x.CreationTimeUnixEpochMillis != nil {
		return *x.CreationTimeUnixEpochMillis
	}
	return 0
}

var File_components_sync_protocol_webauthn_credential_specifics_proto protoreflect.FileDescriptor

const file_components_sync_protocol_webauthn_credential_specifics_proto_rawDesc = "" +
	"\n" +
	"<components/sync/protocol/webauthn_credential_specifics.proto\x12\async_pb\"\x9f\n" +
	"\n" +
	"\x1bWebauthnCredentialSpecifics\x12\x17\n" +
	"\async_id\x18\x01 \x01(\fR\x06syncId\x12#\n" +
	"\rcredential_id\x18\x02 \x01(\fR\fcredentialId\x12\x13\n" +
	"\x05rp_id\x18\x03 \x01(\tR\x04rpId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\fR\x06userId\x12A\n" +
	"\x1dnewly_shadowed_credential_ids\x18\x05 \x03(\fR\x1anewlyShadowedCredentialIds\x12#\n" +
	"\rcreation_time\x18\x06 \x01(\x03R\fcreationTime\x12\x1b\n" +
	"\tuser_name\x18\a \x01(\tR\buserName\x12*\n" +
	"\x11user_display_name\x18\b \x01(\tR\x0fuserDisplayName\x12?\n" +
	"\x1cthird_party_payments_support\x18\v \x01(\bR\x19thirdPartyPaymentsSupport\x12K\n" +
	"#last_used_time_windows_epoch_micros\x18\r \x01(\x03R\x1elastUsedTimeWindowsEpochMicros\x12\x1f\n" +
	"\vkey_version\x18\x0e \x01(\x05R\n" +
	"keyVersion\x12G\n" +
	" device_authorization_key_version\x18\x12 \x01(\x05R\x1ddeviceAuthorizationKeyVersion\x12!\n" +
	"\vprivate_key\x18\t \x01(\fH\x00R\n" +
	"privateKey\x12\x1e\n" +
	"\tencrypted\x18\f \x01(\fH\x00R\tencrypted\x12<\n" +
	"\x19security_domain_encrypted\x18\x13 \x01(\fH\x00R\x17securityDomainEncrypted\x12$\n" +
	"\x0eedited_by_user\x18\x0f \x01(\bR\feditedByUser\x12\x16\n" +
	"\x06hidden\x18\x10 \x01(\bR\x06hidden\x12\x1f\n" +
	"\vhidden_time\x18\x11 \x01(\x03R\n" +
	"hiddenTime\x1a\x91\x03\n" +
	"\tEncrypted\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\fR\n" +
	"privateKey\x12\x1f\n" +
	"\vhmac_secret\x18\x02 \x01(\fR\n" +
	"hmacSecret\x12\x1b\n" +
	"\tcred_blob\x18\x03 \x01(\fR\bcredBlob\x12\x1d\n" +
	"\n" +
	"large_blob\x18\x04 \x01(\fR\tlargeBlob\x12?\n" +
	"\x1clarge_blob_uncompressed_size\x18\x05 \x01(\x04R\x19largeBlobUncompressedSize\x12S\n" +
	"\tcmtg_keys\x18\x06 \x03(\v26.sync_pb.WebauthnCredentialSpecifics.Encrypted.CmtgKeyR\bcmtgKeys\x1ap\n" +
	"\aCmtgKey\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\fR\n" +
	"privateKey\x12D\n" +
	"\x1fcreation_time_unix_epoch_millis\x18\x02 \x01(\x03R\x1bcreationTimeUnixEpochMillis\x1a_\n" +
	"\x17SecurityDomainEncrypted\x12D\n" +
	"\x1edevice_authorization_encrypted\x18\x01 \x01(\fR\x1cdeviceAuthorizationEncryptedB\x10\n" +
	"\x0eencrypted_dataJ\x04\b\n" +
	"\x10\vB+\n" +
	"%org.chromium.components.sync.protocolH\x03P\x01"

var (
	file_components_sync_protocol_webauthn_credential_specifics_proto_rawDescOnce sync.Once
	file_components_sync_protocol_webauthn_credential_specifics_proto_rawDescData []byte
)

func file_components_sync_protocol_webauthn_credential_specifics_proto_rawDescGZIP() []byte {
	file_components_sync_protocol_webauthn_credential_specifics_proto_rawDescOnce.Do(func() {
		file_components_sync_protocol_webauthn_credential_specifics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_components_sync_protocol_webauthn_credential_specifics_proto_rawDesc), len(file_components_sync_protocol_webauthn_credential_specifics_proto_rawDesc)))
	})
	return file_components_sync_protocol_webauthn_credential_specifics_proto_rawDescData
}

var file_components_sync_protocol_webauthn_credential_specifics_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_components_sync_protocol_webauthn_credential_specifics_proto_goTypes = []any{
	(*WebauthnCredentialSpecifics)(nil),                         // 0: sync_pb.WebauthnCredentialSpecifics
	(*WebauthnCredentialSpecifics_Encrypted)(nil),               // 1: sync_pb.WebauthnCredentialSpecifics.Encrypted
	(*WebauthnCredentialSpecifics_SecurityDomainEncrypted)(nil), // 2: sync_pb.WebauthnCredentialSpecifics.SecurityDomainEncrypted
	(*WebauthnCredentialSpecifics_Encrypted_CmtgKey)(nil),       // 3: sync_pb.WebauthnCredentialSpecifics.Encrypted.CmtgKey
}
var file_components_sync_protocol_webauthn_credential_specifics_proto_depIdxs = []int32{
	3, // 0: sync_pb.WebauthnCredentialSpecifics.Encrypted.cmtg_keys:type_name -> sync_pb.WebauthnCredentialSpecifics.Encrypted.CmtgKey
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_components_sync_protocol_webauthn_credential_specifics_proto_init() }
func file_components_sync_protocol_webauthn_credential_specifics_proto_init() {
	if File_components_sync_protocol_webauthn_credential_specifics_proto != nil {
		return
	}
	file_components_sync_protocol_webauthn_credential_specifics_proto_msgTypes[0].OneofWrappers = []any{
		(*WebauthnCredentialSpecifics_PrivateKey)(nil),
		(*WebauthnCredentialSpecifics_Encrypted_)(nil),
		(*WebauthnCredentialSpecifics_SecurityDomainEncrypted_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_sync_protocol_webauthn_credential_specifics_proto_rawDesc), len(file_components_sync_protocol_webauthn_credential_specifics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_sync_protocol_webauthn_credential_specifics_proto_goTypes,
		DependencyIndexes: file_components_sync_protocol_webauthn_credential_specifics_proto_depIdxs,
		MessageInfos:      file_components_sync_protocol_webauthn_credential_specifics_proto_msgTypes,
	}.Build()
	File_components_sync_protocol_webauthn_credential_specifics_proto = out.File
	file_components_sync_protocol_webauthn_credential_specifics_proto_goTypes = nil
	file_components_sync_protocol_webauthn_credential_specifics_proto_depIdxs = nil
}
